# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0005_offer_esign_document_url_offer_esign_envelope_id_and_more'),
        ('candidates', '0008_candidatefollowuptask_candidateoutreachlog_and_more'),
        ('jobs', '0005_job_degree_optional_note_job_degree_required_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_email', models.EmailField(blank=True, default='', max_length=254)),
                ('report_type', models.CharField(choices=[('fake_job', 'Fake Job Posting'), ('harassment', 'Recruiter Harassment'), ('data_misuse', 'Data Misuse'), ('discriminatory_rejection', 'Discriminatory Rejection'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_abuse_reports', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='jobs.job')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'abuse_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error')], default='pending', max_length=20)),
                ('threat_name', models.CharField(blank=True, default='', max_length=255)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_scan_results', to='tenants.tenant')),
            ],
            options={
                'db_table': 'document_scan_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('verification_method', models.CharField(blank=True, default='', help_text='e.g. linkedin_oauth, manual_id_check, company_email', max_length=50)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('identity_document_url', models.URLField(blank=True, default='', help_text='Stored securely; access-logged')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_verifications', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_verification', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruiter_verifications',
            },
        ),
        migrations.CreateModel(
            name='SafeShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('shared_with_email', models.EmailField(blank=True, default='', max_length=254)),
                ('pii_redacted', models.BooleanField(default=True, help_text='If True, name/contact info is hidden')),
                ('fields_visible', models.JSONField(blank=True, default=list, help_text='["resume", "scores", "work_history"] — fields exposed via this link')),
                ('expires_at', models.DateTimeField()),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_share_links', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_share_links', to='candidates.candidate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_share_links_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_share_links', to='tenants.tenant')),
            ],
            options={
                'db_table': 'safe_share_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateWatermark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file_url', models.URLField()),
                ('watermarked_file_url', models.URLField()),
                ('watermark_token', models.CharField(help_text='Embedded token for forensic tracing', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_watermarks', to='tenants.tenant')),
                ('safe_share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watermarks', to='trust_ops.safesharelink')),
            ],
            options={
                'db_table': 'candidate_watermarks',
            },
        ),
        migrations.CreateModel(
            name='SuspiciousSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signals', models.JSONField(blank=True, default=list, help_text='List of triggered signal codes')),
                ('risk_score', models.FloatField(default=0.0, help_text='0–100 composite fraud risk score')),
                ('status', models.CharField(choices=[('flagged', 'Flagged'), ('investigating', 'Investigating'), ('confirmed_fraud', 'Confirmed Fraud'), ('cleared', 'Cleared')], default='flagged', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_flags', to='applications.application')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_investigations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_submissions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'suspicious_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerDomainVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('dns_token', models.CharField(blank=True, default='', help_text='TXT record value to add to DNS', max_length=128)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_verifications', to='tenants.tenant')),
            ],
            options={
                'db_table': 'employer_domain_verifications',
                'unique_together': {('tenant', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='JobModerationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('discriminatory_language', 'Discriminatory Language'), ('misleading_content', 'Misleading Content'), ('spam', 'Spam / Duplicate'), ('illegal_requirement', 'Illegal Requirement'), ('ai_flagged', 'AI-flagged for Review'), ('user_report', 'User Report'), ('other', 'Other')], max_length=40)),
                ('details', models.TextField(blank=True, default='')),
                ('ai_confidence', models.FloatField(blank=True, help_text='AI-assigned confidence score 0–1 (EU AI Act — shown to reviewer)', null=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited_approved', 'Edited & Approved')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_records', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_moderation_queue', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_moderation_queue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'decision'], name='job_moderat_tenant__cf3485_idx')],
            },
        ),
    ]
