# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('agency_crm', '0001_initial'),
        ('job_orders', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('consultant_performance', 'Consultant Performance'), ('billing_dispute', 'Billing Dispute'), ('compliance', 'Compliance Issue'), ('service_quality', 'Service Quality'), ('timesheet_dispute', 'Timesheet Dispute'), ('other', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='agencies.agency')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_escalations', to=settings.AUTH_USER_MODEL)),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='agency_crm.clientaccount')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_escalation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalJobOrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Agency Review'), ('intake_booked', 'Intake Call Booked'), ('converted', 'Converted to Job Order'), ('declined', 'Declined')], default='submitted', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('staffing_type', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('headcount', models.IntegerField(default=1)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('salary_budget', models.CharField(blank=True, max_length=100)),
                ('requirements', models.TextField(blank=True)),
                ('agency_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_jo_requests', to='agencies.agency')),
                ('attached_job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_requests', to='job_orders.joborder')),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_jo_requests', to='agency_crm.clientaccount')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_jo_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_jo_request',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalShortlistFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('interview_yes', 'Yes – Request Interview'), ('interview_maybe', 'Maybe – Need More Info'), ('no', 'No – Not a Fit'), ('hold', 'Hold for Now')], max_length=30)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_feedback', to='agencies.agency')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_feedback_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_feedbacks', to='submissions.submission')),
            ],
            options={
                'db_table': 'portal_shortlist_feedback',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('attachment_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to='agencies.agency')),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to='agency_crm.clientaccount')),
                ('related_job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_messages', to='job_orders.joborder')),
                ('related_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_messages', to='submissions.submission')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_portal_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_message',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('full', 'Full Access'), ('hiring_manager', 'Hiring Manager'), ('finance', 'Finance / Invoices Only'), ('read_only', 'Read Only')], default='hiring_manager', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accesses', to='agencies.agency')),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accesses', to='agency_crm.clientaccount')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_access', to='agency_crm.clientcontact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_access',
                'unique_together': {('agency', 'client_account', 'user')},
            },
        ),
    ]
