"""
MarketplaceOS — apps.marketplace_analytics

Analytics and marketplace intelligence layer.

Models:
    MarketplaceDailySnapshot    — Daily platform-level KPIs
    ProviderDailySnapshot       — Per-provider daily metrics
    SearchEvent                 — Search query log (anonymized)
    BookingFunnelEvent          — Funnel step tracking
    ProviderViewEvent           — Profile view tracking
    RevenueByCategory           — Rev breakdown by service category
"""
import uuid
from django.db import models
from django.conf import settings


class MarketplaceDailySnapshot(models.Model):
    """Daily platform-level KPI snapshot. Generated by Celery beat task."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(unique=True, db_index=True)

    # Volume
    total_bookings = models.IntegerField(default=0)
    confirmed_bookings = models.IntegerField(default=0)
    completed_bookings = models.IntegerField(default=0)
    cancelled_bookings = models.IntegerField(default=0)
    disputed_bookings = models.IntegerField(default=0)

    # Revenue
    gross_merchandise_value_lkr = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    platform_commission_lkr = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    provider_payouts_lkr = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    refunds_issued_lkr = models.DecimalField(max_digits=15, decimal_places=2, default=0)

    # Rates
    take_rate = models.DecimalField(max_digits=5, decimal_places=4, default=0,
                                     help_text="commission / GMV ratio")
    booking_conversion_rate = models.DecimalField(max_digits=5, decimal_places=4, default=0,
                                                    help_text="bookings / profile views")
    search_to_book_rate = models.DecimalField(max_digits=5, decimal_places=4, default=0,
                                               help_text="bookings / search events")
    cancellation_rate = models.DecimalField(max_digits=5, decimal_places=4, default=0)
    repeat_booking_rate = models.DecimalField(max_digits=5, decimal_places=4, default=0)
    average_order_value_lkr = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    # Users
    new_providers = models.IntegerField(default=0)
    new_buyers = models.IntegerField(default=0)
    active_providers = models.IntegerField(default=0)
    active_buyers = models.IntegerField(default=0)

    # Discovery
    total_searches = models.IntegerField(default=0)
    total_profile_views = models.IntegerField(default=0)

    # Assessments
    assessment_orders = models.IntegerField(default=0)
    assessment_gmv_lkr = models.DecimalField(max_digits=15, decimal_places=2, default=0)

    # Learning
    course_enrollments = models.IntegerField(default=0)
    course_gmv_lkr = models.DecimalField(max_digits=15, decimal_places=2, default=0)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "mp_marketplace_daily_snapshot"
        ordering = ["-date"]

    def __str__(self):
        return f"MarketplaceSnapshot {self.date} — GMV: {self.gross_merchandise_value_lkr}"


class ProviderDailySnapshot(models.Model):
    """Per-provider daily performance snapshot."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    provider = models.ForeignKey("providers.Provider", on_delete=models.CASCADE, related_name="daily_snapshots")
    date = models.DateField(db_index=True)
    profile_views = models.IntegerField(default=0)
    bookings_received = models.IntegerField(default=0)
    bookings_completed = models.IntegerField(default=0)
    bookings_cancelled = models.IntegerField(default=0)
    earnings_lkr = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    avg_rating = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    review_count = models.IntegerField(default=0)
    conversion_rate = models.DecimalField(max_digits=5, decimal_places=4, default=0,
                                           help_text="bookings / profile views")
    response_rate = models.DecimalField(max_digits=5, decimal_places=4, default=0)
    acceptance_rate = models.DecimalField(max_digits=5, decimal_places=4, default=0)

    class Meta:
        db_table = "mp_provider_daily_snapshot"
        ordering = ["-date"]
        unique_together = [["provider", "date"]]

    def __str__(self):
        return f"Provider {self.provider_id} snapshot {self.date}"


class SearchEvent(models.Model):
    """Anonymized log of search queries for demand forecasting and tuning."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session_id = models.CharField(max_length=100, db_index=True, help_text="Anonymous session token.")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        null=True, blank=True, related_name="search_events",
    )
    query = models.CharField(max_length=500, blank=True, default="")
    category = models.CharField(max_length=100, blank=True, default="")
    provider_type = models.CharField(max_length=50, blank=True, default="")
    location = models.CharField(max_length=100, blank=True, default="")
    price_min = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    price_max = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    result_count = models.IntegerField(default=0)
    clicked_provider_id = models.UUIDField(null=True, blank=True)
    resulted_in_booking = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = "mp_search_event"
        ordering = ["-timestamp"]

    def __str__(self):
        return f"Search '{self.query}' at {self.timestamp}"


class BookingFunnelEvent(models.Model):
    """Tracks each step in the booking funnel for conversion analysis."""

    class FunnelStep(models.TextChoices):
        SEARCH = "search", "Search Results Viewed"
        PROFILE_VIEW = "profile_view", "Provider Profile Viewed"
        SERVICE_VIEW = "service_view", "Service Detail Viewed"
        BOOKING_START = "booking_start", "Booking Started"
        BOOKING_INTAKE = "booking_intake", "Intake Form Completed"
        PAYMENT_INIT = "payment_init", "Payment Initiated"
        PAYMENT_COMPLETE = "payment_complete", "Payment Completed"
        BOOKING_CONFIRMED = "booking_confirmed", "Booking Confirmed"
        BOOKING_ABANDONED = "booking_abandoned", "Booking Abandoned"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session_id = models.CharField(max_length=100, db_index=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        null=True, blank=True, related_name="funnel_events",
    )
    step = models.CharField(max_length=25, choices=FunnelStep.choices)
    provider_id = models.UUIDField(null=True, blank=True)
    service_id = models.UUIDField(null=True, blank=True)
    booking_id = models.UUIDField(null=True, blank=True)
    metadata = models.JSONField(default=dict)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = "mp_booking_funnel_event"
        ordering = ["-timestamp"]

    def __str__(self):
        return f"FunnelEvent {self.step} — session {self.session_id}"


class ProviderViewEvent(models.Model):
    """Lightweight profile view tracking for provider analytics."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    provider = models.ForeignKey("providers.Provider", on_delete=models.CASCADE, related_name="view_events")
    viewer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        null=True, blank=True, related_name="provider_views",
    )
    session_id = models.CharField(max_length=100, blank=True, default="")
    source = models.CharField(
        max_length=30, blank=True, default="",
        help_text="e.g. search, recommendation, direct, featured",
    )
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = "mp_provider_view_event"
        ordering = ["-timestamp"]

    def __str__(self):
        return f"View of {self.provider_id} at {self.timestamp}"


class RevenueByCategory(models.Model):
    """Daily revenue breakdown by service category."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(db_index=True)
    category = models.CharField(max_length=100, db_index=True)
    booking_count = models.IntegerField(default=0)
    gmv_lkr = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    commission_lkr = models.DecimalField(max_digits=15, decimal_places=2, default=0)

    class Meta:
        db_table = "mp_revenue_by_category"
        ordering = ["-date"]
        unique_together = [["date", "category"]]

    def __str__(self):
        return f"{self.category} — {self.date} — GMV {self.gmv_lkr}"
