# Generated by Django 5.2.11 on 2026-03-08 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_scam_signal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_phishing_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='is_message_request',
            field=models.BooleanField(default=False, help_text='Thread is a message request (not yet accepted by recipient)'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='request_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VerifiedSenderBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('verified_recruiter', 'Verified Recruiter'), ('verified_employer', 'Verified Employer')], max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified_sender_badge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_verified_sender_badges',
            },
        ),
    ]
