# Generated by Django 5.2.11 on 2026-02-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='api_rate_limit_per_minute',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='career_page_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"logo": "url", "colors": {"primary": "#..."}, "banner": "url", "about_text": "...", "benefits": [...], "testimonials": [...]}'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='custom_fields_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"candidate": [{"name": "visa_status", "type": "select", "options": [...]}], "job": [{"name": "clearance_level", "type": "text"}]}'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='data_retention_policy_days',
            field=models.IntegerField(default=730, help_text='Auto-purge after N days'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='default_onboarding_tasks',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "...", "category": "it"}, ...]'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='notification_preferences_default',
            field=models.JSONField(blank=True, default=dict, help_text='{"new_applicant": true, "interview_scheduled": true, ...}'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='pii_masking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='require_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='session_timeout_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
