# Generated by Django 5.1 on 2026-03-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_max_candidates_tenant_max_jobs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
