# Generated by Django 5.2.11 on 2026-03-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_si', models.CharField(blank=True, default='', max_length=100)),
                ('name_ta', models.CharField(blank=True, default='', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_sl_specific', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'jf_education_levels',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_si', models.CharField(blank=True, default='', max_length=200)),
                ('name_ta', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('naics_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'db_table': 'jf_industries',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_si', models.CharField(blank=True, default='', max_length=200)),
                ('name_ta', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'jf_provinces',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_si', models.CharField(blank=True, default='', max_length=100)),
                ('name_ta', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('canonical_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('framework', 'Framework'), ('database', 'Database'), ('devops', 'DevOps'), ('design', 'Design'), ('soft_skill', 'Soft Skill'), ('language', 'Language'), ('trade', 'Trade'), ('certification', 'Certification'), ('other', 'Other')], default='other', max_length=50)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'jf_skills',
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_si', models.CharField(blank=True, default='', max_length=200)),
                ('name_ta', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, default='briefcase', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('job_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.jobcategory')),
            ],
            options={
                'verbose_name_plural': 'Job categories',
                'db_table': 'jf_job_categories',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='JobSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_si', models.CharField(blank=True, default='', max_length=200)),
                ('name_ta', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='taxonomy.jobcategory')),
            ],
            options={
                'verbose_name_plural': 'Job subcategories',
                'db_table': 'jf_job_subcategories',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_si', models.CharField(blank=True, default='', max_length=200)),
                ('name_ta', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='taxonomy.province')),
            ],
            options={
                'db_table': 'jf_districts',
                'ordering': ['name_en'],
            },
        ),
    ]
