# Generated by Django 5.2.11 on 2026-03-07 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0005_criticalrole_internalmobilityprofile'),
        ('helpdesk', '0001_initial'),
        ('tenants', '0003_billing_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(choices=[('web', 'Web Widget'), ('mobile', 'Mobile App'), ('slack', 'Slack'), ('teams', 'MS Teams')], default='web', max_length=30)),
                ('transcript', models.JSONField(default=list, help_text='[{"role":"user","text":"...","ts":"..."}]')),
                ('intent', models.CharField(blank=True, help_text="Classified intent, e.g. 'leave_balance', 'payslip', 'policy'", max_length=100)),
                ('resolved_by_bot', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_sessions', to='core_hr.employee')),
                ('escalated_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_intakes', to='helpdesk.ticket')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_intakes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'chatbot_intakes',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=100)),
                ('form_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema describing fields to collect for this service request')),
                ('fulfillment_sla_hours', models.IntegerField(default=24)),
                ('auto_fulfill', models.BooleanField(default=False, help_text='If true, system auto-fulfills without human intervention')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='helpdesk.ticketcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_catalog_items', to='tenants.tenant')),
            ],
            options={
                'db_table': 'service_catalog_items',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_data', models.JSONField(blank=True, default=dict, help_text="Data collected via the catalog item's form_schema")),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=30)),
                ('fulfillment_notes', models.TextField(blank=True)),
                ('due_by', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='helpdesk.servicecatalogitem')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='tenants.tenant')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request', to='helpdesk.ticket')),
            ],
            options={
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLADashboardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_response_breach_pct', models.IntegerField(default=80, help_text='Alert when response SLA breach % exceeds this threshold')),
                ('alert_resolution_breach_pct', models.IntegerField(default=80, help_text='Alert when resolution SLA breach % exceeds this threshold')),
                ('notify_users', models.JSONField(blank=True, default=list, help_text='List of user IDs to notify on SLA breach alerts')),
                ('escalation_policy', models.JSONField(blank=True, default=dict, help_text='{"levels":[{"after_hours":4,"notify":[]}]}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_dashboard_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sla_dashboard_configs',
            },
        ),
    ]
