# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_joblisting_application_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('keyword', 'Keyword'), ('regex', 'Regular Expression'), ('domain', 'Domain Pattern'), ('phrase', 'Phrase')], max_length=10)),
                ('pattern', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jf_scam_patterns',
                'ordering': ['-hit_count'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateJobGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_ids', models.JSONField(default=list, help_text='All duplicate job UUIDs in this group')),
                ('detection_method', models.CharField(default='title_similarity', max_length=30)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_group_as_canonical', to='jobs.joblisting')),
            ],
            options={
                'db_table': 'jf_duplicate_job_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreshnessSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('posted', 'Initial Post'), ('boosted', 'Manually Boosted'), ('reposted', 'Reposted'), ('edited', 'Job Edited'), ('expired', 'Expired'), ('renewed', 'Renewed')], max_length=10)),
                ('freshness_delta', models.FloatField(default=0.0, help_text='Score change from this signal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freshness_signals', to='jobs.joblisting')),
            ],
            options={
                'db_table': 'jf_freshness_signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0, help_text='0.0–100.0 overall quality')),
                ('freshness_score', models.FloatField(default=0.0, help_text='0.0–100.0 freshness (recency + activity)')),
                ('completeness_score', models.FloatField(default=0.0, help_text='0.0–100.0 field completeness')),
                ('trust_score', models.FloatField(default=0.0, help_text='0.0–100.0 employer trust contribution')),
                ('scam_risk', models.CharField(choices=[('none', 'No Risk'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('flagged', 'Flagged as Scam')], default='none', max_length=10)),
                ('scam_signals', models.JSONField(default=list, help_text='Detected scam signal descriptions')),
                ('has_salary', models.BooleanField(default=False)),
                ('has_requirements', models.BooleanField(default=False)),
                ('has_benefits', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('duplicate_group_id', models.UUIDField(blank=True, null=True)),
                ('last_scored_at', models.DateTimeField(auto_now=True)),
                ('score_version', models.CharField(default='v1', max_length=10)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score_obj', to='jobs.joblisting')),
            ],
            options={
                'db_table': 'jf_job_quality_scores',
            },
        ),
    ]
