# Generated by Django 5.2.11 on 2026-03-06 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=50)),
                ('metric_name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=100)),
                ('threshold', models.CharField(blank=True, default='>0.80', max_length=50)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warning', 'Warning'), ('fail', 'Fail')], default='pass', max_length=10)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jf_bias_metrics',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='Guardrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jf_guardrails',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIDecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=200)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=200)),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('inputs', models.TextField(blank=True, default='')),
                ('output', models.TextField(blank=True, default='')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewer', models.CharField(blank=True, default='', max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_ai_decision_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
