# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_alter_job_options'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('chain_type', models.CharField(choices=[('offer', 'Offer Approval'), ('headcount', 'Headcount Approval'), ('job_publish', 'Job Publish Approval'), ('general', 'General')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_chains', to='tenants.tenant')),
            ],
            options={
                'db_table': 'approval_chains',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('approver_role', models.CharField(blank=True, default='', help_text='Role-based fallback if approver is unset', max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('timeout_hours', models.IntegerField(default=48, help_text='Auto-escalate after this many hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='job_architecture.approvalchain')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='tenants.tenant')),
            ],
            options={
                'db_table': 'approval_steps',
                'ordering': ['chain', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_frameworks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'competency_frameworks',
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', help_text='e.g. Technical, Leadership, Soft', max_length=100)),
                ('required_for_levels', models.JSONField(blank=True, default=list, help_text='List of JobLevel UUIDs where this competency is required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='tenants.tenant')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='job_architecture.competencyframework')),
            ],
            options={
                'db_table': 'competencies',
                'ordering': ['framework', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeadcountPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fiscal_year', models.IntegerField()),
                ('quarter', models.IntegerField(blank=True, help_text='1–4; null = full year', null=True)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('total_headcount', models.IntegerField(default=0)),
                ('approved_headcount', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_headcount_plans', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headcount_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'headcount_plans',
                'ordering': ['-fiscal_year', 'department'],
            },
        ),
        migrations.CreateModel(
            name='JobDescriptionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, default='')),
                ('inclusive_language_score', models.FloatField(blank=True, help_text='0–100 inclusive language score', null=True)),
                ('jd_quality_score', models.FloatField(blank=True, help_text='0–100 overall quality score', null=True)),
                ('inclusive_language_flags', models.JSONField(blank=True, default=list, help_text="[{'term': 'ninja', 'suggestion': 'engineer', 'severity': 'medium'}]")),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jd_versions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_versions', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_versions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_description_versions',
                'ordering': ['job', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='JobFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='job_architecture.jobfamily')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_families', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_families',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('level_type', models.CharField(choices=[('ic', 'Individual Contributor'), ('manager', 'Manager'), ('director', 'Director'), ('vp', 'VP / Executive')], default='ic', max_length=20)),
                ('numeric_level', models.IntegerField(default=1, help_text='Numeric ordering within the family')),
                ('scope', models.TextField(blank=True, default='', help_text='What a person at this level owns/decides')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='job_architecture.jobfamily')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_levels', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_levels',
                'ordering': ['job_family', 'numeric_level'],
                'unique_together': {('tenant', 'job_family', 'numeric_level')},
            },
        ),
        migrations.CreateModel(
            name='HeadcountRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headcount_requisitions', to='jobs.job')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='job_architecture.headcountplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headcount_requisitions', to='tenants.tenant')),
                ('job_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='job_architecture.jobfamily')),
                ('job_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='job_architecture.joblevel')),
            ],
            options={
                'db_table': 'headcount_requisitions',
                'ordering': ['plan', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('pay_range_min', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pay_range_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pay_range_max', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('geo_zone', models.CharField(blank=True, default='', help_text='e.g. SF Bay Area, Remote-US, UK', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bands', to='job_architecture.jobfamily')),
                ('job_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bands', to='job_architecture.joblevel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bands', to='tenants.tenant')),
            ],
            options={
                'db_table': 'salary_bands',
                'ordering': ['job_family', 'job_level', 'geo_zone'],
            },
        ),
    ]
