# Generated by Django 5.2.11 on 2026-03-02 02:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_scimconfiguration_scimsynclog_ssoconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_url', models.URLField(max_length=500)),
                ('events', models.JSONField(default=list, help_text='List of event types to subscribe to')),
                ('secret', models.CharField(blank=True, help_text='HMAC-SHA256 signing secret for payload verification', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('retry_count', models.IntegerField(default=3, help_text='Number of delivery retries on failure')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_registrations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'integration_webhook_registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=1)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='integrations.webhookregistration')),
            ],
            options={
                'db_table': 'integration_webhook_delivery_logs',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector', models.CharField(choices=[('slack', 'Slack'), ('google_calendar', 'Google Calendar'), ('microsoft_365', 'Microsoft 365'), ('linkedin', 'LinkedIn'), ('xero', 'Xero'), ('quickbooks', 'QuickBooks'), ('ats', 'ATS System (Internal)'), ('custom_webhook', 'Custom Webhook')], max_length=50)),
                ('name', models.CharField(help_text='Display name, e.g. "Company Slack Workspace"', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending_auth', 'Pending Authorization')], default='inactive', max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Encrypted OAuth tokens or API keys')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Connector-specific config, e.g. channel_id, calendar_id')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['connector'],
                'unique_together': {('tenant', 'connector')},
            },
        ),
    ]
