# Generated by Django 5.2.11 on 2026-03-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='credentials',
        ),
        migrations.AddField(
            model_name='integration',
            name='_credentials_raw',
            field=models.JSONField(blank=True, db_column='credentials', default=dict, help_text='Fernet-encrypted OAuth tokens or API keys (see encryption.py)'),
        ),
    ]
