# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostOfLivingIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_value', models.FloatField(default=100.0, help_text='100 = national average')),
                ('housing_index', models.FloatField(default=100.0)),
                ('transport_index', models.FloatField(default=100.0)),
                ('food_index', models.FloatField(default=100.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_of_living', to='taxonomy.district')),
            ],
            options={
                'db_table': 'jf_cost_of_living_index',
            },
        ),
        migrations.CreateModel(
            name='SalaryBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('user_salary', models.IntegerField(help_text='Salary entered by user for comparison')),
                ('market_median', models.IntegerField(blank=True, null=True)),
                ('percentile_rank', models.FloatField(blank=True, help_text="User's salary percentile vs market", null=True)),
                ('below_market', models.BooleanField(default=False)),
                ('above_market', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.district')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_salary_benchmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalarySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_title', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, default='', max_length=10)),
                ('base_salary_lkr', models.IntegerField()),
                ('total_comp_lkr', models.IntegerField(blank=True, null=True)),
                ('has_bonus', models.BooleanField(default=False)),
                ('has_medical', models.BooleanField(default=False)),
                ('job_type', models.CharField(blank=True, default='', max_length=15)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('confidence_boost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.district')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employers.employeraccount')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_salary_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_title', models.CharField(help_text='Normalized/canonical job title', max_length=200)),
                ('experience_level', models.CharField(blank=True, default='', max_length=10)),
                ('salary_p10_lkr', models.IntegerField(blank=True, null=True)),
                ('salary_p25_lkr', models.IntegerField(blank=True, null=True)),
                ('salary_median_lkr', models.IntegerField(blank=True, null=True)),
                ('salary_p75_lkr', models.IntegerField(blank=True, null=True)),
                ('salary_p90_lkr', models.IntegerField(blank=True, null=True)),
                ('sample_size', models.IntegerField(default=0, help_text='Number of data points')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0–1.0 data confidence')),
                ('currency', models.CharField(default='LKR', max_length=5)),
                ('salary_period', models.CharField(default='monthly', max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.district')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.industry')),
            ],
            options={
                'db_table': 'jf_salary_estimates',
                'ordering': ['normalized_title', 'district'],
                'indexes': [models.Index(fields=['normalized_title', 'district'], name='idx_sal_title_dist')],
            },
        ),
        migrations.CreateModel(
            name='SalaryTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_title', models.CharField(max_length=200)),
                ('month', models.DateField(help_text='First day of the month')),
                ('median_salary_lkr', models.IntegerField(blank=True, null=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.district')),
            ],
            options={
                'db_table': 'jf_salary_trends',
                'ordering': ['normalized_title', '-month'],
                'unique_together': {('normalized_title', 'district', 'month')},
            },
        ),
    ]
