# Generated by Django 5.2.11 on 2026-03-06 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('credential_type', models.CharField(choices=[('certificate', 'Certificate'), ('license', 'License'), ('badge', 'Digital Badge'), ('assessment', 'Assessment Result'), ('portfolio', 'Portfolio Item'), ('endorsement', 'Endorsement'), ('degree', 'Degree')], max_length=20)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Verification'), ('expired', 'Expired'), ('unverified', 'Unverified'), ('revoked', 'Revoked')], default='unverified', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('import', 'Imported'), ('open_badge', 'Open Badge (1EdTech)'), ('linkedin', 'LinkedIn Import'), ('platform', 'Platform Issued')], default='manual', max_length=20)),
                ('issuer_name', models.CharField(max_length=300)),
                ('issuer_url', models.URLField(blank=True)),
                ('issuer_logo_url', models.URLField(blank=True)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True, help_text='URL to verify the credential')),
                ('credential_id', models.CharField(blank=True, help_text='External credential ID for verification', max_length=300)),
                ('badge_json', models.JSONField(blank=True, default=dict, help_text='Open Badge 2.0/3.0 assertion JSON')),
                ('evidence_url', models.URLField(blank=True)),
                ('evidence_file', models.FileField(blank=True, upload_to='credentials/')),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Show on public profile')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_skills', models.JSONField(blank=True, default=list, help_text='Skills validated by this credential')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cx_credential',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='CredentialShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='credentials.credential')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_credential_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cx_credential_share',
                'ordering': ['-shared_at'],
            },
        ),
    ]
