# Generated by Django 5.2.11 on 2026-03-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='linked_skills',
            field=models.JSONField(blank=True, default=list, help_text='Skill IDs validated by this credential (JSON list)'),
        ),
    ]
