# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0005_offer_esign_document_url_offer_esign_envelope_id_and_more'),
        ('candidates', '0008_candidatefollowuptask_candidateoutreachlog_and_more'),
        ('jobs', '0005_job_degree_optional_note_job_degree_required_and_more'),
        ('tenants', '0004_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('needs', models.JSONField(blank=True, default=list, help_text='["screen_reader", "captions", "extra_time", "sign_language"]')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_preference', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_prefs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accessibility_preferences',
            },
        ),
        migrations.CreateModel(
            name='CandidateFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.IntegerField(help_text='1-5 stars')),
                ('comments', models.TextField(blank=True, default='')),
                ('would_apply_again', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'candidate_feedback',
            },
        ),
        migrations.CreateModel(
            name='PortalToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('purpose', models.CharField(help_text='status_check, document_upload, self_schedule, offer_review, feedback', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'portal_tokens',
            },
        ),
        migrations.CreateModel(
            name='CandidateNPS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('applied', 'After Applying'), ('interviewed', 'After Interview'), ('offer_received', 'After Offer'), ('rejected', 'After Rejection'), ('hired', 'After Joining')], max_length=20)),
                ('score', models.IntegerField(help_text='0-10 NPS score')),
                ('comment', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nps_responses', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_responses', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_nps', to='tenants.tenant')),
            ],
            options={
                'db_table': 'candidate_nps',
                'ordering': ['-responded_at'],
                'indexes': [models.Index(fields=['tenant', 'event'], name='candidate_n_tenant__754990_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='["Python", "Backend"]')),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_alerts',
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='job_alerts_tenant__a9a074_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedApplicationDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, default='', help_text='Anonymous session key for unauthenticated users', max_length=100)),
                ('draft_data', models.JSONField(blank=True, default=dict)),
                ('resume_file_url', models.CharField(blank=True, default='', max_length=500)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_drafts', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_drafts', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_applications', to='tenants.tenant')),
            ],
            options={
                'db_table': 'saved_application_drafts',
                'ordering': ['-last_saved_at'],
                'indexes': [models.Index(fields=['tenant', 'job'], name='saved_appli_tenant__b12c50_idx'), models.Index(fields=['session_key'], name='saved_appli_session_1908c2_idx')],
            },
        ),
    ]
