# Generated by Django 5.2.11 on 2026-02-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company_admin', 'Company Admin'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('candidate', 'Candidate')], default='candidate', max_length=20),
        ),
    ]
