# Generated by Django 5.2.11 on 2026-02-25 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(db_index=True, max_length=50)),
                ('value', models.FloatField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('computed_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='tenants.tenant')),
            ],
            options={
                'db_table': 'analytics_daily',
                'indexes': [models.Index(fields=['tenant', 'computed_date'], name='analytics_d_tenant__3d59be_idx'), models.Index(fields=['tenant', 'metric', 'computed_date'], name='analytics_d_tenant__6185bf_idx')],
                'unique_together': {('tenant', 'job', 'metric', 'computed_date')},
            },
        ),
    ]
