# Generated by Django 5.2.11 on 2026-02-27 04:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenants', '0002_tenantsettings_api_rate_limit_per_minute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(help_text='pipeline_funnel, source_roi, recruiter_performance, time_to_hire, diversity, custom', max_length=50)),
                ('query_config', models.JSONField(blank=True, default=dict, help_text='{"fields": [...], "filters": {...}, "group_by": "...", "date_range": "..."}')),
                ('schedule', models.CharField(choices=[('none', 'No Schedule'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('recipients', models.JSONField(blank=True, default=list, help_text='["user_id_1", "user_id_2"] or ["email@example.com"]')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'saved_reports',
            },
        ),
    ]
