# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=30, unique=True)),
                ('case_type', models.CharField(choices=[('disciplinary', 'Disciplinary'), ('performance_concern', 'Performance Concern'), ('harassment', 'Harassment'), ('discrimination', 'Discrimination'), ('policy_violation', 'Policy Violation'), ('ethics', 'Ethics / Whistleblower'), ('grievance', 'Grievance'), ('conflict', 'Workplace Conflict'), ('accommodation', 'Accommodation Request'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('critical', 'Critical')], default='moderate', max_length=10)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('intake', 'Intake'), ('assigned', 'Assigned'), ('investigation', 'Under Investigation'), ('hearing', 'Hearing Scheduled'), ('pending_outcome', 'Pending Outcome'), ('outcome_issued', 'Outcome Issued'), ('appeal', 'Under Appeal'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], default='intake', max_length=25)),
                ('sla_response_due', models.DateTimeField(blank=True, null=True)),
                ('sla_resolution_due', models.DateTimeField(blank=True, null=True)),
                ('response_given_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_summary', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('tags', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_er_cases', to=settings.AUTH_USER_MODEL)),
                ('complainant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='er_cases_as_complainant', to='core_hr.employee')),
                ('investigating_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigating_er_cases', to=settings.AUTH_USER_MODEL)),
                ('subject_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='er_cases_as_subject', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='er_cases', to='tenants.tenant')),
            ],
            options={
                'db_table': 'er_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('verbal_warning', 'Verbal Warning'), ('written_warning', 'Written Warning'), ('final_warning', 'Final Written Warning'), ('suspension', 'Suspension'), ('demotion', 'Demotion'), ('termination_cause', 'Termination for Cause'), ('no_action', 'No Action Taken'), ('coaching_required', 'Coaching Required')], max_length=25)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Date warning expires from record', null=True)),
                ('suspension_days', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('conditions', models.TextField(blank=True, help_text='Conditions attached to the action')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('acknowledged', 'Employee Acknowledged'), ('appealed', 'Appealed'), ('overturned', 'Overturned'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('appeal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='core_hr.employee')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='tenants.tenant')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='employee_relations.ercase')),
            ],
            options={
                'db_table': 'disciplinary_actions',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ERCaseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('update', 'Status Update'), ('interview', 'Interview Note'), ('evidence', 'Evidence Note'), ('decision', 'Decision Note'), ('communication', 'Communication Log'), ('legal', 'Legal Note'), ('internal', 'Internal Note')], default='update', max_length=20)),
                ('content', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('is_confidential', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='employee_relations.ercase')),
            ],
            options={
                'db_table': 'er_case_notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EthicsIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(help_text='Short code given to reporter to track status anonymously', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('fraud', 'Fraud'), ('bribery', 'Bribery'), ('harassment', 'Harassment'), ('safety', 'Safety Violation'), ('data_privacy', 'Data Privacy'), ('conflict_interest', 'Conflict of Interest'), ('other', 'Other')], max_length=50)),
                ('subject', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('attachments', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('received', 'Received'), ('triaged', 'Triaged'), ('investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='received', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_er_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ethics_intakes', to='employee_relations.ercase')),
                ('reporter_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ethics_reports', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethics_intakes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ethics_intakes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PImprovementPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('performance_concerns', models.TextField()),
                ('objectives', models.JSONField(default=list, help_text='[{"goal":"...","metric":"...","target":"...","deadline":"2024-03-01"}]')),
                ('support_provided', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('review_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed_success', 'Completed — Successful'), ('completed_failure', 'Completed — Not Met'), ('withdrawn', 'Withdrawn')], default='draft', max_length=25)),
                ('outcome_notes', models.TextField(blank=True)),
                ('check_in_notes', models.JSONField(default=list, help_text='[{"date":"2024-02-01","notes":"Progress noted","by":"manager_uuid"}]')),
                ('employee_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pips', to='core_hr.employee')),
                ('hr_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_pips', to='core_hr.employee')),
                ('related_er_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pips', to='employee_relations.ercase')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pips', to='tenants.tenant')),
            ],
            options={
                'db_table': 'performance_improvement_plans',
                'ordering': ['-start_date'],
            },
        ),
    ]
