# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('job_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('ownership_status', models.CharField(choices=[('owned', 'Owned'), ('expired', 'Ownership Expired'), ('disputed', 'Disputed'), ('released', 'Released')], default='owned', max_length=20)),
                ('ownership_expiry', models.DateTimeField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('work_auth_status', models.CharField(choices=[('citizen', 'Citizen'), ('pr', 'Permanent Resident'), ('work_visa', 'Work Visa'), ('needs_sponsorship', 'Needs Sponsorship'), ('not_authorized', 'Not Authorized'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('work_auth_country', models.CharField(blank=True, max_length=100)),
                ('contract_preference', models.CharField(choices=[('contract_only', 'Contract Only'), ('perm_only', 'Permanent Only'), ('both', 'Both Contract & Perm'), ('temp', 'Temp / Ad-hoc')], default='both', max_length=20)),
                ('desired_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('desired_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('desired_rate_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('location_preferences', models.JSONField(default=list)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('willing_to_travel', models.BooleanField(default=False)),
                ('skills', models.JSONField(default=list)),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('do_not_submit', models.BooleanField(default=False)),
                ('do_not_rehire', models.BooleanField(default=False)),
                ('do_not_submit_reason', models.TextField(blank=True)),
                ('accepts_email', models.BooleanField(default=True)),
                ('accepts_sms', models.BooleanField(default=False)),
                ('accepts_whatsapp', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('source_detail', models.CharField(blank=True, max_length=200)),
                ('is_redeployable', models.BooleanField(default=False)),
                ('is_boomerang', models.BooleanField(default=False)),
                ('is_silver_medalist', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('recruiter_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='agencies.agency')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='submissions.candidateprofile')),
                ('owning_recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_candidates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_candidate_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sub_candidate_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Client'), ('under_review', 'Under Client Review'), ('shortlisted', 'Shortlisted'), ('interview_requested', 'Interview Requested'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offer', 'Offer Made'), ('placed', 'Placed'), ('rejected', 'Rejected by Client'), ('withdrawn', 'Withdrawn by Candidate'), ('on_hold', 'On Hold')], default='draft', max_length=30)),
                ('recruiter_pitch', models.TextField(blank=True)),
                ('tailored_resume_url', models.URLField(blank=True)),
                ('cover_note', models.TextField(blank=True)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('rank_in_shortlist', models.IntegerField(blank=True, null=True)),
                ('ownership_verified', models.BooleanField(default=False)),
                ('right_to_represent_captured', models.BooleanField(default=False)),
                ('right_to_represent_date', models.DateTimeField(blank=True, null=True)),
                ('duplicate_check_passed', models.BooleanField(default=True)),
                ('client_notes', models.TextField(blank=True)),
                ('client_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_client_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='am_submissions', to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='agencies.agency')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.candidateprofile')),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='job_orders.joborder')),
                ('legacy_submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_submission', to='agencies.agencysubmission')),
                ('sent_to_client_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sub_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('reviewed', 'Client Reviewed'), ('revision_requested', 'Revision Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('intro_message', models.TextField(blank=True)),
                ('deck_url', models.URLField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('revision_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='agencies.agency')),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortlists', to='job_orders.joborder')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_shortlists', to=settings.AUTH_USER_MODEL)),
                ('submissions', models.ManyToManyField(blank=True, related_name='shortlists', to='submissions.submission')),
            ],
            options={
                'db_table': 'sub_shortlist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SendToClientLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('method', models.CharField(choices=[('email', 'Email'), ('portal', 'Client Portal'), ('api', 'API')], default='email', max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='agencies.agency')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to=settings.AUTH_USER_MODEL)),
                ('shortlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='submissions.shortlist')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='submissions.submission')),
            ],
            options={
                'db_table': 'sub_send_to_client_log',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_status_changes', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='submissions.submission')),
            ],
            options={
                'db_table': 'sub_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
