# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('reactivation', 'Inactivity Reactivation'), ('weekly_digest', 'Weekly Job Digest'), ('missed_opportunity', 'Missed Opportunity Alert'), ('new_since_visit', 'New Since Last Visit'), ('profile_incomplete', 'Complete Your Profile'), ('saved_expiring', 'Saved Job Expiring Soon')], max_length=25)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('subject_template', models.CharField(blank=True, default='', max_length=300)),
                ('body_template', models.TextField(blank=True, default='')),
                ('inactivity_threshold_days', models.IntegerField(default=7, help_text='Days of inactivity to trigger (for reactivation)')),
                ('audience_filter', models.JSONField(default=dict, help_text='JSON filter criteria for targeted audience')),
                ('target_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('reactivation_count', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jf_retention_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigestQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_ids', models.JSONField(default=list, help_text='Ordered list of job UUIDs for digest')),
                ('digest_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_job_id', models.UUIDField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_digest_queues',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='InactivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_search_at', models.DateTimeField(blank=True, null=True)),
                ('last_application_at', models.DateTimeField(blank=True, null=True)),
                ('last_job_save_at', models.DateTimeField(blank=True, null=True)),
                ('inactivity_days', models.IntegerField(default=0)),
                ('reactivation_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reactivation_count', models.IntegerField(default=0)),
                ('is_inactive', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_inactivity_records',
            },
        ),
    ]
