# Generated by Django 5.2.11 on 2026-02-27 04:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('tenants', '0002_tenantsettings_api_rate_limit_per_minute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('employment_type', models.CharField(default='full_time', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('optional_skills', models.JSONField(blank=True, default=list)),
                ('target_titles', models.JSONField(blank=True, default=list)),
                ('screening_questions', models.JSONField(blank=True, default=list)),
                ('pipeline_stages', models.JSONField(blank=True, default=list, help_text='[{"name": "Applied", "stage_type": "applied", "order": 1}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_templates',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='headcount_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='headcount_target',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='internal_only',
            field=models.BooleanField(default=False, help_text='Only visible to current employees'),
        ),
        migrations.AddField(
            model_name='job',
            name='locations',
            field=models.JSONField(blank=True, default=list, help_text='Multi-location support'),
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='requisition_id',
            field=models.CharField(blank=True, default='', help_text='External HRIS job code', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='template_source',
            field=models.ForeignKey(blank=True, help_text='Job template this was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='notes_template',
            field=models.TextField(blank=True, default='', help_text='Pre-filled notes template when entering this stage'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='sla_days',
            field=models.IntegerField(blank=True, help_text='Max days in this stage', null=True),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='stage_checklist',
            field=models.JSONField(blank=True, default=list, help_text='["Resume reviewed", "Phone screen done", "References checked"]'),
        ),
        migrations.AlterField(
            model_name='job',
            name='screening_questions',
            field=models.JSONField(blank=True, default=list, help_text='[{"question": "...", "type": "boolean|text", "knockout": true, "knockout_value": false, "score_weight": 1}]'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant', 'priority'], name='jobs_tenant__be5011_idx'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_templates', to='tenants.tenant'),
        ),
    ]
