# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_architecture', '__first__'),
        ('jobs', '0004_alter_job_options'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='degree_optional_note',
            field=models.TextField(blank=True, default='', help_text="Message shown to candidates: 'Degree not required — skills matter'"),
        ),
        migrations.AddField(
            model_name='job',
            name='degree_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='headcount_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job_architecture.headcountplan'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job_architecture.jobfamily'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job_architecture.joblevel'),
        ),
        migrations.AddField(
            model_name='job',
            name='pay_frequency',
            field=models.CharField(choices=[('annual', 'Annual'), ('monthly', 'Monthly'), ('hourly', 'Hourly')], default='annual', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_disclosed',
            field=models.BooleanField(default=False, help_text='Show salary band on public posting'),
        ),
        migrations.CreateModel(
            name='JobIntakeMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('agreed_requirements', models.JSONField(blank=True, default=dict, help_text='{"must_have": [...], "nice_to_have": [...], "deal_breakers": [...]}')),
                ('interview_process', models.JSONField(blank=True, default=list, help_text='[{"round": 1, "type": "phone", "interviewer": "...", "duration_mins": 30}]')),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_meetings_as_hm', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_meetings', to='jobs.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_meetings_as_recruiter', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_intake_meetings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_intake_meetings',
                'ordering': ['-meeting_date'],
            },
        ),
    ]
