# Generated by Django 5.2.11 on 2026-02-28 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_scimconfiguration_scimsynclog_ssoconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('onboarding', 'Onboarding'), ('leave', 'Leave Management'), ('attendance', 'Attendance'), ('payroll', 'Payroll'), ('birthday', 'Birthday/Anniversary'), ('compliance', 'Compliance'), ('helpdesk', 'Helpdesk'), ('other', 'Other')], max_length=30)),
                ('icon', models.CharField(default='⚡', max_length=10)),
                ('template_data', models.JSONField(help_text='Serialized workflow definition + nodes')),
                ('install_count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=True, help_text='System-provided vs community')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_templates',
                'ordering': ['-is_featured', '-install_count'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_event', models.CharField(help_text='e.g. employee.created, leave.approved, payroll.finalized', max_length=100)),
                ('trigger_conditions', models.JSONField(blank=True, default=list, help_text='[{"field":"department.name","operator":"equals","value":"Engineering"}]')),
                ('actions', models.JSONField(default=list, help_text='[{"type":"send_notification","config":{"template":"welcome","to":"employee"}}, {"type":"create_task","config":{"title":"...","assignee_role":"hr_admin","due_offset_days":7}}, {"type":"update_field","config":{"model":"employee","field":"status","value":"active"}}, {"type":"call_webhook","config":{"url":"...","method":"POST"}}, {"type":"create_approval","config":{"approver_role":"manager"}}]')),
                ('is_active', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False, help_text='Pre-built workflow from template marketplace')),
                ('run_count', models.IntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='tenants.tenant')),
            ],
            options={
                'db_table': 'workflow_definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_event', models.CharField(max_length=100)),
                ('trigger_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('actions_executed', models.JSONField(default=list, help_text='[{"action":"send_notification","status":"success","timestamp":"..."}]')),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to='tenants.tenant')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('trigger', 'Trigger'), ('condition', 'Condition'), ('action', 'Action'), ('branch', 'Branch (Parallel)'), ('merge', 'Merge'), ('loop', 'Loop'), ('delay', 'Delay'), ('end', 'End')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('config', models.JSONField(default=dict, help_text='\n        For action: {"action_type":"send_email","template":"welcome","to":"employee.email"}\n        For condition: {"field":"employee.department","operator":"equals","value":"Engineering"}\n        For branch: {"paths":[{"name":"Path A","next":"node-uuid"},{"name":"Path B","next":"node-uuid"}]}\n        For delay: {"duration_minutes":60}\n        For loop: {"max_iterations":5,"condition":{"field":"status","operator":"not_equals","value":"complete"}}\n    ')),
                ('position_x', models.IntegerField(default=0, help_text='X position in visual builder')),
                ('position_y', models.IntegerField(default=0, help_text='Y position in visual builder')),
                ('next_nodes', models.JSONField(default=list, help_text='List of next node UUIDs')),
                ('sort_order', models.IntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_nodes',
                'ordering': ['sort_order'],
            },
        ),
    ]
