# Generated by Django 5.2.11 on 2026-02-25 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('trigger_type', models.CharField(choices=[('application_created', 'Application Created'), ('stage_changed', 'Stage Changed'), ('application_idle', 'Application Idle'), ('application_rejected', 'Application Rejected'), ('offer_accepted', 'Offer Accepted'), ('retention_expired', 'Retention Expired')], max_length=50)),
                ('conditions_json', models.JSONField(blank=True, default=dict, help_text='e.g. {"to_stage_type": "interview"}')),
                ('actions_json', models.JSONField(default=list, help_text='[{"type": "send_email", "template_id": "..."}, ...]')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'automation_rules',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'idempotency_keys',
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('action_type', models.CharField(max_length=50)),
                ('action_target', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.automationrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'workflow_executions',
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['tenant', 'trigger_type', 'enabled'], name='automation__tenant__1eebf2_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['tenant', 'key'], name='idempotency_tenant__0311d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='idempotencykey',
            unique_together={('tenant', 'key')},
        ),
    ]
