# Generated by Django 5.2.11 on 2026-02-27 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantsettings_api_rate_limit_per_minute_and_more'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrule',
            options={'ordering': ['priority_order']},
        ),
        migrations.AddField(
            model_name='automationrule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Pre-built workflow recipe'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='priority_order',
            field=models.IntegerField(default=0, help_text='Lower = higher priority'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='execute_at',
            field=models.DateTimeField(blank=True, help_text='For delayed executions', null=True),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='conditions_json',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"to_stage_type": "interview", "score_min": 80}'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('application_created', 'Application Created'), ('stage_changed', 'Stage Changed'), ('application_idle', 'Application Idle'), ('application_rejected', 'Application Rejected'), ('offer_accepted', 'Offer Accepted'), ('offer_expiring', 'Offer Expiring'), ('retention_expired', 'Retention Expired'), ('score_threshold', 'Score Threshold Met'), ('interview_completed', 'Interview Completed'), ('feedback_overdue', 'Feedback Overdue'), ('candidate_updated', 'Candidate Profile Updated'), ('new_job_match', 'New Job Matches Talent Pool'), ('probation_milestone', 'Probation Milestone'), ('application_deadline', 'Application Deadline Approaching')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('pending', 'Pending'), ('delayed', 'Delayed')], default='success', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('move_stage', 'Move Stage'), ('assign_tag', 'Assign Tag'), ('notify_user', 'Notify User'), ('set_priority', 'Set Priority'), ('assign_recruiter', 'Assign Recruiter'), ('create_task', 'Create Task'), ('wait', 'Wait/Delay'), ('condition', 'Conditional Branch'), ('auto_reject', 'Auto Reject'), ('escalate', 'Escalate')], max_length=50)),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='{"template_id": "...", "stage_id": "...", "delay_hours": 48}')),
                ('delay_hours', models.FloatField(default=0, help_text='Hours to wait before executing this step')),
                ('condition_json', models.JSONField(blank=True, default=dict, help_text='{"if_score_above": 80, "else_goto_step": 3}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.automationrule')),
            ],
            options={
                'db_table': 'workflow_steps',
                'ordering': ['rule', 'order'],
            },
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='workflows.workflowstep'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['tenant', 'execute_at'], name='workflow_ex_tenant__9d0038_idx'),
        ),
    ]
