# Generated by Django 5.2.11 on 2026-03-03 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_max_candidates_tenant_max_jobs_and_more'),
        ('workflows', '0003_workflow_execution_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(blank=True, help_text='HMAC signing secret', max_length=200)),
                ('events', models.JSONField(default=list, help_text='List of event types to subscribe to, e.g. ["candidate.created"]')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Webhook Subscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
