# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_delete_subscription'),
        ('workflows', '0004_webhooksubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChainInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('offer', 'Offer'), ('job', 'Job'), ('headcount_plan', 'Headcount Plan'), ('compensation', 'Compensation Change')], max_length=30)),
                ('object_id', models.UUIDField(db_index=True, help_text='PK of the object being approved')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_step', models.IntegerField(default=1)),
                ('total_steps', models.IntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_approvals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain_instances', to='tenants.tenant')),
            ],
            options={
                'db_table': 'approval_chain_instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('role_label', models.CharField(blank=True, default='', help_text="e.g. 'Finance Director', 'VP Engineering'", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_step_instances', to=settings.AUTH_USER_MODEL)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.approvalchaininstance')),
            ],
            options={
                'db_table': 'approval_step_instances',
                'ordering': ['chain', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='SLAEscalationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('stage_sla_breach', 'Stage SLA Breach'), ('approval_overdue', 'Approval Overdue'), ('feedback_overdue', 'Feedback Overdue'), ('offer_expiring', 'Offer Expiring')], max_length=30)),
                ('threshold_hours', models.IntegerField(help_text='Hours after SLA deadline before escalation fires')),
                ('escalation_action', models.CharField(choices=[('notify_manager', 'Notify Manager'), ('notify_recruiter', 'Notify Recruiter'), ('auto_reassign', 'Auto-Reassign'), ('slack_alert', 'Slack Alert'), ('email_chain', 'Email Escalation Chain')], max_length=30)),
                ('escalation_config', models.JSONField(blank=True, default=dict, help_text='{"notify_user_ids": [...], "slack_channel": "..."}')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_escalation_rules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sla_escalation_rules',
                'ordering': ['threshold_hours'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalchaininstance',
            index=models.Index(fields=['tenant', 'object_type', 'object_id'], name='approval_ch_tenant__b4caf8_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalchaininstance',
            index=models.Index(fields=['tenant', 'status'], name='approval_ch_tenant__0da254_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstepinstance',
            unique_together={('chain', 'step_number')},
        ),
    ]
