# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        ('jobs', '0002_joblisting_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProofRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Documents Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('documents_submitted', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employers.employeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_proofs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_identity_proof_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhishingMessageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_thread_id', models.UUIDField(blank=True, null=True)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('suspicious_url', models.URLField(blank=True, default='', max_length=500)),
                ('description', models.TextField()),
                ('screenshot_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('actioned', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phishing_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phishing_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_phishing_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScamAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_level', models.CharField(choices=[('warning', 'Warning'), ('high_risk', 'High Risk'), ('confirmed_scam', 'Confirmed Scam')], default='warning', max_length=15)),
                ('alert_message', models.TextField()),
                ('is_public', models.BooleanField(default=False, help_text='Show warning to seekers')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scam_alerts', to='employers.employeraccount')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scam_alerts', to='jobs.joblisting')),
            ],
            options={
                'db_table': 'jf_scam_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrikeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('fake_job', 'Fake Job Posting'), ('scam', 'Scam Behavior'), ('harassment', 'User Harassment'), ('payment_request', 'Illegal Payment Request'), ('misleading', 'Misleading Job Info'), ('duplicate', 'Excessive Duplicate Postings'), ('policy', 'General Policy Violation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('related_job_id', models.UUIDField(blank=True, null=True)),
                ('related_report_id', models.UUIDField(blank=True, null=True)),
                ('strike_number', models.IntegerField(default=1, help_text='1st, 2nd, 3rd strike')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strikes_issued', to=settings.AUTH_USER_MODEL)),
                ('target_employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strikes', to='employers.employeraccount')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_strike_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspensionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suspension_type', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent'), ('under_review', 'Under Review')], default='temporary', max_length=15)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_lifted', to=settings.AUTH_USER_MODEL)),
                ('suspended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_issued', to=settings.AUTH_USER_MODEL)),
                ('target_employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions', to='employers.employeraccount')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_suspension_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
