# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0005_job_degree_optional_note_job_degree_required_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalPostingWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('is_exclusive', models.BooleanField(default=True, help_text='If True, external candidates cannot apply until window closes')),
                ('notify_employees', models.BooleanField(default=True)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_posting_window', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_posting_windows', to='tenants.tenant')),
            ],
            options={
                'db_table': 'internal_posting_windows',
            },
        ),
        migrations.CreateModel(
            name='InternalRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('on_hold', 'On Hold'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_fill_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hiring_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_requisitions_managed', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_requisitions', to='jobs.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_requisitions_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_requisitions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'internal_requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_role', models.CharField(blank=True, default='', max_length=255)),
                ('current_department', models.CharField(blank=True, default='', max_length=150)),
                ('cover_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('current_manager_notified', models.BooleanField(default=False)),
                ('current_manager_approval', models.BooleanField(blank=True, help_text='None=pending, True=approved, False=denied', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_applications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_applications', to='tenants.tenant')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internal_recruiting.internalrequisition')),
            ],
            options={
                'db_table': 'internal_applications',
                'ordering': ['-applied_at'],
                'unique_together': {('requisition', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='InternalTransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_type', models.CharField(choices=[('lateral', 'Lateral Transfer'), ('promotion', 'Promotion'), ('demotion', 'Demotion'), ('rotation', 'Job Rotation')], default='lateral', max_length=20)),
                ('from_role', models.CharField(max_length=255)),
                ('from_department', models.CharField(blank=True, default='', max_length=150)),
                ('to_role', models.CharField(max_length=255)),
                ('to_department', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_start_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_initiated', to=settings.AUTH_USER_MODEL)),
                ('target_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'internal_transfer_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalVsExternalComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_applicants', models.IntegerField(default=0)),
                ('external_applicants', models.IntegerField(default=0)),
                ('internal_shortlisted', models.IntegerField(default=0)),
                ('external_shortlisted', models.IntegerField(default=0)),
                ('internal_hired', models.IntegerField(default=0)),
                ('external_hired', models.IntegerField(default=0)),
                ('avg_internal_score', models.FloatField(blank=True, null=True)),
                ('avg_external_score', models.FloatField(blank=True, null=True)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_vs_external_comparisons', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_vs_external_comparisons', to='tenants.tenant')),
            ],
            options={
                'db_table': 'internal_vs_external_comparisons',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagerApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('conditionally_approved', 'Conditionally Approved')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approvals', to='internal_recruiting.internalapplication')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_manager_approvals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_approvals', to='tenants.tenant')),
                ('transfer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approvals', to='internal_recruiting.internaltransferrequest')),
            ],
            options={
                'db_table': 'manager_approvals',
                'ordering': ['-created_at'],
            },
        ),
    ]
