# Generated by Django 5.2.11 on 2026-03-06 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('seekers', 'For Seekers'), ('employers', 'For Employers'), ('account', 'Account'), ('payments', 'Payments'), ('general', 'General')], max_length=30)),
                ('question', models.TextField()),
                ('question_si', models.TextField(blank=True, default='')),
                ('question_ta', models.TextField(blank=True, default='')),
                ('answer', models.TextField()),
                ('answer_si', models.TextField(blank=True, default='')),
                ('answer_ta', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jf_faqs',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_si', models.CharField(blank=True, default='', max_length=200)),
                ('title_ta', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('body_si', models.TextField(blank=True, default='')),
                ('body_ta', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jf_static_pages',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_si', models.CharField(blank=True, default='', max_length=200)),
                ('title_ta', models.CharField(blank=True, default='', max_length=200)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('excerpt_si', models.TextField(blank=True, default='')),
                ('excerpt_ta', models.TextField(blank=True, default='')),
                ('body', models.TextField()),
                ('body_si', models.TextField(blank=True, default='')),
                ('body_ta', models.TextField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog_covers/')),
                ('category', models.CharField(choices=[('career_advice', 'Career Advice'), ('interview_tips', 'Interview Tips'), ('salary_guide', 'Salary Guide'), ('industry_news', 'Industry News'), ('resume_guide', 'Resume Guide'), ('foreign_employment', 'Foreign Employment')], max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, default='', max_length=70)),
                ('meta_description', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_blog_posts',
                'ordering': ['-published_at'],
            },
        ),
    ]
