# Generated by Django 5.2.11 on 2026-03-06 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jf_webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_mode', models.CharField(choices=[('full', 'Full ATS Sync'), ('webhook', 'Basic Webhook'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('api_endpoint', models.URLField(blank=True, default='', max_length=500)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('webhook_secret_encrypted', models.TextField(blank=True, default='')),
                ('webhook_url', models.URLField(blank=True, default='', max_length=500)),
                ('sync_jobs', models.BooleanField(default=True)),
                ('sync_applications', models.BooleanField(default=True)),
                ('sync_candidates', models.BooleanField(default=False)),
                ('sync_interval_minutes', models.IntegerField(default=30)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_connection', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_ats_connections',
            },
        ),
        migrations.CreateModel(
            name='JobSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_job_id', models.CharField(max_length=100)),
                ('ats_job_data', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('sync_errors', models.JSONField(default=list)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='ats_connector.atsconnection')),
            ],
            options={
                'db_table': 'jf_job_sync_records',
            },
        ),
    ]
