# Generated by Django 5.2.11 on 2026-03-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ats_connector', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsyncrecord',
            name='local_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='jobs.joblisting'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='ats_connector.atsconnection'),
        ),
        migrations.AlterUniqueTogether(
            name='jobsyncrecord',
            unique_together={('connection', 'ats_job_id')},
        ),
    ]
