# Generated by Django 5.2.11 on 2026-02-27 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Subdomain identifier', max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='active', max_length=20)),
                ('settings_json', models.JSONField(blank=True, default=dict, help_text='Branding, defaults, feature flags')),
                ('hrm_settings', models.JSONField(blank=True, default=dict, help_text='HRM-specific config: active modules, defaults')),
                ('max_employees', models.IntegerField(default=10, help_text='Employee limit based on plan')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_key', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('rollout_pct', models.IntegerField(default=100, help_text='Percentage for gradual rollout')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = global flag', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='tenants.tenant')),
            ],
            options={
                'db_table': 'feature_flags',
                'unique_together': {('tenant', 'flag_key')},
            },
        ),
        migrations.CreateModel(
            name='TenantFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('core_hr', 'Core HR'), ('onboarding', 'Onboarding & Offboarding'), ('leave_attendance', 'Leave & Attendance'), ('payroll', 'Payroll'), ('performance', 'Performance & Goals'), ('compensation', 'Compensation & Benefits'), ('engagement', 'Employee Engagement'), ('learning', 'Learning & Development'), ('helpdesk', 'HR Helpdesk'), ('analytics', 'Analytics'), ('integrations', 'Integrations')], max_length=50)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_features',
                'unique_together': {('tenant', 'module')},
            },
        ),
    ]
