# Generated by Django 5.2.11 on 2026-02-28 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCIMConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('bearer_token', models.CharField(blank=True, max_length=200)),
                ('base_url', models.URLField(blank=True)),
                ('sync_groups', models.BooleanField(default=True)),
                ('sync_users', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='idle', max_length=20)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scim_config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'scim_configurations',
            },
        ),
        migrations.CreateModel(
            name='SCIMSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=20)),
                ('resource_type', models.CharField(max_length=20)),
                ('resource_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'scim_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('saml', 'SAML 2.0'), ('oidc', 'OpenID Connect'), ('google', 'Google'), ('microsoft', 'Microsoft Entra')], default='saml', max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('idp_entity_id', models.URLField(blank=True, help_text='Identity Provider Entity ID')),
                ('idp_sso_url', models.URLField(blank=True, help_text='IdP SSO Login URL')),
                ('idp_slo_url', models.URLField(blank=True, help_text='IdP Single Logout URL')),
                ('idp_certificate', models.TextField(blank=True, help_text='IdP X.509 certificate (PEM)')),
                ('sp_entity_id', models.URLField(blank=True, help_text='Service Provider Entity ID (this app)')),
                ('sp_acs_url', models.URLField(blank=True, help_text='Assertion Consumer Service URL')),
                ('attribute_mapping', models.JSONField(default=dict, help_text='\n        {"email":"urn:oid:0.9.2342.19200300.100.1.3",\n         "first_name":"urn:oid:2.5.4.42","last_name":"urn:oid:2.5.4.4"}\n    ')),
                ('force_sso', models.BooleanField(default=False, help_text='Require SSO for all users')),
                ('auto_provision', models.BooleanField(default=True, help_text='Auto-create users on first login')),
                ('default_role', models.CharField(default='employee', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sso_configurations',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('price_per_user', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_users', models.IntegerField(default=25)),
                ('current_users', models.IntegerField(default=0)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.subscription')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="e.g. 'leave.apply_leave', 'common.save'", max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('si', 'Sinhala'), ('ta', 'Tamil')], max_length=5)),
                ('value', models.TextField()),
                ('module', models.CharField(blank=True, help_text='Module grouping', max_length=50)),
            ],
            options={
                'db_table': 'translation_keys',
                'ordering': ['key', 'language'],
                'unique_together': {('key', 'language')},
            },
        ),
    ]
