# Generated by Django 5.2.11 on 2026-03-08 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_indexed', models.IntegerField(default=0)),
                ('total_expired_removed', models.IntegerField(default=0)),
                ('total_new_added', models.IntegerField(default=0)),
                ('validation_errors', models.IntegerField(default=0)),
                ('indexing_api_successes', models.IntegerField(default=0)),
                ('indexing_api_failures', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'jf_crawl_health_snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IndexingAPILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('action', models.CharField(choices=[('URL_UPDATED', 'URL Updated (Added/Modified)'), ('URL_DELETED', 'URL Deleted (Removed)')], max_length=15)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jf_indexing_api_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['url', '-created_at'], name='idx_indexing_url')],
            },
        ),
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_type', models.CharField(choices=[('job', 'Job Listing'), ('company', 'Company Page'), ('category', 'Category Page'), ('city', 'City Page'), ('salary', 'Salary Page'), ('blog', 'Blog Post')], max_length=10)),
                ('slug', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('change_frequency', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='daily', max_length=10)),
                ('priority', models.FloatField(default=0.5)),
                ('is_indexable', models.BooleanField(default=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'jf_sitemap_entries',
                'ordering': ['-last_modified'],
                'unique_together': {('page_type', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StructuredDataValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_type', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('warnings', 'Has Warnings'), ('errors', 'Has Errors'), ('pending', 'Pending Validation')], default='pending', max_length=10)),
                ('warnings', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jf_structured_data_validations',
                'ordering': ['-validated_at'],
                'unique_together': {('page_type', 'slug')},
            },
        ),
    ]
