# Generated by Django 5.2.11 on 2026-03-06 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStat',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('total_users', models.IntegerField(default=0)),
                ('total_seekers', models.IntegerField(default=0)),
                ('total_employers', models.IntegerField(default=0)),
                ('total_jobs', models.IntegerField(default=0)),
                ('active_jobs', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('new_jobs_today', models.IntegerField(default=0)),
                ('new_applications_today', models.IntegerField(default=0)),
                ('searches_today', models.IntegerField(default=0)),
                ('page_views_today', models.IntegerField(default=0)),
                ('unique_visitors_today', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jf_platform_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job_views', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('applications_received', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('search_appearances', models.IntegerField(default=0)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_employer_analytics',
                'ordering': ['-date'],
                'unique_together': {('employer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_event_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='idx_event_type_date')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('query', models.CharField(max_length=500)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('clicked_job_id', models.UUIDField(blank=True, null=True)),
                ('clicked_position', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=2)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_search_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_search_log_date')],
            },
        ),
    ]
