# Generated by Django 5.2.11 on 2026-03-06 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_si', models.CharField(blank=True, default='', max_length=200)),
                ('title_ta', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('description_si', models.TextField(blank=True, default='')),
                ('description_ta', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('requirements_si', models.TextField(blank=True, default='')),
                ('requirements_ta', models.TextField(blank=True, default='')),
                ('benefits', models.TextField(blank=True, default='')),
                ('benefits_si', models.TextField(blank=True, default='')),
                ('benefits_ta', models.TextField(blank=True, default='')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary'), ('freelance', 'Freelance')], max_length=10)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive')], default='', max_length=10)),
                ('work_arrangement', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('flexible', 'Flexible')], default='onsite', max_length=10)),
                ('address_line', models.CharField(blank=True, default='', max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(choices=[('LKR', 'Sri Lankan Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'Emirati Dirham'), ('SAR', 'Saudi Riyal'), ('QAR', 'Qatari Riyal'), ('SGD', 'Singapore Dollar')], default='LKR', max_length=3)),
                ('salary_period', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('hide_salary', models.BooleanField(default=False)),
                ('experience_years_min', models.IntegerField(blank=True, null=True)),
                ('experience_years_max', models.IntegerField(blank=True, null=True)),
                ('screening_questions', models.JSONField(blank=True, default=list)),
                ('requires_cover_letter', models.BooleanField(default=False)),
                ('requires_resume', models.BooleanField(default=True)),
                ('apply_method', models.CharField(choices=[('internal', 'In-Platform'), ('external_url', 'External URL'), ('email', 'Email'), ('ats', 'ATS System')], default='internal', max_length=15)),
                ('external_apply_url', models.URLField(blank=True, default='', max_length=500)),
                ('email_apply_address', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('filled', 'Filled'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_boosted', models.BooleanField(default=False)),
                ('boost_factor', models.FloatField(default=1.0)),
                ('ats_job_id', models.CharField(blank=True, default='', max_length=100)),
                ('ats_pipeline_id', models.CharField(blank=True, default='', max_length=100)),
                ('ats_synced_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('application_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, default='', max_length=70)),
                ('meta_description', models.CharField(blank=True, default='', max_length=160)),
                ('canonical_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='taxonomy.jobcategory')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.district')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.employeraccount')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.industry')),
                ('min_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.educationlevel')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('preferred_skills', models.ManyToManyField(blank=True, related_name='preferred_for_jobs', to='taxonomy.skill')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.province')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='required_for_jobs', to='taxonomy.skill')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.jobsubcategory')),
            ],
            options={
                'db_table': 'jf_job_listings',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobs.joblisting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_job_views',
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='jobs.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_saved_jobs',
            },
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['status', '-published_at'], name='idx_job_status_pub'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['employer', 'status'], name='idx_job_employer_status'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['category', 'status'], name='idx_job_cat_status'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['district', 'status'], name='idx_job_district_status'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['job_type', 'status'], name='idx_job_type_status'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['experience_level', 'status'], name='idx_job_exp_status'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['slug'], name='idx_job_slug'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
    ]
