# Generated by Django 5.2.11 on 2026-03-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Display deadline for applications', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='freshness_score',
            field=models.FloatField(default=0.0, help_text='0–100 freshness score'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='is_sponsored',
            field=models.BooleanField(default=False, help_text='Linked to a PromotedJobCampaign'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='language_requirements',
            field=models.JSONField(blank=True, default=list, help_text='e.g. [{"language": "English", "level": "proficient"}]'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='quality_score',
            field=models.FloatField(default=0.0, help_text='0–100 overall quality score'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='quick_apply_enabled',
            field=models.BooleanField(default=False, help_text='Allow one-click apply with saved profile'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('rotating', 'Rotating'), ('flexible', 'Flexible')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='structured_faqs',
            field=models.JSONField(blank=True, default=list, help_text='e.g. [{"question": "", "answer": ""}]'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='visa_sponsorship',
            field=models.BooleanField(default=False, help_text='Job offers visa sponsorship'),
        ),
    ]
