# Generated by Django 5.2.11 on 2026-02-27 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('kudos', 'Kudos'), ('feedback', 'Feedback'), ('coaching', 'Coaching')], default='kudos', max_length=20)),
                ('message', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='["teamwork", "innovation", "leadership"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tenants.tenant')),
                ('to_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='core_hr.employee')),
            ],
            options={
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('annual', 'Annual'), ('semi_annual', 'Semi-Annual'), ('quarterly', 'Quarterly'), ('probation', 'Probation')], default='annual', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('self_review_deadline', models.DateField(blank=True, null=True)),
                ('manager_review_deadline', models.DateField(blank=True, null=True)),
                ('calibration_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_review', 'In Review'), ('calibration', 'Calibration'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('template_config', models.JSONField(blank=True, default=dict, help_text='Review template: competencies, rating scale, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cycles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'review_cycles',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('org', 'Organization'), ('department', 'Department'), ('team', 'Team'), ('individual', 'Individual')], default='individual', max_length=20)),
                ('metric_type', models.CharField(choices=[('percentage', 'Percentage'), ('number', 'Number'), ('currency', 'Currency'), ('boolean', 'Yes/No')], default='percentage', max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='0-100 percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core_hr.employee')),
                ('parent_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_goals', to='performance.goal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tenants.tenant')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='performance.reviewcycle')),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('self_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('final_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('self_comments', models.TextField(blank=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('self_submitted', 'Self Submitted'), ('manager_submitted', 'Manager Submitted'), ('calibrated', 'Calibrated'), ('finalized', 'Finalized')], default='pending', max_length=20)),
                ('calibrated_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calibrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='core_hr.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='tenants.tenant')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.reviewcycle')),
            ],
            options={
                'db_table': 'performance_reviews',
                'constraints': [models.UniqueConstraint(fields=('cycle', 'employee'), name='unique_review_per_cycle')],
            },
        ),
    ]
