# Generated by Django 5.2.11 on 2026-03-07 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0005_criticalrole_internalmobilityprofile'),
        ('performance', '0001_initial'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_year', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succession_plans_as_holder', to='core_hr.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_plans', to='core_hr.position')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'succession_plans',
            },
        ),
        migrations.CreateModel(
            name='SuccessionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('readiness', models.CharField(choices=[('ready_now', 'Ready Now'), ('ready_1_2y', 'Ready in 1-2 Years'), ('ready_3_5y', 'Ready in 3-5 Years'), ('developmental', 'Developmental')], default='developmental', max_length=20)),
                ('rank', models.IntegerField(default=1, help_text='Priority ranking among candidates')),
                ('development_actions', models.JSONField(blank=True, default=list, help_text='[{"action":"...", "target_date":"..."}]')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_candidacies', to='core_hr.employee')),
                ('succession_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='performance.successionplan')),
            ],
            options={
                'db_table': 'succession_candidates',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TalentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('scope', models.JSONField(blank=True, default=dict, help_text='{"departments":[], "levels":[], "all":false}')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_reviews', to='performance.reviewcycle')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_reviews', to='tenants.tenant')),
            ],
            options={
                'db_table': 'talent_reviews',
            },
        ),
        migrations.CreateModel(
            name='NineBoxPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('potential', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('box_label', models.CharField(blank=True, help_text="e.g. 'Star', 'Core Player', 'Growth Employee'", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core_hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nine_box_placements', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nine_box_placements', to='tenants.tenant')),
                ('talent_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='performance.talentreview')),
            ],
            options={
                'db_table': 'nine_box_placements',
            },
        ),
        migrations.CreateModel(
            name='PromotionReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('readiness_score', models.DecimalField(blank=True, decimal_places=1, help_text='0.0–10.0 readiness score', max_digits=4, null=True)),
                ('readiness_label', models.CharField(choices=[('ready_now', 'Ready Now'), ('ready_soon', 'Ready Soon'), ('developing', 'Developing'), ('not_ready', 'Not Ready')], default='not_ready', max_length=20)),
                ('strengths', models.TextField(blank=True)),
                ('gaps', models.TextField(blank=True)),
                ('development_plan', models.JSONField(blank=True, default=list)),
                ('assessment_date', models.DateField()),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core_hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_readiness', to='core_hr.employee')),
                ('target_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core_hr.position')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_readiness', to='tenants.tenant')),
            ],
            options={
                'db_table': 'promotion_readiness',
                'ordering': ['-assessment_date'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='idx_promo_emp')],
            },
        ),
        migrations.AddConstraint(
            model_name='successionplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'position', 'review_year'), name='unique_succession_plan'),
        ),
        migrations.AddConstraint(
            model_name='successioncandidate',
            constraint=models.UniqueConstraint(fields=('succession_plan', 'employee'), name='unique_succession_candidate'),
        ),
        migrations.AddConstraint(
            model_name='nineboxplacement',
            constraint=models.UniqueConstraint(fields=('talent_review', 'employee'), name='unique_nine_box_per_review'),
        ),
    ]
