# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0008_candidatefollowuptask_candidateoutreachlog_and_more'),
        ('jobs', '0005_job_degree_optional_note_job_degree_required_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('preferred', 'Preferred'), ('approved', 'Approved'), ('probationary', 'Probationary'), ('inactive', 'Inactive')], default='approved', max_length=20)),
                ('website', models.URLField(blank=True, default='')),
                ('specialties', models.JSONField(blank=True, default=list, help_text='["Engineering", "Finance", "Executive Search"]')),
                ('regions', models.JSONField(blank=True, default=list, help_text='Geographies this agency covers')),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('nda_signed', models.BooleanField(default=False)),
                ('msa_document_url', models.URLField(blank=True, default='', help_text='Master Service Agreement URL')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_agencies', to='tenants.tenant')),
            ],
            options={
                'db_table': 'vendor_agencies',
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('percent_base', '% of Base Salary'), ('fixed', 'Fixed Fee'), ('retained', 'Retained Search'), ('container', 'Container / Milestone')], default='percent_base', max_length=20)),
                ('fee_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Used when fee_type=percent_base', max_digits=5, null=True)),
                ('fixed_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('guarantee_days', models.IntegerField(default=90, help_text='Days the placement is guaranteed; refund/replacement on exit')),
                ('applies_to_levels', models.JSONField(blank=True, default=list, help_text='Job levels this fee applies to')),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='tenants.tenant')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='vendor_management.vendoragency')),
            ],
            options={
                'db_table': 'fee_schedules',
                'ordering': ['agency', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vendor_management.vendoragency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_contacts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'vendor_contacts',
                'ordering': ['agency', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('submissions_count', models.IntegerField(default=0)),
                ('interviews_count', models.IntegerField(default=0)),
                ('offers_count', models.IntegerField(default=0)),
                ('hires_count', models.IntegerField(default=0)),
                ('avg_time_to_submit_days', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, help_text='0–100 overall quality rating', null=True)),
                ('diversity_hire_rate', models.FloatField(blank=True, help_text='% hires from underrepresented groups', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='vendor_management.vendoragency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_scorecards', to='tenants.tenant')),
            ],
            options={
                'db_table': 'vendor_scorecards',
                'ordering': ['agency', '-period_start'],
            },
        ),
        migrations.CreateModel(
            name='VendorAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('view_only', 'View Only'), ('can_submit', 'Can Submit'), ('exclusive', 'Exclusive')], default='can_submit', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_access_grants_given', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_access_grants', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_access_grants', to='tenants.tenant')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='vendor_management.vendoragency')),
            ],
            options={
                'db_table': 'vendor_access_grants',
                'unique_together': {('agency', 'job')},
            },
        ),
        migrations.CreateModel(
            name='CandidateOwnershipRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ownership_days', models.IntegerField(default=180, help_text='Days vendor retains claim on a submitted candidate')),
                ('applies_across_jobs', models.BooleanField(default=True, help_text='True = ownership applies to any role, False = job-specific')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_rules', to='tenants.tenant')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_rules', to='vendor_management.vendoragency')),
            ],
            options={
                'db_table': 'candidate_ownership_rules',
                'unique_together': {('tenant', 'agency')},
            },
        ),
        migrations.CreateModel(
            name='VendorSLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_time_to_submit_days', models.IntegerField(default=5)),
                ('min_submissions_per_week', models.IntegerField(default=2)),
                ('max_rejection_rate_percent', models.FloatField(default=50.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='vendor_management.vendoragency')),
                ('breach_escalation_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_sla_escalations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_slas', to='tenants.tenant')),
            ],
            options={
                'db_table': 'vendor_slas',
                'unique_together': {('tenant', 'agency')},
            },
        ),
        migrations.CreateModel(
            name='VendorSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_candidate_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='submitted', max_length=20)),
                ('resume_url', models.URLField(blank=True, default='')),
                ('vendor_notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='vendor_management.vendoragency')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_submissions', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_submissions', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_submissions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_submissions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'vendor_submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='vendor_subm_tenant__f13ff1_idx'), models.Index(fields=['agency', 'job'], name='vendor_subm_agency__890e47_idx')],
            },
        ),
    ]
