# Generated by Django 5.2.11 on 2026-03-08 04:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='commute_radius_km',
            field=models.IntegerField(default=25, help_text='Maximum commute radius in km'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='last_job_alert_match',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='notice_period_weeks',
            field=models.IntegerField(blank=True, help_text='Current notice period in weeks', null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='open_to_work',
            field=models.BooleanField(default=False, help_text="Show 'Open to Work' badge publicly"),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='preferred_shift',
            field=models.CharField(blank=True, choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('rotating', 'Rotating'), ('flexible', 'Flexible')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='public_profile_slug',
            field=models.SlugField(blank=True, default='', help_text='Slug for public profile URL', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='recruiter_visibility',
            field=models.CharField(choices=[('all', 'All Recruiters'), ('premium_only', 'Premium Recruiters Only'), ('none', 'Hidden')], default='all', help_text='Who can see seeker in recruiter search', max_length=15),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='trust_score',
            field=models.IntegerField(default=50, help_text='0–100 seeker trust score'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='work_auth',
            field=models.CharField(blank=True, choices=[('citizen', 'Citizen'), ('permanent_resident', 'Permanent Resident'), ('work_permit', 'Work Permit'), ('student_visa', 'Student Visa')], default='', help_text='Work authorization status', max_length=20),
        ),
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(max_length=200)),
                ('target_industry', models.CharField(blank=True, default='', max_length=200)),
                ('current_readiness', models.IntegerField(default=0, help_text='0-100 readiness score')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('achieved', 'Achieved'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('milestones', models.JSONField(blank=True, default=list, help_text='List of milestone objects with title, done, due_date')),
                ('skill_gaps', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='candidates.seekerprofile')),
            ],
            options={
                'db_table': 'jf_career_roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('ai', 'AI-Powered'), ('human', 'Human Expert')], default='ai', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('target_role', models.CharField(blank=True, default='', max_length=200)),
                ('interview_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('case', 'Case Study'), ('culture', 'Culture Fit')], default='behavioral', max_length=20)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('responses', models.JSONField(blank=True, default=list)),
                ('feedback', models.JSONField(blank=True, default=dict)),
                ('overall_score', models.IntegerField(blank=True, help_text='0-100', null=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to='candidates.seekerprofile')),
            ],
            options={
                'db_table': 'jf_mock_interviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
