# Generated by Django 5.2.11 on 2026-03-08 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_seekerprofile_commute_radius_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_override', models.CharField(blank=True, default='', max_length=200)),
                ('phone_override', models.CharField(blank=True, default='', max_length=20)),
                ('email_override', models.EmailField(blank=True, default='', max_length=254)),
                ('cover_letter_template', models.TextField(blank=True, default='', help_text='Default cover letter template, use {{job_title}} / {{company_name}} placeholders')),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='LKR', max_length=5)),
                ('work_auth_statement', models.CharField(blank=True, default='', max_length=300)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=300)),
                ('portfolio_url', models.URLField(blank=True, default='', max_length=300)),
                ('github_url', models.URLField(blank=True, default='', max_length=300)),
                ('additional_questions', models.JSONField(blank=True, default=dict, help_text='Pre-filled answers to common employer questions keyed by question text')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_profile', to='candidates.seekerprofile')),
            ],
            options={
                'db_table': 'jf_application_profiles',
            },
        ),
        migrations.CreateModel(
            name='SeekerActivityTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('profile_updated', 'Profile Updated'), ('resume_uploaded', 'Resume Uploaded'), ('application_sent', 'Application Sent'), ('job_saved', 'Job Saved'), ('job_viewed', 'Job Viewed'), ('badge_earned', 'Badge Earned'), ('search_done', 'Search Performed'), ('preferences_updated', 'Preferences Updated'), ('visibility_changed', 'Visibility Changed'), ('careeros_import', 'CareerOS Profile Import'), ('interview_scheduled', 'Interview Scheduled'), ('offer_received', 'Offer Received')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra event-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='candidates.seekerprofile')),
            ],
            options={
                'db_table': 'jf_seeker_timeline',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seeker', '-created_at'], name='idx_timeline_seeker')],
            },
        ),
        migrations.CreateModel(
            name='SeekerBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('profile_complete', 'Profile Complete'), ('resume_uploaded', 'Resume Uploaded'), ('skill_verified', 'Skill Verified'), ('10_applications', '10 Applications'), ('first_apply', 'First Application'), ('open_to_work', 'Open To Work'), ('careeros_import', 'CareerOS Import'), ('top_applicant', 'Top Applicant'), ('trusted', 'Trusted Profile'), ('multilingual', 'Multilingual'), ('linkedin_connected', 'LinkedIn Connected'), ('certified', 'Certified Professional')], max_length=30)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='candidates.seekerprofile')),
            ],
            options={
                'db_table': 'jf_seeker_badges',
                'ordering': ['awarded_at'],
                'unique_together': {('seeker', 'badge_type')},
            },
        ),
    ]
