# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('agency_crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('job_orders_received', models.IntegerField(default=0)),
                ('job_orders_filled', models.IntegerField(default=0)),
                ('fill_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_time_to_fill_days', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('avg_time_to_submit_days', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('submissions_sent', models.IntegerField(default=0)),
                ('interviews_conducted', models.IntegerField(default=0)),
                ('offers_made', models.IntegerField(default=0)),
                ('placements_made', models.IntegerField(default=0)),
                ('contractors_active', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('invoices_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dso_days', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_analytics', to='agencies.agency')),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_records', to='agency_crm.clientaccount')),
            ],
            options={
                'db_table': 'analytics_client',
                'ordering': ['-period_start'],
                'unique_together': {('agency', 'client_account', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='DailyKPISnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('open_job_orders', models.IntegerField(default=0)),
                ('active_assignments', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('new_submissions', models.IntegerField(default=0)),
                ('submissions_to_interviews', models.IntegerField(default=0)),
                ('interviews_to_offers', models.IntegerField(default=0)),
                ('offers_to_starts', models.IntegerField(default=0)),
                ('placements_this_day', models.IntegerField(default=0)),
                ('revenue_this_day', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_margin_this_day', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('contractors_available', models.IntegerField(default=0)),
                ('contractors_on_assignment', models.IntegerField(default=0)),
                ('assignments_ending_in_30_days', models.IntegerField(default=0)),
                ('expiring_credentials_30d', models.IntegerField(default=0)),
                ('open_compliance_issues', models.IntegerField(default=0)),
                ('timesheets_pending_approval', models.IntegerField(default=0)),
                ('timesheets_missing', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='agencies.agency')),
            ],
            options={
                'db_table': 'analytics_daily_kpi',
                'ordering': ['-snapshot_date'],
                'unique_together': {('agency', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='FunnelMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('sourced', models.IntegerField(default=0)),
                ('screened', models.IntegerField(default=0)),
                ('submitted', models.IntegerField(default=0)),
                ('shortlisted', models.IntegerField(default=0)),
                ('interviewed', models.IntegerField(default=0)),
                ('offered', models.IntegerField(default=0)),
                ('placed', models.IntegerField(default=0)),
                ('source_to_submit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submit_to_interview_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interview_to_offer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('offer_to_start_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ghosting_count', models.IntegerField(default=0)),
                ('withdrawal_count', models.IntegerField(default=0)),
                ('rejection_count', models.IntegerField(default=0)),
                ('fallthrough_count', models.IntegerField(default=0)),
                ('redeployment_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_metrics', to='agencies.agency')),
            ],
            options={
                'db_table': 'analytics_funnel',
                'ordering': ['-period_start'],
                'unique_together': {('agency', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='RecruiterPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('calls_made', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('candidates_sourced', models.IntegerField(default=0)),
                ('submissions_made', models.IntegerField(default=0)),
                ('interviews_arranged', models.IntegerField(default=0)),
                ('placements_made', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_margin_generated', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('submission_to_interview_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interview_to_offer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('offer_to_start_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_performance', to='agencies.agency')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_recruiter_perf',
                'ordering': ['-period_start'],
                'unique_together': {('agency', 'recruiter', 'period_start')},
            },
        ),
    ]
