# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('overall_score', models.FloatField(default=0.0, help_text='0–100 composite health')),
                ('job_supply_score', models.FloatField(default=0.0)),
                ('seeker_demand_score', models.FloatField(default=0.0)),
                ('apply_conversion_score', models.FloatField(default=0.0)),
                ('employer_response_score', models.FloatField(default=0.0)),
                ('trust_score', models.FloatField(default=0.0)),
                ('fraud_rate', models.FloatField(default=0.0, help_text='% of jobs flagged as suspicious')),
                ('duplicate_rate', models.FloatField(default=0.0)),
                ('avg_apply_rate', models.FloatField(default=0.0, help_text='% of viewers who apply')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'jf_marketplace_health_scores',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployerROISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('job_views', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('applications', models.IntegerField(default=0)),
                ('applications_quality_score', models.FloatField(default=0.0, help_text='0–100 quality of applicants')),
                ('shortlisted', models.IntegerField(default=0)),
                ('hired', models.IntegerField(default=0)),
                ('avg_time_to_shortlist_hours', models.FloatField(blank=True, null=True)),
                ('sponsored_impressions', models.IntegerField(default=0)),
                ('sponsored_clicks', models.IntegerField(default=0)),
                ('sponsored_spend_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('organic_applies', models.IntegerField(default=0)),
                ('sponsored_applies', models.IntegerField(default=0)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_summaries', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_employer_roi_summaries',
                'ordering': ['-week_start'],
                'unique_together': {('employer', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('step', models.CharField(choices=[('search', 'Job Search'), ('job_view', 'Job Detail View'), ('job_save', 'Job Saved'), ('apply_start', 'Apply Started'), ('apply_submit', 'Application Submitted'), ('company_view', 'Company Page View'), ('alert_open', 'Alert Email Opened'), ('alert_click', 'Alert Email Clicked')], max_length=15)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('employer_id', models.UUIDField(blank=True, null=True)),
                ('search_query', models.CharField(blank=True, default='', max_length=300)),
                ('page_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_channel', models.CharField(blank=True, default='', help_text='organic/alert/saved/promoted/direct', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_funnel_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['step', 'created_at'], name='idx_funnel_step_date'), models.Index(fields=['user', 'step'], name='idx_funnel_user_step')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceLiquiditySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active_jobs', models.IntegerField(default=0, help_text='Supply: active job count')),
                ('seeker_searches', models.IntegerField(default=0, help_text='Demand: seekers searching in this segment')),
                ('apply_count', models.IntegerField(default=0)),
                ('demand_supply_ratio', models.FloatField(default=0.0, help_text='seekers_searching / active_jobs (>1 = under-supplied)')),
                ('avg_time_to_fill_days', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_snapshots', to='taxonomy.jobcategory')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidity_snapshots', to='taxonomy.district')),
            ],
            options={
                'db_table': 'jf_marketplace_liquidity',
                'ordering': ['-date'],
                'unique_together': {('date', 'category', 'district')},
            },
        ),
    ]
