# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0008_candidatefollowuptask_candidateoutreachlog_and_more'),
        ('jobs', '0005_job_degree_optional_note_job_degree_required_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('query_json', models.JSONField(default=dict, help_text='{"query": "python", "location": "NYC", "min_experience": 3, "skills": ["React"]}')),
                ('notify_on_match', models.BooleanField(default=False, help_text='Email user when new candidates match this search')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('result_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_searches',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, default='', help_text='initial_score, re_scored, skills_updated, resume_updated', max_length=100)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='candidates.candidate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'score_history',
                'ordering': ['-scored_at'],
                'indexes': [models.Index(fields=['tenant', 'candidate', 'scored_at'], name='score_histo_tenant__745327_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchSegmentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('segment_query', models.JSONField(blank=True, default=dict, help_text='{"skills": [...], "location": "...", "min_experience": 3}')),
                ('alert_type', models.CharField(choices=[('supply_drop', 'Supply Drop'), ('supply_surge', 'Supply Surge'), ('competition_spike', 'Competition Spike'), ('new_match', 'New Talent Match')], default='supply_drop', max_length=30)),
                ('threshold', models.FloatField(blank=True, help_text='Numeric threshold that triggers the alert (e.g. percentage change)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segment_alerts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_alerts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'search_segment_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='search_segm_tenant__c35d02_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillSynonym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant', models.CharField(db_index=True, max_length=200)),
                ('canonical', models.CharField(max_length=200)),
                ('tenant', models.ForeignKey(blank=True, help_text='null = global synonym', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'skill_synonyms',
                'unique_together': {('tenant', 'variant')},
            },
        ),
    ]
