# Generated by Django 5.2.11 on 2026-02-25 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('file_content', models.BinaryField(blank=True, help_text='Raw file bytes (stored in DB for simplicity, move to S3 later)', null=True)),
                ('file_type', models.CharField(default='pdf', max_length=10)),
                ('file_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_json', models.JSONField(blank=True, default=dict)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=300)),
                ('candidate_email', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('scoring', 'Scoring'), ('done', 'Done'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='tenants.tenant')),
            ],
            options={
                'db_table': 'batch_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchItemScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_total', models.IntegerField(default=0, help_text='0-100 ATS score')),
                ('content_score', models.FloatField(default=0, help_text='0-1 content match')),
                ('title_score', models.FloatField(default=0, help_text='0-1 title alignment')),
                ('experience_score', models.FloatField(default=0, help_text='0-1 experience fit')),
                ('recency_score', models.FloatField(default=0, help_text='0-1 recency')),
                ('format_score', models.FloatField(default=0, help_text='0-1 format quality')),
                ('breakdown_json', models.JSONField(blank=True, default=dict, help_text='Full breakdown: matched/missing skills, evidence, penalties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='scoring.batchitem')),
            ],
            options={
                'db_table': 'batch_item_scores',
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, default='', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_profiles',
            },
        ),
        migrations.CreateModel(
            name='CandidateResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('file_content', models.BinaryField(blank=True, null=True)),
                ('file_type', models.CharField(default='pdf', max_length=10)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_json', models.JSONField(blank=True, default=dict)),
                ('version_label', models.CharField(blank=True, default='', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_resume_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateScoreRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jd_text', models.TextField(help_text='Job description used for scoring')),
                ('jd_title', models.CharField(blank=True, default='', max_length=300)),
                ('jd_requirements_json', models.JSONField(blank=True, default=dict)),
                ('score_total', models.IntegerField(default=0)),
                ('content_score', models.FloatField(default=0)),
                ('title_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('recency_score', models.FloatField(default=0)),
                ('format_score', models.FloatField(default=0)),
                ('breakdown_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_runs', to='scoring.candidateresumeversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_score_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobScoreBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, default='', max_length=300)),
                ('jd_text', models.TextField(help_text='Raw job description text')),
                ('jd_requirements_json', models.JSONField(blank=True, default=dict, help_text='Extracted requirements: skills, years, location, etc.')),
                ('scoring_weights', models.JSONField(blank=True, default=dict, help_text='Custom weights override: {content, title, experience, recency, format}')),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('parsed_items', models.IntegerField(default=0)),
                ('scored_items', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_batches', to='tenants.tenant')),
            ],
            options={
                'db_table': 'job_score_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='batchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scoring.jobscorebatch'),
        ),
    ]
