# Generated by Django 5.2.11 on 2026-03-03 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_offer_hrm_employee_fields'),
        ('scoring', '0001_initial'),
        ('tenants', '0003_tenant_max_candidates_tenant_max_jobs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('criteria', models.JSONField(default=list, help_text='List of criteria dicts: [{name, weight, description}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecard_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'scorecard_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_date', models.DateTimeField(help_text='When the interview took place')),
                ('overall_score', models.IntegerField(help_text='1-5 overall rating')),
                ('technical_score', models.IntegerField(blank=True, help_text='1-5 technical skills', null=True)),
                ('communication_score', models.IntegerField(blank=True, help_text='1-5 communication', null=True)),
                ('culture_fit_score', models.IntegerField(blank=True, help_text='1-5 culture fit', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('recommendation', models.CharField(choices=[('strong_yes', 'Strong Yes'), ('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No'), ('strong_no', 'Strong No')], default='yes', max_length=20)),
                ('extra_scores', models.JSONField(blank=True, default=dict, help_text='Additional per-criteria scores: {criteria_name: score}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='applications.application')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_scorecards', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='scoring.scorecardtemplate')),
            ],
            options={
                'db_table': 'scorecards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application'], name='scorecards_applica_4d8c7e_idx'), models.Index(fields=['interviewer'], name='scorecards_intervi_eb0294_idx')],
                'unique_together': {('application', 'interviewer')},
            },
        ),
    ]
