# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('band', models.CharField(blank=True, max_length=50)),
                ('job_family', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mid_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('market_data_source', models.CharField(blank=True, max_length=200)),
                ('market_percentile', models.IntegerField(default=50, help_text='Target market positioning (50 = median)')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_bands', to='tenants.tenant')),
            ],
            options={
                'db_table': 'compensation_bands',
                'ordering': ['grade', 'band', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquityGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grant_type', models.CharField(choices=[('stock_option', 'Stock Option'), ('rsu', 'RSU'), ('phantom', 'Phantom Stock'), ('sar', 'Stock Appreciation Right'), ('espp', 'ESPP')], max_length=20)),
                ('grant_date', models.DateField()),
                ('units_granted', models.IntegerField()),
                ('grant_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('vesting_schedule', models.JSONField(default=list, help_text='[{"date":"2025-01-01","units":250,"vested":false}]')),
                ('cliff_months', models.IntegerField(default=12)),
                ('total_vesting_months', models.IntegerField(default=48)),
                ('units_vested', models.IntegerField(default=0)),
                ('units_exercised', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('vesting', 'Vesting'), ('vested', 'Vested'), ('exercised', 'Exercised'), ('forfeited', 'Forfeited'), ('expired', 'Expired')], default='granted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_grants', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_grants', to='tenants.tenant')),
            ],
            options={
                'db_table': 'equity_grants',
                'ordering': ['-grant_date'],
            },
        ),
        migrations.CreateModel(
            name='MeritCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cycle_year', models.IntegerField()),
                ('cycle_type', models.CharField(choices=[('annual', 'Annual'), ('mid_year', 'Mid-Year'), ('off_cycle', 'Off-Cycle')], default='annual', max_length=20)),
                ('budget_pool_pct', models.DecimalField(decimal_places=2, default=0, help_text='Total merit budget as % of payroll', max_digits=5)),
                ('effective_date', models.DateField()),
                ('manager_input_deadline', models.DateField(blank=True, null=True)),
                ('calibration_deadline', models.DateField(blank=True, null=True)),
                ('approval_deadline', models.DateField(blank=True, null=True)),
                ('communication_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('manager_input', 'Manager Input'), ('calibration', 'Calibration'), ('approval', 'Approval'), ('finalized', 'Finalized'), ('communicated', 'Communicated'), ('closed', 'Closed')], default='planning', max_length=20)),
                ('guidelines', models.JSONField(default=dict, help_text='{"exceeds":0.06,"meets":0.04,"below":0.00,"promo_additional":0.08}')),
                ('total_eligible_employees', models.IntegerField(default=0)),
                ('total_budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('total_allocated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_cycles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'merit_cycles',
                'ordering': ['-cycle_year'],
            },
        ),
        migrations.CreateModel(
            name='PayEquityAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('gender', 'Gender Pay Gap'), ('ethnicity', 'Ethnicity Pay Gap'), ('grade', 'Grade Pay Spread'), ('tenure', 'Tenure vs Pay'), ('department', 'Department Pay Spread')], max_length=20)),
                ('analysis_date', models.DateField()),
                ('scope', models.JSONField(default=dict, help_text='{"department":"Engineering","grade":"G4"}')),
                ('results', models.JSONField(default=dict, help_text='{"group_a":{"avg_salary":...,"median_salary":...,"count":...},...}')),
                ('gap_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Overall pay gap % (positive = group A earns more)', max_digits=6, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('recommended_actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_equity_analyses', to='tenants.tenant')),
            ],
            options={
                'db_table': 'pay_equity_analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='MeritRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('merit', 'Merit Increase'), ('bonus', 'Bonus'), ('promotion', 'Promotion + Merit'), ('no_change', 'No Change'), ('demotion', 'Demotion')], default='merit', max_length=20)),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recommended_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('merit_increase_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('performance_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('compa_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Salary / midpoint of band', max_digits=5, null=True)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('calibrated', 'Calibrated'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('calibrated_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('calibrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='total_rewards.meritcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_recommendations', to='core_hr.employee')),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_recommendations_given', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_recommendations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'merit_recommendations',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='TotalRewardsStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('equity_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employer_benefits_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employer_statutory_value', models.DecimalField(decimal_places=2, default=0, help_text='EPF/ETF employer portion', max_digits=14)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_compensation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('breakdown', models.JSONField(default=dict, help_text='Full itemised breakdown')),
                ('pdf_url', models.CharField(blank=True, max_length=500)),
                ('is_visible_to_employee', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_rewards_statements', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_rewards_statements', to='tenants.tenant')),
            ],
            options={
                'db_table': 'total_rewards_statements',
                'ordering': ['-statement_year'],
                'unique_together': {('tenant', 'employee', 'statement_year')},
            },
        ),
    ]
