# Generated by Django 5.2.11 on 2026-03-09 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0005_criticalrole_internalmobilityprofile'),
        ('tenants', '0003_billing_history'),
        ('total_rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusIncentivePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('plan_type', models.CharField(choices=[('annual_bonus', 'Annual Bonus'), ('quarterly_bonus', 'Quarterly Bonus'), ('spot_award', 'Spot Award'), ('retention_bonus', 'Retention Bonus'), ('performance_incentive', 'Performance Incentive')], max_length=30)),
                ('plan_year', models.IntegerField()),
                ('eligibility_criteria', models.JSONField(blank=True, default=dict, help_text='{"grades": [...], "departments": [...], "min_tenure_months": 6}')),
                ('target_pct', models.DecimalField(decimal_places=2, default=0, help_text='Target bonus as % of annual salary', max_digits=5)),
                ('max_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('funding_formula', models.JSONField(blank=True, default=dict, help_text='{"company_performance_weight":0.5,"individual_performance_weight":0.5}')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_incentive_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'bonus_incentive_plans',
                'ordering': ['-plan_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompChangeApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(default=1, help_text='1=Line Manager, 2=HR, 3=Finance, etc.')),
                ('change_type', models.CharField(blank=True, max_length=50)),
                ('proposed_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('increase_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_change_approvals', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_change_approvals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'comp_change_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusIncentiveEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('awarded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('company_performance_factor', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('individual_performance_factor', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('calculation_breakdown', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('manager_review', 'Manager Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('withheld', 'Withheld')], default='calculated', max_length=20)),
                ('manager_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_incentive_entries', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_incentive_entries', to='tenants.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='total_rewards.bonusincentiveplan')),
            ],
            options={
                'db_table': 'bonus_incentive_entries',
                'ordering': ['-created_at'],
                'unique_together': {('plan', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='ManagerCompReviewWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('calibrated', 'Calibrated'), ('locked', 'Locked')], default='open', max_length=20)),
                ('budget_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('team_snapshot', models.JSONField(blank=True, default=list, help_text='Snapshot of team members with salary data at cycle open')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_workspaces', to='total_rewards.meritcycle')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_review_workspaces', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_comp_review_workspaces', to='tenants.tenant')),
            ],
            options={
                'db_table': 'manager_comp_review_workspaces',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'manager')},
            },
        ),
    ]
