# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0005_offer_esign_document_url_offer_esign_envelope_id_and_more'),
        ('candidates', '0008_candidatefollowuptask_candidateoutreachlog_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('provider', models.CharField(blank=True, default='', max_length=255)),
                ('use_case', models.CharField(help_text='e.g. Resume scoring, JD quality analysis', max_length=255)),
                ('risk_level', models.CharField(choices=[('minimal', 'Minimal Risk'), ('limited', 'Limited Risk'), ('high', 'High Risk (Annex III)'), ('unacceptable', 'Unacceptable Risk (Prohibited)')], default='limited', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('technical_documentation_url', models.URLField(blank=True, default='')),
                ('conformity_assessment_done', models.BooleanField(default=False)),
                ('human_oversight_required', models.BooleanField(default=True, help_text='EU AI Act Annex III — mandatory for high-risk')),
                ('explainability_method', models.CharField(blank=True, default='', help_text='e.g. SHAP, LIME, rule-based explanation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_models',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_resume_scoring', models.BooleanField(default=True)),
                ('allow_jd_analysis', models.BooleanField(default=True)),
                ('allow_market_benchmarking', models.BooleanField(default=True)),
                ('allow_predictive_analytics', models.BooleanField(default=True)),
                ('require_human_review_for_rejections', models.BooleanField(default=True, help_text='Require human confirmation before auto-rejecting via AI')),
                ('data_retention_days', models.IntegerField(default=365, help_text='Days AI logs are retained before purging')),
                ('custom_restrictions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_policy', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_policies',
            },
        ),
        migrations.CreateModel(
            name='AIPromptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_hash', models.CharField(help_text='SHA-256 of prompt text for dedup', max_length=64)),
                ('prompt_preview', models.CharField(blank=True, default='', help_text='First 500 chars of prompt (no PII)', max_length=500)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompt_logs', to='compliance_ai.aimodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompt_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_prompt_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIOutputLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_summary', models.TextField(blank=True, default='', help_text='Plain-language summary (no PII)')),
                ('score_or_decision', models.CharField(blank=True, default='', max_length=255)),
                ('explanation', models.TextField(blank=True, default='', help_text='SHAP/LIME or rule explanation')),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_output_logs', to='tenants.tenant')),
                ('prompt_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output_log', to='compliance_ai.aipromptlog')),
            ],
            options={
                'db_table': 'ai_output_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiasMonitoringReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_decisions', models.IntegerField(default=0)),
                ('adverse_impact_ratio', models.JSONField(blank=True, default=dict, help_text='{"gender": {"female": 0.82, "male": 1.0}, "ethnicity": {...}}')),
                ('disparate_impact_flags', models.JSONField(blank=True, default=list, help_text='Groups with ratio < 0.8 (4/5ths rule)')),
                ('remediation_actions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bias_reports', to='compliance_ai.aimodel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bias_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_monitoring_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'bias_monitoring_reports',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='CandidateAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appeal_reason', models.TextField()),
                ('ai_decision_explained', models.TextField(blank=True, default='', help_text='Explanation of the AI decision that is being appealed')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed')], default='submitted', max_length=20)),
                ('outcome_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_appeals', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='candidates.candidate')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_appeal_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_appeals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'candidate_appeals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DPIATemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sections', models.JSONField(blank=True, default=list, help_text='[{"title": "...", "questions": ["..."]}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpia_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'dpia_templates',
            },
        ),
        migrations.CreateModel(
            name='DPIAAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, help_text='Next scheduled review', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpia_assessments', to='compliance_ai.aimodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpias_created', to=settings.AUTH_USER_MODEL)),
                ('dpo_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpia_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpia_assessments', to='tenants.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='compliance_ai.dpiatemplate')),
            ],
            options={
                'db_table': 'dpia_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanReviewQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('application_score', 'Application Score'), ('resume_parse', 'Resume Parse'), ('jd_quality', 'JD Quality Score'), ('assessment_result', 'Assessment Result'), ('offer_recommendation', 'Offer Recommendation'), ('other', 'Other')], max_length=30)),
                ('object_id', models.UUIDField(help_text='UUID of the reviewed object (application, score, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('overridden', 'Overridden'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('review_deadline', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_queue_items', to='compliance_ai.aioutputlog')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reviews_assigned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_review_queue', to='tenants.tenant')),
            ],
            options={
                'db_table': 'human_review_queue',
                'ordering': ['review_deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIOverrideRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_decision', models.CharField(help_text='Original AI output / decision', max_length=255)),
                ('human_decision', models.CharField(help_text="Human's final decision", max_length=255)),
                ('override_reason', models.TextField()),
                ('override_category', models.CharField(blank=True, default='', help_text='e.g. bias_suspected, factual_error, context_not_captured', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_overrides', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_override_records', to='tenants.tenant')),
                ('review_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='override_record', to='compliance_ai.humanreviewqueue')),
            ],
            options={
                'db_table': 'ai_override_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aipromptlog',
            index=models.Index(fields=['tenant', 'ai_model'], name='ai_prompt_l_tenant__7e8a66_idx'),
        ),
        migrations.AddIndex(
            model_name='aipromptlog',
            index=models.Index(fields=['created_at'], name='ai_prompt_l_created_c8eb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='humanreviewqueue',
            index=models.Index(fields=['tenant', 'status'], name='human_revie_tenant__081df8_idx'),
        ),
    ]
