# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, default='', max_length=200)),
                ('platform', models.CharField(max_length=5)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('screens_visited', models.JSONField(default=list)),
                ('jobs_viewed', models.JSONField(default=list)),
                ('session_duration_seconds', models.IntegerField(default=0)),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_mobile_session_logs',
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='DevicePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=200)),
                ('language', models.CharField(default='en', max_length=5)),
                ('enable_job_alerts', models.BooleanField(default=True)),
                ('enable_application_updates', models.BooleanField(default=True)),
                ('enable_messages', models.BooleanField(default=True)),
                ('enable_promotions', models.BooleanField(default=False)),
                ('commute_location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('commute_location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('commute_radius_km', models.IntegerField(default=25)),
                ('low_bandwidth_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_device_preferences',
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='PushDeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(help_text='FCM registration token or APNs device token', unique=True)),
                ('platform', models.CharField(choices=[('fcm', 'Firebase (Android)'), ('apns', 'Apple (iOS)'), ('web', 'Web Push')], max_length=5)),
                ('device_id', models.CharField(blank=True, default='', max_length=200)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('os_version', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_push_device_tokens',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_push_user_active')],
            },
        ),
    ]
