# Generated by Django 5.2.11 on 2026-02-28 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0001_initial'),
        ('onboarding', '0001_initial'),
        ('tenants', '0002_scimconfiguration_scimsynclog_ssoconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exit_type', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('contract_end', 'Contract End'), ('mutual', 'Mutual Separation')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('resignation_date', models.DateField()),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('notice_served', models.BooleanField(default=False)),
                ('notice_buyout', models.BooleanField(default=False, help_text='Employee buying out notice period')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('notice_period', 'Notice Period'), ('handover', 'Handover'), ('exit_interview', 'Exit Interview'), ('settlement', 'Final Settlement'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('settlement_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'exit_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conducted_at', models.DateTimeField(blank=True, null=True)),
                ('responses', models.JSONField(default=dict, help_text='{"reason_for_leaving":"...","would_recommend":true,"satisfaction_rating":3,"feedback":"..."}')),
                ('overall_experience_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('manager_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('would_rejoin', models.BooleanField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='onboarding.exitrequest')),
            ],
            options={
                'db_table': 'exit_interviews',
            },
        ),
        migrations.CreateModel(
            name='ExitChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hr', 'HR'), ('it', 'IT'), ('finance', 'Finance'), ('manager', 'Manager'), ('facilities', 'Facilities')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='onboarding.exitrequest')),
            ],
            options={
                'db_table': 'exit_checklist_items',
                'ordering': ['sort_order'],
            },
        ),
    ]
