# Generated by Django 5.2.11 on 2026-03-07 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0005_criticalrole_internalmobilityprofile'),
        ('onboarding', '0002_exitrequest_exitinterview_exitchecklist'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestonePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='30-60-90 Day Plan', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_plans', to='core_hr.employee')),
                ('onboarding_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_plans', to='onboarding.onboardinginstance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'milestone_plans',
            },
        ),
        migrations.CreateModel(
            name='MilestonePlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('preboarding', 'Pre-boarding'), ('first_week', 'First Week'), ('30_day', '30 Day'), ('60_day', '60 Day'), ('90_day', '90 Day'), ('custom', 'Custom')], default='30_day', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('success_criteria', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core_hr.employee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboarding.milestoneplan')),
            ],
            options={
                'db_table': 'milestone_plan_items',
                'ordering': ['phase', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PreboardingPortal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Secure access token for portal link', max_length=64, unique=True)),
                ('welcome_message', models.TextField(blank=True)),
                ('documents_to_complete', models.JSONField(blank=True, default=list, help_text='[{"title":"Tax Form", "url":"..."}]')),
                ('tasks_completed', models.JSONField(blank=True, default=list, help_text='["tax_form", "bank_details", "policy_acknowledgement"]')),
                ('portal_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preboarding_portal', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preboarding_portals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'preboarding_portals',
            },
        ),
        migrations.CreateModel(
            name='BuddyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('meeting_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_assignments_as_buddy', to='core_hr.employee')),
                ('new_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_assignments_as_new', to='core_hr.employee')),
                ('onboarding_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddy_assignments', to='onboarding.onboardinginstance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_assignments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'buddy_assignments',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'new_employee', 'buddy'), name='unique_buddy_assignment')],
            },
        ),
    ]
