# Generated by Django 5.2.11 on 2026-03-03 10:01

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0003_gin_indexes_and_immutability'),
        ('tenants', '0002_scimconfiguration_scimsynclog_ssoconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('employee_number', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('nic_number', models.CharField(blank=True, help_text='Sri Lanka National ID', max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('personal_email', models.EmailField(blank=True, max_length=320)),
                ('work_email', models.EmailField(max_length=320)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('address_current', models.JSONField(blank=True, default=dict)),
                ('address_permanent', models.JSONField(blank=True, default=dict)),
                ('hire_date', models.DateField()),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('probation', 'Probation'), ('intern', 'Intern'), ('part_time', 'Part-time'), ('casual', 'Casual')], default='permanent', max_length=30)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('casual', 'Casual')], default='full_time', max_length=20)),
                ('work_schedule', models.CharField(choices=[('standard', 'Standard'), ('shift', 'Shift-based'), ('flexible', 'Flexible')], default='standard', max_length=20)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('probation_months', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('retired', 'Retired'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('separation_date', models.DateField(blank=True, null=True)),
                ('separation_type', models.CharField(blank=True, choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('contract_end', 'Contract End'), ('death', 'Death'), ('mutual', 'Mutual Separation')], max_length=30)),
                ('separation_reason', models.TextField(blank=True)),
                ('emergency_contact', models.JSONField(blank=True, default=dict, help_text='{"name": "", "relationship": "", "phone": "", "address": ""}')),
                ('bank_details', models.JSONField(blank=True, default=dict, help_text='{"bank_name": "", "branch": "", "account_no": "", "account_type": ""}')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('ats_import', 'ATS Import'), ('bulk_import', 'Bulk Import')], default='manual', max_length=30)),
                ('ats_candidate_id', models.UUIDField(blank=True, help_text='Link to ATS candidate record', null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.branch')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.company')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.employee')),
                ('position', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_hr.position')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
