# Generated by Django 5.2.11 on 2026-03-07 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rationale', models.TextField(blank=True, help_text='Why this role is considered critical')),
                ('impact_if_vacant', models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('target_successor_count', models.IntegerField(default=2, help_text='Desired number of ready successors')),
                ('review_date', models.DateField(blank=True, help_text='Next scheduled review of this critical role designation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_critical_roles', to=settings.AUTH_USER_MODEL)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='critical_role', to='core_hr.position')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_roles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'critical_roles',
                'ordering': ['position__title'],
            },
        ),
        migrations.CreateModel(
            name='InternalMobilityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_to_move', models.BooleanField(default=False, help_text='Employee is open to internal moves')),
                ('mobility_type', models.JSONField(blank=True, default=list, help_text='["lateral","promotion","project","relocation","remote"]')),
                ('preferred_locations', models.JSONField(blank=True, default=list, help_text='List of preferred branch/location names')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='List of position IDs the employee is targeting')),
                ('earliest_available', models.DateField(blank=True, help_text='Earliest date employee is available for a move', null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_mobility_profile', to='core_hr.employee')),
                ('preferred_departments', models.ManyToManyField(blank=True, related_name='interested_employees', to='core_hr.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_hr_mobility_profiles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'internal_mobility_profiles',
            },
        ),
    ]
