# Generated by Django 5.2.11 on 2026-02-27 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('salary_advance', 'Salary Advance'), ('personal_loan', 'Personal Loan'), ('festival_advance', 'Festival Advance'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments_total', models.IntegerField()),
                ('installments_paid', models.IntegerField(default=0)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'loan_records',
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('review', 'Review'), ('approved', 'Approved'), ('finalized', 'Finalized'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('employee_count', models.IntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_employer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='core_hr.company')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payroll_runs',
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('earnings_json', models.JSONField(default=list, help_text='[{"component": "...", "amount": 0, "description": "..."}]')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions_json', models.JSONField(default=list)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('epf_employee', models.DecimalField(decimal_places=2, default=0, help_text='8% of relevant earnings', max_digits=10)),
                ('epf_employer', models.DecimalField(decimal_places=2, default=0, help_text='12% of relevant earnings', max_digits=10)),
                ('etf_employer', models.DecimalField(decimal_places=2, default=0, help_text='3% of relevant earnings', max_digits=10)),
                ('apit', models.DecimalField(decimal_places=2, default=0, help_text='Advanced Personal Income Tax', max_digits=10)),
                ('statutory_json', models.JSONField(blank=True, default=dict)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ot_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_worked', models.IntegerField(blank=True, null=True)),
                ('days_absent', models.IntegerField(default=0)),
                ('loan_deductions', models.JSONField(default=list, help_text='[{"loan_id": "...", "amount": 0, "remaining": 0}]')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='bank', max_length=20)),
                ('bank_details', models.JSONField(blank=True, default=dict)),
                ('payslip_url', models.URLField(blank=True, max_length=500)),
                ('payslip_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='tenants.tenant')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payroll_entries',
            },
        ),
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_audit_logs', to='tenants.tenant')),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payroll_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('components', models.JSONField(default=list, help_text='[{"name":"...", "type":"earning|deduction", "calc_type":"fixed|percentage|formula", "value": 0, "basis":"basic|gross"}]')),
                ('applicable_grades', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='core_hr.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='tenants.tenant')),
            ],
            options={
                'db_table': 'salary_structures',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('components', models.JSONField(blank=True, default=list, help_text='Per-employee overrides')),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('bi_weekly', 'Bi-weekly'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('bank_details', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_compensations', to='tenants.tenant')),
                ('salary_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'employee_compensations',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=3)),
                ('rule_type', models.CharField(choices=[('epf_employee', 'EPF Employee'), ('epf_employer', 'EPF Employer'), ('etf', 'ETF'), ('income_tax', 'Income Tax'), ('gratuity', 'Gratuity')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('calculation', models.JSONField(help_text='{"type": "percentage|slab", "rate": 0.08, "slabs": [{"from":0, "to":..., "rate":...}]}')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'statutory_rules',
                'ordering': ['country', 'rule_type', '-effective_from'],
                'indexes': [models.Index(fields=['country', 'rule_type', 'effective_from'], name='idx_statutory_country')],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('tenant', 'company', 'period_year', 'period_month'), name='unique_payroll_period'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['tenant', 'employee'], name='idx_payentry_emp'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='unique_payroll_entry'),
        ),
        migrations.AddIndex(
            model_name='payrollauditlog',
            index=models.Index(fields=['payroll_run', 'created_at'], name='idx_payaudit_run'),
        ),
        migrations.AddIndex(
            model_name='employeecompensation',
            index=models.Index(fields=['employee', '-effective_date'], name='idx_comp_emp_date'),
        ),
    ]
