# Generated by Django 5.2.11 on 2026-03-06 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignEmploymentAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_si', models.CharField(blank=True, default='', max_length=200)),
                ('name_ta', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_valid_until', models.DateField(blank=True, null=True)),
                ('is_slbfe_registered', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('countries_served', models.JSONField(blank=True, default=list)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Foreign employment agencies',
                'db_table': 'jf_foreign_agencies',
            },
        ),
        migrations.CreateModel(
            name='PreDepartureChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('title_si', models.CharField(blank=True, default='', max_length=200)),
                ('title_ta', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('description_si', models.TextField(blank=True, default='')),
                ('description_ta', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'jf_predeparture_checklist',
                'ordering': ['country', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OverseasJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('title_si', models.CharField(blank=True, default='', max_length=200)),
                ('title_ta', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('description_si', models.TextField(blank=True, default='')),
                ('description_ta', models.TextField(blank=True, default='')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('contract_duration_months', models.IntegerField(blank=True, null=True)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('vacancies', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], default='active', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('slbfe_approval_no', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='foreign_employment.foreignemploymentagency')),
            ],
            options={
                'db_table': 'jf_overseas_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
