# Generated by Django 5.2.11 on 2026-03-06 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('job', 'Job Listing'), ('review', 'Review'), ('message', 'Message'), ('employer', 'Employer'), ('seeker', 'Seeker')], max_length=10)),
                ('content_id', models.UUIDField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('fake', 'Fake Listing'), ('inappropriate', 'Inappropriate Content'), ('scam', 'Potential Scam'), ('harassment', 'Harassment'), ('discrimination', 'Discrimination'), ('misleading', 'Misleading Information'), ('other', 'Other')], max_length=15)),
                ('description', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('suspend', 'Suspended'), ('ban', 'Banned'), ('warn', 'Warning Issued'), ('remove', 'Content Removed'), ('restore', 'Content Restored')], max_length=10)),
                ('target_type', models.CharField(max_length=10)),
                ('target_id', models.UUIDField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='moderation.report')),
            ],
            options={
                'db_table': 'jf_moderation_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannedEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('ip', 'IP'), ('domain', 'Domain'), ('email', 'Email')], max_length=10)),
                ('entity_value', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_banned_entities',
                'indexes': [models.Index(fields=['entity_type', 'entity_value'], name='idx_banned_entity')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='idx_report_status'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'content_id'], name='idx_report_content'),
        ),
    ]
