# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('agency_crm', '0001_initial'),
        ('job_orders', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('contract', 'Contract'), ('temp', 'Temporary'), ('temp_to_perm', 'Temp to Perm'), ('interim', 'Interim'), ('project', 'Project-Based')], default='contract', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Start'), ('active', 'Active'), ('on_hold', 'On Hold'), ('extended', 'Extended'), ('ending_soon', 'Ending Soon'), ('ended', 'Ended'), ('terminated_early', 'Terminated Early'), ('converted', 'Converted to Perm')], default='pending', max_length=30)),
                ('start_date', models.DateField()),
                ('original_end_date', models.DateField(blank=True, null=True)),
                ('current_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('worksite_name', models.CharField(blank=True, max_length=200)),
                ('worksite_address', models.TextField(blank=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=200)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('pay_rate_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill_rate_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('markup_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overtime_bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extension_count', models.IntegerField(default=0)),
                ('is_conversion_eligible', models.BooleanField(default=False)),
                ('conversion_fee_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('early_termination_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='agencies.agency')),
                ('assigned_recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_assignments', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='submissions.candidateprofile')),
                ('client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='agency_crm.clientaccount')),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='job_orders.joborder')),
                ('placement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='agencies.agencyplacement')),
                ('supervisor_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_assignments', to='agency_crm.clientcontact')),
            ],
            options={
                'db_table': 'cop_assignment',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_end_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('new_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('pending_client', 'Pending Client Approval'), ('pending_candidate', 'Pending Candidate Acceptance'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='proposed', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extensions', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='contractor_ops.assignment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cop_extension',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='contractor_ops.assignment')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cop_incident',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('satisfaction_score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('check_in_date', models.DateTimeField()),
                ('next_check_in_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='contractor_ops.assignment')),
                ('checked_in_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cop_check_in',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id', 'Government ID'), ('work_permit', 'Work Permit / Visa'), ('contract', 'Assignment Contract'), ('nda', 'NDA'), ('background_check', 'Background Check'), ('drug_screen', 'Drug Screen'), ('certificate', 'Certificate / License'), ('insurance', 'Insurance Certificate'), ('policy_ack', 'Policy Acknowledgement'), ('safety_training', 'Safety Training'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Collection'), ('collected', 'Collected'), ('verified', 'Verified'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contractor_ops.assignment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cop_contractor_document',
            },
        ),
    ]
