# Generated by Django 5.2.11 on 2026-02-28 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_scimconfiguration_scimsynclog_ssoconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False, help_text='Visible to all users in tenant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dashboards', to='tenants.tenant')),
            ],
            options={
                'db_table': 'custom_dashboards',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('widget_type', models.CharField(choices=[('kpi', 'KPI Card'), ('chart_line', 'Line Chart'), ('chart_bar', 'Bar Chart'), ('chart_pie', 'Pie Chart'), ('chart_donut', 'Donut Chart'), ('table', 'Data Table'), ('gauge', 'Gauge'), ('heatmap', 'Heatmap'), ('trend', 'Trend Sparkline')], max_length=20)),
                ('data_source', models.CharField(choices=[('employees', 'Employee Data'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('performance', 'Performance'), ('helpdesk', 'Helpdesk'), ('engagement', 'Engagement'), ('custom', 'Custom Query')], max_length=30)),
                ('config', models.JSONField(default=dict, help_text='\n        {"metric":"count","group_by":"department","filter":{"status":"active"},\n         "time_range":"last_30_days","color":"#6366f1"}\n    ')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=4, help_text='Grid columns (1-12)')),
                ('height', models.IntegerField(default=2, help_text='Grid rows')),
                ('refresh_interval', models.IntegerField(default=300, help_text='Seconds between auto-refresh')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.customdashboard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
    ]
