# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0008_candidatefollowuptask_candidateoutreachlog_and_more'),
        ('jobs', '0005_job_degree_optional_note_job_degree_required_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger_event', models.CharField(default='hired', help_text='e.g. hired, passed_day_90, passed_probation', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('department_filter', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'bonus_rules',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referrer_email', models.EmailField(blank=True, default='', help_text='For alumni / external referrers', max_length=254)),
                ('referrer_name', models.CharField(blank=True, default='', max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('hired', 'Hired'), ('not_hired', 'Not Hired'), ('pending_payout', 'Pending Payout'), ('paid', 'Paid')], default='submitted', max_length=20)),
                ('referral_note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='candidates.candidate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='jobs.job')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_referrals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_payouts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_payouts', to='tenants.tenant')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='referrals.bonusrule')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='referrals.referral')),
            ],
            options={
                'db_table': 'bonus_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('paused', 'Paused')], default='active', max_length=20)),
                ('target_jobs', models.JSONField(blank=True, default=list, help_text='List of Job UUIDs for this campaign')),
                ('bonus_multiplier', models.FloatField(default=1.0, help_text='Multiplier on top of base BonusRule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_campaigns', to='tenants.tenant')),
            ],
            options={
                'db_table': 'referral_campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='referrals.referralcampaign'),
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_alumni', models.BooleanField(default=False, help_text='Allow former employees to refer')),
                ('allow_external', models.BooleanField(default=False, help_text='Allow non-employees to refer')),
                ('bonus_currency', models.CharField(default='USD', max_length=3)),
                ('terms_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_programs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'referral_programs',
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('click_count', models.IntegerField(default=0)),
                ('conversion_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_links', to='jobs.job')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='tenants.tenant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='referrals.referralprogram')),
            ],
            options={
                'db_table': 'referral_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly'), ('quarter', 'Quarterly'), ('all_time', 'All Time')], default='month', max_length=20)),
                ('period_start', models.DateField()),
                ('rankings', models.JSONField(default=list, help_text="[{'user_id': ..., 'name': ..., 'referrals': 5, 'hires': 2}]")),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_leaderboards', to='tenants.tenant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='referrals.referralprogram')),
            ],
            options={
                'db_table': 'referral_leaderboards',
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddField(
            model_name='referralcampaign',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='referrals.referralprogram'),
        ),
        migrations.AddField(
            model_name='referral',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='referrals.referralprogram'),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='referrals.referralprogram'),
        ),
    ]
