# Generated by Django 5.2.11 on 2026-03-06 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_name_si', models.CharField(blank=True, default='', max_length=200)),
                ('company_name_ta', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='company_covers/')),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('description_si', models.TextField(blank=True, default='')),
                ('description_ta', models.TextField(blank=True, default='')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1–10'), ('11-50', '11–50'), ('51-200', '51–200'), ('201-500', '201–500'), ('501-1000', '501–1000'), ('1001-5000', '1001–5000'), ('5000+', '5000+')], default='', max_length=10)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('registration_no', models.CharField(blank=True, default='', max_length=50)),
                ('tax_id', models.CharField(blank=True, default='', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_badge', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('premium', 'Premium'), ('government', 'Government')], default='none', max_length=10)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('facebook_url', models.URLField(blank=True, default='', max_length=500)),
                ('twitter_url', models.URLField(blank=True, default='', max_length=500)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('agency', 'Agency')], default='free', max_length=15)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('monthly_job_limit', models.IntegerField(default=3)),
                ('resume_db_access', models.BooleanField(default=False)),
                ('active_job_count', models.IntegerField(default=0)),
                ('ats_connected', models.BooleanField(default=False)),
                ('ats_tenant_slug', models.CharField(blank=True, default='', max_length=100)),
                ('ats_api_key_encrypted', models.TextField(blank=True, default='')),
                ('ats_webhook_secret_encrypted', models.TextField(blank=True, default='')),
                ('ats_sync_enabled', models.BooleanField(default=False)),
                ('ats_last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headquarters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.district')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.industry')),
            ],
            options={
                'db_table': 'jf_employer_accounts',
            },
        ),
        migrations.CreateModel(
            name='CareerSitePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('primary_color', models.CharField(default='#2563eb', max_length=10)),
                ('sections', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_site', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_career_site_pages',
            },
        ),
        migrations.CreateModel(
            name='EmployerBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7)),
                ('banner_images', models.JSONField(blank=True, default=list)),
                ('employee_testimonials', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('office_photos', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, default='', max_length=500)),
                ('culture_keywords', models.JSONField(blank=True, default=list)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_employer_branding',
            },
        ),
        migrations.CreateModel(
            name='InterviewDebrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('consensus', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debriefs', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_interview_debriefs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DebriefFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interviewer_name', models.CharField(max_length=200)),
                ('interviewer_role', models.CharField(blank=True, default='', max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('recommendation', models.CharField(default='Pending', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('debrief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='employers.interviewdebrief')),
            ],
            options={
                'db_table': 'jf_debrief_feedback',
            },
        ),
        migrations.CreateModel(
            name='InterviewKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('scoring_criteria', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_kits', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_interview_kits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('expected_answer', models.TextField(blank=True, default='')),
                ('max_score', models.IntegerField(default=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='employers.interviewkit')),
            ],
            options={
                'db_table': 'jf_interview_questions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('level', models.CharField(blank=True, default='', max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_job_descriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('role_interest', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('engaged', 'Engaged'), ('qualified', 'Qualified'), ('pipeline', 'Pipeline')], default='new', max_length=15)),
                ('skills', models.JSONField(default=list)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.district')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contacts', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_recruiter_contacts',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('reward_amount', models.IntegerField(default=0)),
                ('reward_currency', models.CharField(default='LKR', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_campaigns', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_referral_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='employers.referralcampaign')),
            ],
            options={
                'db_table': 'jf_referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_comp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='LKR', max_length=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_reports', to='employers.employeraccount')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_salary_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SilverMedalist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('original_role', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('skills', models.JSONField(default=list)),
                ('recruiter_notes', models.TextField(blank=True, default='')),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_medalists', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_silver_medalists',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='EmployerFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='employers.employeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_employers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_employer_follows',
                'unique_together': {('employer', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EmployerTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('recruiter', 'Recruiter'), ('viewer', 'Viewer')], default='recruiter', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='employers.employeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_employer_team_members',
                'unique_together': {('employer', 'user')},
            },
        ),
    ]
