# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('contractor_ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_invoiceable', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='agencies.agency')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='contractor_ops.assignment')),
            ],
            options={
                'db_table': 'ts_expense_report',
            },
        ),
        migrations.CreateModel(
            name='ExpenseLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('mileage', 'Mileage'), ('accommodation', 'Accommodation'), ('meals', 'Meals & Entertainment'), ('equipment', 'Equipment'), ('communication', 'Communication'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('expense_date', models.DateField()),
                ('receipt_url', models.URLField(blank=True)),
                ('mileage_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_invoiceable', models.BooleanField(default=True)),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='timesheets.expensereport')),
            ],
            options={
                'db_table': 'ts_expense_line',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('supervisor_approved', 'Supervisor Approved'), ('client_approved', 'Client Approved'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('exported', 'Exported to Payroll')], default='draft', max_length=30)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('double_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('shift_differential_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('gross_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gross_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gross_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('client_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('payroll_exported_at', models.DateTimeField(blank=True, null=True)),
                ('billing_exported_at', models.DateTimeField(blank=True, null=True)),
                ('payroll_reference', models.CharField(blank=True, max_length=100)),
                ('billing_reference', models.CharField(blank=True, max_length=100)),
                ('worker_notes', models.TextField(blank=True)),
                ('approver_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='agencies.agency')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='contractor_ops.assignment')),
                ('client_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_approved_ts', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_ts', to=settings.AUTH_USER_MODEL)),
                ('supervisor_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_approved_ts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ts_timesheet',
                'ordering': ['-period__start_date'],
            },
        ),
        migrations.AddField(
            model_name='expensereport',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='timesheets.timesheet'),
        ),
        migrations.CreateModel(
            name='TimesheetPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_periods', to='agencies.agency')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ts_period',
                'ordering': ['-start_date'],
                'unique_together': {('agency', 'start_date', 'end_date')},
            },
        ),
        migrations.AddField(
            model_name='timesheet',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='timesheets.timesheetperiod'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='timesheets.timesheetperiod'),
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('shift_differential', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheets.timesheet')),
            ],
            options={
                'db_table': 'ts_entry',
                'ordering': ['work_date'],
                'unique_together': {('timesheet', 'work_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('assignment', 'period')},
        ),
    ]
