# Generated by Django 5.2.11 on 2026-02-25 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('candidates', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'activity_logs',
                'indexes': [models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='activity_lo_tenant__b35749_idx'), models.Index(fields=['tenant', 'created_at'], name='activity_lo_tenant__509b6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(help_text='Template body with {{variable}} placeholders')),
                ('category', models.CharField(choices=[('application', 'Application'), ('interview', 'Interview'), ('rejection', 'Rejection'), ('offer', 'Offer'), ('reminder', 'Reminder'), ('general', 'General')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'email_templates',
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS')], default='email', max_length=10)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('bounced', 'Bounced')], default='queued', max_length=20)),
                ('provider_id', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='candidates.candidate')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tenants.tenant')),
            ],
            options={
                'db_table': 'messages',
                'indexes': [models.Index(fields=['tenant', 'candidate', 'created_at'], name='messages_tenant__f498eb_idx'), models.Index(fields=['tenant', 'status'], name='messages_tenant__e763e9_idx')],
            },
        ),
    ]
