# Generated by Django 5.2.11 on 2026-02-27 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_employee_interviewpanel_interviewscorecard_and_more'),
        ('candidates', '0002_candidatecertification_candidatenote_and_more'),
        ('messaging', '0001_initial'),
        ('tenants', '0002_tenantsettings_api_rate_limit_per_minute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Send at this time instead of immediately', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='messaging.emailtemplate'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups emails into conversation threads', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tracking_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(choices=[('application', 'Application'), ('interview', 'Interview'), ('rejection', 'Rejection'), ('offer', 'Offer'), ('reminder', 'Reminder'), ('follow_up', 'Follow-up'), ('acknowledgment', 'Acknowledgment'), ('onboarding', 'Onboarding'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('opened', 'Opened')], default='queued', max_length=20),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant', 'actor', 'created_at'], name='activity_lo_tenant__b9b75a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant', 'thread_id'], name='messages_tenant__374648_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant', 'scheduled_for'], name='messages_tenant__262dbb_idx'),
        ),
    ]
