# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidatefollowuptask_candidateoutreachlog_and_more'),
        ('messaging', '0003_offer_letter_template'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('segment_query', models.JSONField(blank=True, default=dict, help_text='{"pool_status": "active", "talent_tier": "gold", "skills": [...]}')),
                ('recipient_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bulk_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationPreferenceCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_job_alerts', models.BooleanField(default=True)),
                ('email_application_updates', models.BooleanField(default=True)),
                ('email_nurture', models.BooleanField(default=False)),
                ('sms_interview_reminders', models.BooleanField(default=False)),
                ('sms_offers', models.BooleanField(default=False)),
                ('global_opt_out', models.BooleanField(default=False, help_text='Opted out of all communications')),
                ('opt_out_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communication_preferences',
            },
        ),
        migrations.CreateModel(
            name='NurtureEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('exited', 'Exited'), ('paused', 'Paused')], default='active', max_length=20)),
                ('exit_reason', models.CharField(blank=True, default='', max_length=50)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nurture_enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='NurtureSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('exit_on_reply', models.BooleanField(default=True, help_text='Stop sequence if candidate replies')),
                ('exit_on_apply', models.BooleanField(default=True, help_text='Stop sequence if candidate applies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nurture_sequences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NurtureStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField(default=1)),
                ('delay_days', models.IntegerField(default=0, help_text='Days after previous step (or enrollment for step 1)')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nurture_steps',
                'ordering': ['sequence', 'step_order'],
            },
        ),
        migrations.RenameIndex(
            model_name='offerlettertemplate',
            new_name='offer_lette_tenant__3b5185_idx',
            old_name='offer_tmpl_tenant_default_idx',
        ),
        migrations.RenameIndex(
            model_name='offerlettertemplate',
            new_name='offer_lette_tenant__05ab32_idx',
            old_name='offer_tmpl_tenant_active_idx',
        ),
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='name',
            field=models.CharField(help_text="Internal template name (e.g. 'Standard Offer – Engineering')", max_length=200),
        ),
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='slug',
            field=models.CharField(help_text='Machine-readable identifier, unique per tenant', max_length=100),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_campaigns', to='messaging.emailtemplate'),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_campaigns', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='communicationpreferencecenter',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comm_preferences', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='communicationpreferencecenter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_preferences', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nurtureenrollment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurture_enrollments', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='nurtureenrollment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurture_enrollments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nurturesequence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sequences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurturesequence',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurture_sequences', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nurtureenrollment',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='messaging.nurturesequence'),
        ),
        migrations.AddField(
            model_name='nurturestep',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='messaging.nurturesequence'),
        ),
        migrations.AddField(
            model_name='nurturestep',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurture_steps', to='messaging.emailtemplate'),
        ),
        migrations.AddIndex(
            model_name='bulkcampaign',
            index=models.Index(fields=['tenant', 'status'], name='bulk_campai_tenant__ca7341_idx'),
        ),
        migrations.AddIndex(
            model_name='nurtureenrollment',
            index=models.Index(fields=['tenant', 'status', 'next_send_at'], name='nurture_enr_tenant__f2179d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nurtureenrollment',
            unique_together={('sequence', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='nurturestep',
            unique_together={('sequence', 'step_order')},
        ),
    ]
