# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('agency_crm', '0001_initial'),
        ('contractor_ops', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('criminal', 'Criminal History'), ('credit', 'Credit Check'), ('employment', 'Employment Verification'), ('education', 'Education Verification'), ('reference', 'Reference Check'), ('drug_screen', 'Drug Screen'), ('global_watch', 'Global Watchlist'), ('right_to_work', 'Right to Work')], max_length=30)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('clear', 'Clear'), ('consider', 'Consider (Review Required)'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('report_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to='agencies.agency')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to='submissions.candidateprofile')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compl_background_check',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='CompliancePack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pack_type', models.CharField(choices=[('general', 'General'), ('healthcare', 'Healthcare'), ('trades', 'Skilled Trades'), ('it', 'IT / Technology'), ('finance', 'Finance / Banking'), ('education', 'Education'), ('executive', 'Executive Search'), ('custom', 'Custom')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('required_document_types', models.JSONField(default=list)),
                ('required_checks', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_packs', to='agencies.agency')),
                ('client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_packs', to='agency_crm.clientaccount')),
            ],
            options={
                'db_table': 'compl_pack',
            },
        ),
        migrations.CreateModel(
            name='ComplianceChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('failed', 'Failed / Non-Compliant'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checklists', to='agencies.agency')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checklists', to='contractor_ops.assignment')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checklists', to='submissions.candidateprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checklists', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='agency_compliance.compliancepack')),
            ],
            options={
                'db_table': 'compl_checklist',
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('data_processing', 'Data Processing Consent'), ('marketing', 'Marketing / Outreach'), ('right_to_represent', 'Right to Represent'), ('background_check', 'Background Check Consent'), ('terms', 'Terms & Conditions'), ('privacy_policy', 'Privacy Policy')], max_length=30)),
                ('granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(choices=[('email', 'Email'), ('portal', 'Portal'), ('verbal', 'Verbal'), ('form', 'Form')], default='portal', max_length=30)),
                ('document_version', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='agencies.agency')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='submissions.candidateprofile')),
            ],
            options={
                'db_table': 'compl_consent_log',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(choices=[('license', 'Professional License'), ('certification', 'Certification'), ('degree', 'Academic Degree'), ('safety_cert', 'Safety Certificate'), ('insurance', 'Insurance / Indemnity'), ('membership', 'Professional Membership'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('credential_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('pending_renewal', 'Pending Renewal'), ('revoked', 'Revoked')], default='active', max_length=30)),
                ('document_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='submissions.candidateprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_creds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compl_credential',
                'ordering': ['expiry_date'],
            },
        ),
    ]
