# Generated by Django 5.2.11 on 2026-02-28 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0001_initial'),
        ('tenants', '0002_scimconfiguration_scimsynclog_ssoconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('kudos', 'Kudos'), ('shoutout', 'Shoutout'), ('award', 'Award'), ('milestone', 'Milestone'), ('innovation', 'Innovation')], default='kudos', max_length=50)),
                ('message', models.TextField()),
                ('badges', models.JSONField(blank=True, default=list, help_text='["teamwork","leadership","innovation"]')),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_given', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_entries', to='tenants.tenant')),
                ('to_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_received', to='core_hr.employee')),
            ],
            options={
                'db_table': 'recognition_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('pulse', 'Pulse Survey'), ('engagement', 'Engagement Survey'), ('enps', 'eNPS Survey'), ('exit', 'Exit Survey'), ('onboarding', 'Onboarding Survey')], default='pulse', max_length=30)),
                ('questions', models.JSONField(default=list, help_text='[{"id":"q1","text":"...","type":"rating|text|choice|nps","options":["..."]}]')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('target_audience', models.JSONField(blank=True, default=dict, help_text='{"departments":[],"branches":[],"all":true}')),
                ('anonymous', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_surveys', to='tenants.tenant')),
            ],
            options={
                'db_table': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict, help_text='{"q1": 4, "q2": "Great culture"}')),
                ('nps_score', models.IntegerField(blank=True, help_text='0-10 eNPS score', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='core_hr.employee')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='engagement.survey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='tenants.tenant')),
            ],
            options={
                'db_table': 'survey_responses',
                'constraints': [models.UniqueConstraint(fields=('survey', 'employee'), name='unique_survey_response')],
            },
        ),
    ]
