# Generated by Django 5.2.11 on 2026-03-07 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0005_criticalrole_internalmobilityprofile'),
        ('engagement', '0001_initial'),
        ('tenants', '0003_billing_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleSurveyTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_event', models.CharField(choices=[('hire', 'On Hire'), ('onboarding_complete', 'Onboarding Complete'), ('probation_end', 'Probation End'), ('anniversary', 'Work Anniversary'), ('promotion', 'Promotion'), ('transfer', 'Transfer'), ('manager_change', 'Manager Change'), ('offboarding_start', 'Offboarding Start'), ('exit', 'Exit')], max_length=50)),
                ('delay_days', models.IntegerField(default=0, help_text='Days after trigger event before sending survey')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_triggers', to='engagement.survey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_survey_triggers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'lifecycle_survey_triggers',
                'ordering': ['trigger_event'],
            },
        ),
        migrations.CreateModel(
            name='ManagerActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('focus_area', models.CharField(blank=True, help_text="e.g. 'Communication', 'Recognition', 'Work-Life Balance'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='core_hr.employee')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='engagement.survey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_action_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'manager_action_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='core_hr.employee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='engagement.manageractionplan')),
            ],
            options={
                'db_table': 'manager_action_items',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='StayInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('conducted_date', models.DateField(blank=True, null=True)),
                ('stay_factors', models.JSONField(blank=True, default=list, help_text='["growth","team","compensation","flexibility"]')),
                ('leave_risks', models.JSONField(blank=True, default=list, help_text='["limited_growth","commute","workload"]')),
                ('key_notes', models.TextField(blank=True)),
                ('follow_up_actions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_interviews', to='core_hr.employee')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_stay_interviews', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_interviews', to='tenants.tenant')),
            ],
            options={
                'db_table': 'stay_interviews',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
