# Generated by Django 5.2.11 on 2026-03-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apply_method_used',
            field=models.CharField(blank=True, choices=[('quick_apply', 'Quick Apply'), ('full_profile', 'Full Profile'), ('resume_upload', 'Resume Upload'), ('external', 'External')], default='full_profile', help_text='Which apply flow the seeker used', max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='autofill_used',
            field=models.BooleanField(default=False, help_text='Was autofill used to populate the application?'),
        ),
        migrations.AddField(
            model_name='application',
            name='completion_percentage',
            field=models.IntegerField(default=100, help_text='Application completeness (0-100%)'),
        ),
        migrations.AddField(
            model_name='application',
            name='external_apply_tracked',
            field=models.BooleanField(default=False, help_text='Tracked external redirect to employer site'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Saved-draft not yet submitted'),
        ),
    ]
