# Generated by Django 5.2.11 on 2026-03-08 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_apply_method_used_and_more'),
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='applications.application')),
            ],
            options={
                'db_table': 'jf_application_tasks',
                'ordering': ['sort_order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchApplySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_ids', models.JSONField(default=list, help_text='List of JobListing UUIDs in this batch')),
                ('applied_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('cover_letter_used', models.TextField(blank=True, default='')),
                ('resume_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_apply_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_batch_apply_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalApplicationTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer Received'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=15)),
                ('applied_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employers.employeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_external_application_tracker',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpNudge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nudge_type', models.CharField(choices=[('incomplete_draft', 'Finish Incomplete Application'), ('no_response', 'Follow Up — No Response'), ('interview_prep', 'Interview Preparation Reminder'), ('offer_expiring', 'Offer Expiring Soon'), ('weekly_update', 'Weekly Application Update')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='applications.application')),
            ],
            options={
                'db_table': 'jf_follow_up_nudges',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(choices=[('accepted_other_offer', 'Accepted Another Offer'), ('salary_mismatch', 'Salary Not Matching'), ('role_not_right', 'Role Not Right Fit'), ('no_response', 'Employer Not Responding'), ('location_issue', 'Location / Commute Issue'), ('company_concerns', 'Concerns About Company'), ('still_exploring', 'Still Exploring Options'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_reason', to='applications.application')),
            ],
            options={
                'db_table': 'jf_withdrawal_reasons',
            },
        ),
    ]
