# Generated by Django 5.2.11 on 2026-02-26 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('video', 'Video'), ('phone', 'Phone'), ('onsite', 'On-site'), ('take_home', 'Take Home')], default='video', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(default=45, help_text='Duration in minutes')),
                ('interviewer_name', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
                ('rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.candidate')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='tenants.tenant')),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='interviews_tenant__199d32_idx'), models.Index(fields=['tenant', 'candidate'], name='interviews_tenant__ce1499_idx'), models.Index(fields=['tenant', 'status'], name='interviews_tenant__be035f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, default='')),
                ('equity', models.CharField(blank=True, default='', max_length=200)),
                ('signing_bonus', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='applications.application')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offers', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='offers_tenant__15cb91_idx'), models.Index(fields=['tenant', 'candidate'], name='offers_tenant__50a824_idx')],
            },
        ),
    ]
