# Generated by Django 5.2.11 on 2026-02-27 04:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_interview_offer'),
        ('candidates', '0002_candidatecertification_candidatenote_and_more'),
        ('jobs', '0002_jobtemplate_job_application_deadline_and_more'),
        ('tenants', '0002_tenantsettings_api_rate_limit_per_minute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, default='', help_text='Internal employee ID', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('probation', 'Probation'), ('active', 'Active'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], default='onboarding', max_length=20)),
                ('goals_30', models.JSONField(blank=True, default=list)),
                ('goals_60', models.JSONField(blank=True, default=list)),
                ('goals_90', models.JSONField(blank=True, default=list)),
                ('satisfaction_score', models.IntegerField(blank=True, help_text='1-5 from 30-day survey', null=True)),
                ('hiring_quality_score', models.IntegerField(blank=True, help_text='1-5 rated 6 months after hire', null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, default='')),
                ('exit_interview_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Feedback'), ('submitted', 'Feedback Submitted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, default='')),
                ('rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_panels',
            },
        ),
        migrations.CreateModel(
            name='InterviewScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria_name', models.CharField(help_text='Communication, Technical Skills, Problem Solving, Culture Fit', max_length=100)),
                ('rating', models.IntegerField(help_text='1-5 rating')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'interview_scorecards',
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('it', 'IT Setup'), ('hr', 'HR/Admin'), ('training', 'Training'), ('equipment', 'Equipment'), ('intro', 'Introductions'), ('other', 'Other')], default='other', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'onboarding_tasks',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='hold_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Starred/pinned application'),
        ),
        migrations.AddField(
            model_name='application',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('unqualified', 'Unqualified'), ('salary_mismatch', 'Salary Mismatch'), ('no_show', 'No Show'), ('culture_fit', 'Culture Fit'), ('position_filled', 'Position Filled'), ('overqualified', 'Overqualified'), ('insufficient_experience', 'Insufficient Experience'), ('failed_assessment', 'Failed Assessment'), ('candidate_withdrew', 'Candidate Withdrew'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_checklist_completed',
            field=models.JSONField(blank=True, default=dict, help_text='{"stage_id": ["item1_done", "item2_done"]}'),
        ),
        migrations.AddField(
            model_name='interview',
            name='decision',
            field=models.CharField(blank=True, default='', help_text='advance, reject, hold — set by hiring manager after feedback', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='no_show_by',
            field=models.CharField(blank=True, default='', help_text='candidate or interviewer', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='reschedule_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='round_name',
            field=models.CharField(blank=True, default='', help_text='Phone Screen, Technical, Culture Fit', max_length=100),
        ),
        migrations.AddField(
            model_name='interview',
            name='round_number',
            field=models.IntegerField(default=1, help_text='Interview round (1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='approval_chain',
            field=models.JSONField(blank=True, default=list, help_text='[{"level": "manager", "user_id": "...", "status": "approved"}]'),
        ),
        migrations.AddField(
            model_name='offer',
            name='background_check_status',
            field=models.CharField(blank=True, default='', help_text='pending, in_progress, cleared, failed', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='bonus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='decline_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='decline_reason',
            field=models.CharField(blank=True, choices=[('better_offer', 'Better Offer Elsewhere'), ('salary_too_low', 'Salary Too Low'), ('relocation', 'Relocation Issues'), ('counter_offer', 'Counter-offer from Current Employer'), ('personal', 'Personal Reasons'), ('role_mismatch', 'Role Not as Expected'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='negotiation_history',
            field=models.JSONField(blank=True, default=list, help_text='[{"round": 1, "offered": 150000, "counter": 165000, "date": "..."}]'),
        ),
        migrations.AddField(
            model_name='offer',
            name='salary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='salary_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='offer',
            name='total_compensation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='verbal_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='duration_hours',
            field=models.FloatField(blank=True, help_text='Hours spent in previous stage', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tenant', 'is_priority'], name='application_tenant__d758f1_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['tenant', 'interviewer'], name='interviews_tenant__054dfe_idx'),
        ),
        migrations.AddField(
            model_name='employee',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to='applications.application'),
        ),
        migrations.AddField(
            model_name='employee',
            name='buddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_record', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='interviewpanel',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_members', to='applications.interview'),
        ),
        migrations.AddField(
            model_name='interviewpanel',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_panels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewpanel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='interviewscorecard',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='applications.interviewpanel'),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='applications.employee'),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'status'], name='employees_tenant__f0cde0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'department'], name='employees_tenant__ac492f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewpanel',
            unique_together={('interview', 'interviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='interviewscorecard',
            unique_together={('panel', 'criteria_name')},
        ),
    ]
