# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_offer_hrm_employee_fields'),
        ('jobs', '0004_alter_job_options'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='esign_document_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='esign_envelope_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='esign_provider',
            field=models.CharField(blank=True, default='', help_text='docusign, hellosign, adobe_sign, internal', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='esign_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CalibrationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('criteria_discussed', models.JSONField(blank=True, default=list, help_text='[{"criterion": "Technical", "agreed_weight": 0.4, "notes": "..."}]')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_sessions', to='jobs.job')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_calibrations', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='calibration_participants', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_sessions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'calibration_sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='HiringManagerNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_visible_to_recruiter', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hm_notes', to='applications.application')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hm_application_notes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hm_notes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hiring_manager_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('supporting_evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('upheld', 'Upheld — Decision Reversed'), ('dismissed', 'Dismissed — Original Decision Stands')], default='open', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ai_decision_overridden', models.BooleanField(default=False)),
                ('override_justification', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='applications.application')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_appeals', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_appeals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'application_appeals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='application_tenant__d1ce02_idx'), models.Index(fields=['tenant', 'application'], name='application_tenant__b30a23_idx')],
            },
        ),
        migrations.CreateModel(
            name='DebriefSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('decision', models.CharField(choices=[('advance', 'Advance'), ('reject', 'Reject'), ('hold', 'Hold'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debrief_sessions', to='applications.application')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_debriefs', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='debrief_participants', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debrief_sessions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'debrief_sessions',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['tenant', 'application'], name='debrief_ses_tenant__8fa4da_idx')],
            },
        ),
    ]
