# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('agency_crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('internal_ref', models.CharField(blank=True, max_length=100)),
                ('client_ref', models.CharField(blank=True, max_length=100)),
                ('staffing_type', models.CharField(choices=[('perm', 'Permanent'), ('contract', 'Contract'), ('temp', 'Temporary'), ('temp_to_perm', 'Temp to Perm'), ('retained', 'Retained Search'), ('executive', 'Executive Search'), ('project', 'Project-Based'), ('interim', 'Interim Management')], default='perm', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('filled', 'Filled'), ('partial_fill', 'Partially Filled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('exclusivity', models.CharField(choices=[('contingency', 'Contingency (Non-exclusive)'), ('exclusive', 'Exclusive'), ('retained', 'Retained'), ('preferred', 'Preferred Supplier')], default='contingency', max_length=20)),
                ('positions_count', models.IntegerField(default=1)),
                ('filled_count', models.IntegerField(default=0)),
                ('submittal_limit', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(default=list)),
                ('credential_requirements', models.JSONField(default=list)),
                ('compliance_requirements', models.JSONField(default=list)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_hybrid', models.BooleanField(default=False)),
                ('worksite_details', models.TextField(blank=True)),
                ('shift_details', models.TextField(blank=True)),
                ('hours_per_week', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bill_rate_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_rate_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('markup_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gross_margin_preview', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perm_fee_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('guarantee_days', models.IntegerField(default=90)),
                ('replacement_policy', models.TextField(blank=True)),
                ('hiring_manager_name', models.CharField(blank=True, max_length=200)),
                ('hiring_manager_email', models.EmailField(blank=True, max_length=254)),
                ('subcontractor_allowed', models.BooleanField(default=False)),
                ('target_submit_date', models.DateField(blank=True, null=True)),
                ('target_fill_date', models.DateField(blank=True, null=True)),
                ('sla_days_to_submit', models.IntegerField(blank=True, null=True)),
                ('sla_days_to_fill', models.IntegerField(blank=True, null=True)),
                ('candidate_packaging_notes', models.TextField(blank=True)),
                ('intake_checklist', models.JSONField(default=dict)),
                ('intake_completed', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_clone', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='am_job_orders', to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_orders', to='agencies.agency')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_job_orders', to=settings.AUTH_USER_MODEL)),
                ('assigned_recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_job_orders', to=settings.AUTH_USER_MODEL)),
                ('client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='agency_crm.clientaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_orders', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='job_orders.joborder')),
                ('hiring_manager_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders_as_hm', to='agency_crm.clientcontact')),
                ('legacy_job_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_job_order', to='agencies.agencyjoborder')),
            ],
            options={
                'db_table': 'jo_job_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOrderNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jo_notes', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_set', to='job_orders.joborder')),
            ],
            options={
                'db_table': 'jo_job_order_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jo_status_changes', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='job_orders.joborder')),
            ],
            options={
                'db_table': 'jo_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
