# Generated by Django 5.2.11 on 2026-02-27 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('country', models.CharField(default='LKA', max_length=3)),
                ('applies_to', models.JSONField(blank=True, default=list, help_text='Branch IDs or empty for all')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_calendars', to='tenants.tenant')),
            ],
            options={
                'db_table': 'holiday_calendars',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('public', 'Public Holiday'), ('mercantile', 'Mercantile Holiday'), ('poya', 'Poya Day'), ('optional', 'Optional Holiday'), ('company', 'Company Holiday')], default='public', max_length=20)),
                ('is_optional', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='leave_attendance.holidaycalendar')),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('paid', models.BooleanField(default=True)),
                ('max_days_per_year', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('carry_forward', models.BooleanField(default=False)),
                ('max_carry_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('encashable', models.BooleanField(default=False)),
                ('accrual_type', models.CharField(choices=[('annual', 'Annual'), ('monthly', 'Monthly'), ('none', 'No Accrual')], default='annual', max_length=20)),
                ('applicable_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Leave blank for all genders', max_length=10)),
                ('probation_eligible', models.BooleanField(default=False)),
                ('min_service_months', models.IntegerField(default=0)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('allow_short_leave', models.BooleanField(default=False)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('requires_attachment_after_days', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='tenants.tenant')),
            ],
            options={
                'db_table': 'leave_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_multiplier', models.DecimalField(decimal_places=1, default=1.5, max_digits=3)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'overtime_records',
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.IntegerField(default=60)),
                ('grace_minutes', models.IntegerField(default=15)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('color', models.CharField(default='#10B981', max_length=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'shift_templates',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10)),
                ('is_short_leave', models.BooleanField(default=False)),
                ('short_leave_from', models.TimeField(blank=True, null=True)),
                ('short_leave_to', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='tenants.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leave_attendance.leavetype')),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'start_date'], name='idx_leave_emp_date'), models.Index(fields=['tenant', 'status'], name='idx_leave_status')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('entitled', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('taken', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('pending', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('adjustment', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='tenants.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave_attendance.leavetype')),
            ],
            options={
                'db_table': 'leave_balances',
                'unique_together': {('tenant', 'employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, help_text='Specific date; null if recurring', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='If true, repeats weekly')),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Mon, 6=Sun (for default shifts)', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='tenants.tenant')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='leave_attendance.shifttemplate')),
            ],
            options={
                'db_table': 'shift_assignments',
                'constraints': [models.UniqueConstraint(condition=models.Q(('date__isnull', False)), fields=('tenant', 'employee', 'date'), name='unique_shift_per_day')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('clock_in_source', models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('biometric', 'Biometric'), ('manual', 'Manual'), ('qr', 'QR Code')], max_length=20)),
                ('clock_out_source', models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('biometric', 'Biometric'), ('manual', 'Manual'), ('qr', 'QR Code')], max_length=20)),
                ('clock_in_location', models.JSONField(blank=True, help_text='{"lat": ..., "lng": ..., "address": ...}', null=True)),
                ('clock_out_location', models.JSONField(blank=True, null=True)),
                ('clock_in_photo_url', models.URLField(blank=True, max_length=500)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_minutes', models.IntegerField(default=0)),
                ('early_leave_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('holiday', 'Holiday'), ('leave', 'On Leave'), ('weekend', 'Weekend')], default='present', max_length=20)),
                ('exception_type', models.CharField(blank=True, choices=[('late', 'Late'), ('early_leave', 'Early Leave'), ('missing_punch', 'Missing Punch'), ('overtime', 'Overtime')], max_length=30)),
                ('regularized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core_hr.employee')),
                ('regularized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.tenant')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_attendance.shifttemplate')),
            ],
            options={
                'db_table': 'attendance_records',
                'indexes': [models.Index(fields=['tenant', 'employee', 'date'], name='idx_attend_emp_date'), models.Index(fields=['tenant', 'date', 'status'], name='idx_attend_date_status')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'employee', 'date'), name='unique_attendance_per_day')],
            },
        ),
    ]
