# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('announcement', 'Announcement'), ('recognition', 'Recognition'), ('birthday', 'Birthday'), ('anniversary', 'Work Anniversary'), ('new_joiner', 'New Joiner'), ('achievement', 'Achievement'), ('poll', 'Poll'), ('event', 'Event')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('audience_filter', models.JSONField(default=dict, help_text='{"departments":[],"grades":[],"all":true}')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_feed_items', to='core_hr.employee')),
                ('target_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items_about_me', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='tenants.tenant')),
            ],
            options={
                'db_table': 'employee_feed_items',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHubWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('leave_balance', 'Leave Balance'), ('attendance_summary', 'Attendance Summary'), ('payslips', 'Recent Payslips'), ('goals', 'My Goals'), ('tasks', 'My Tasks'), ('announcements', 'Announcements'), ('quick_links', 'Quick Links'), ('recognition', 'Recognition Feed'), ('upcoming_events', 'Upcoming Events'), ('org_chart', 'Team Org Chart'), ('learning', 'Learning Progress')], max_length=30)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=4)),
                ('height', models.IntegerField(default=2)),
                ('is_visible', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_widgets', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_widgets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'employee_hub_widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfileCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_pct', models.IntegerField(default=0)),
                ('section_scores', models.JSONField(default=dict, help_text='{"personal":100,"contact":80,"emergency":0,"bank":50,"documents":60}')),
                ('missing_fields', models.JSONField(default=list)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_completion', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_completions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'employee_profile_completions',
            },
        ),
        migrations.CreateModel(
            name='EmployeeQuickLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('icon', models.CharField(default='🔗', max_length=10)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('audience', models.JSONField(default=list, help_text='Department/grade filters; empty = all')),
                ('is_active', models.BooleanField(default=True)),
                ('opens_in_new_tab', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_quick_links', to='tenants.tenant')),
            ],
            options={
                'db_table': 'employee_quick_links',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SelfServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('employment_letter', 'Employment Letter'), ('salary_certificate', 'Salary Certificate'), ('experience_letter', 'Experience Letter'), ('noc_letter', 'No Objection Certificate'), ('bank_letter', 'Bank Confirmation Letter'), ('address_update', 'Address Update'), ('name_change', 'Name Change'), ('bank_details_update', 'Bank Details Update'), ('emergency_contact_update', 'Emergency Contact Update'), ('document_request', 'Document Request'), ('other', 'Other')], max_length=40)),
                ('subject', models.CharField(max_length=300)),
                ('details', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('response_notes', models.TextField(blank=True)),
                ('output_file', models.CharField(blank=True, help_text='Generated document URL', max_length=500)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_service_requests', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_service_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'self_service_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
