# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0008_candidatefollowuptask_candidateoutreachlog_and_more'),
        ('jobs', '0005_job_degree_optional_note_job_degree_required_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurtureSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger', models.CharField(choices=[('manual', 'Manual Enroll'), ('pool_join', 'Talent Pool Join'), ('prospect_created', 'Prospect Created'), ('application_withdrawn', 'Application Withdrawn'), ('silver_medalist', 'Silver Medalist')], default='manual', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('steps_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_nurture_sequences', to='tenants.tenant')),
            ],
            options={
                'db_table': 'crm_nurture_sequences',
            },
        ),
        migrations.CreateModel(
            name='NurtureStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(default=1)),
                ('delay_days', models.IntegerField(default=0, help_text='Days after previous step to send')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('linkedin', 'LinkedIn InMail')], default='email', max_length=20)),
                ('subject_line', models.CharField(blank=True, default='', max_length=500)),
                ('body_template', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='talent_crm.nurturesequence')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_nurture_steps', to='tenants.tenant')),
            ],
            options={
                'db_table': 'crm_nurture_steps',
                'ordering': ['sequence', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('headline', models.CharField(blank=True, default='', max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('referral', 'Referral'), ('event', 'Event'), ('inbound', 'Inbound'), ('other', 'Other')], default='other', max_length=30)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('engaged', 'Engaged'), ('applied', 'Applied (Converted)'), ('declined', 'Declined'), ('dormant', 'Dormant')], default='new', max_length=20)),
                ('target_role', models.CharField(blank=True, default='', max_length=255)),
                ('sourcing_consent', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_records', to='candidates.candidate')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_prospects', to=settings.AUTH_USER_MODEL)),
                ('target_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='tenants.tenant')),
            ],
            options={
                'db_table': 'prospects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NurtureEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('current_step', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], default='active', max_length=20)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_enrollments', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_enrollments', to='tenants.tenant')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='talent_crm.nurturesequence')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='talent_crm.prospect')),
            ],
            options={
                'db_table': 'crm_nurture_enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('pool_type', models.CharField(choices=[('skill', 'Skill-based'), ('geo', 'Geography-based'), ('seniority', 'Seniority-based'), ('silver_medalist', 'Silver Medalists'), ('alumni', 'Alumni'), ('talent_community', 'Talent Community'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('segment_criteria', models.JSONField(blank=True, default=dict, help_text="Auto-segment rules: {'skills': [...], 'locations': [...], 'min_years_exp': 5}")),
                ('is_active', models.BooleanField(default=True)),
                ('member_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pools', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_pools', to='tenants.tenant')),
            ],
            options={
                'db_table': 'talent_pools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('segment_query', models.JSONField(blank=True, default=dict)),
                ('subject_line', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('channel', models.CharField(default='email', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('sent_count', models.IntegerField(default=0)),
                ('open_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_campaigns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_campaigns', to='tenants.tenant')),
                ('talent_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='talent_crm.talentpool')),
            ],
            options={
                'db_table': 'outreach_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoNotContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dnc_additions', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dnc_records', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_not_contact_list', to='tenants.tenant')),
            ],
            options={
                'db_table': 'do_not_contact',
                'ordering': ['-added_at'],
                'unique_together': {('tenant', 'email')},
            },
        ),
        migrations.CreateModel(
            name='TalentPoolMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_additions', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='candidates.candidate')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='talent_crm.talentpool')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='tenants.tenant')),
            ],
            options={
                'db_table': 'talent_pool_members',
                'ordering': ['-added_at'],
                'unique_together': {('pool', 'candidate')},
            },
        ),
    ]
