# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('health', 'Health & Wellness'), ('financial', 'Financial'), ('work_life', 'Work-Life Balance'), ('learning', 'Learning & Development'), ('perks', 'Perks & Extras'), ('leave', 'Leave & Time Off'), ('transport', 'Transport'), ('food', 'Food & Meals')], max_length=15)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_highlighted', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_benefits', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_company_benefits',
                'ordering': ['-is_highlighted', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyOfficeLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Colombo HQ, Kandy Branch', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('active_job_count', models.IntegerField(default=0)),
                ('photos', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.district')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_locations', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_company_office_locations',
                'ordering': ['-is_headquarters', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyQnA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_employer_answer', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_answers', to=settings.AUTH_USER_MODEL)),
                ('asked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_questions', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_items', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_company_qna',
                'ordering': ['-helpful_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('comparison_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('employer_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='employers.employeraccount')),
                ('employer_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_employer_comparisons',
                'unique_together': {('employer_a', 'employer_b')},
            },
        ),
        migrations.CreateModel(
            name='HiringActivityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('new_jobs_posted', models.IntegerField(default=0)),
                ('jobs_filled', models.IntegerField(default=0)),
                ('avg_response_hours', models.FloatField(blank=True, null=True)),
                ('avg_time_to_hire_days', models.FloatField(blank=True, null=True)),
                ('open_positions', models.IntegerField(default=0)),
                ('is_actively_hiring', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_activity', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_hiring_activity_indicators',
                'ordering': ['-week_start'],
                'unique_together': {('employer', 'week_start')},
            },
        ),
    ]
