# Generated by Django 5.2.11 on 2026-02-28 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0001_initial'),
        ('tenants', '0002_scimconfiguration_scimsynclog_ssoconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomObjectDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name e.g. 'Company Vehicle'", max_length=100)),
                ('slug', models.SlugField(help_text="URL-safe identifier e.g. 'company_vehicle'", max_length=100)),
                ('plural_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📦', help_text='Emoji icon for UI', max_length=10)),
                ('properties', models.JSONField(default=list, help_text='\n        [{"key":"plate_number","label":"Plate Number","type":"text","required":true},\n         {"key":"assigned_to","label":"Assigned To","type":"employee_reference"},\n         {"key":"purchase_date","label":"Purchase Date","type":"date"}]\n    ')),
                ('associations', models.JSONField(default=list, help_text='\n        [{"type":"belongs_to","target":"employee","key":"assigned_employee_id"},\n         {"type":"has_many","target":"custom_object","slug":"maintenance_log"}]\n    ')),
                ('display_properties', models.JSONField(default=list, help_text='Property keys to show in list view')),
                ('title_property', models.CharField(default='name', help_text='Property used as record title', max_length=100)),
                ('searchable_properties', models.JSONField(default=list, help_text='Property keys that are searchable')),
                ('enable_timeline', models.BooleanField(default=True, help_text='Show in employee timeline')),
                ('enable_workflows', models.BooleanField(default=True, help_text='Can trigger workflow rules')),
                ('is_active', models.BooleanField(default=True)),
                ('record_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_objects', to='tenants.tenant')),
            ],
            options={
                'db_table': 'custom_object_definitions',
                'ordering': ['name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CustomObjectRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict, help_text='{"plate_number":"CAR-1234","assigned_to":"emp-uuid"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='custom_objects.customobjectdefinition')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_records', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_records', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_object_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
