# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_monthly_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_annual_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('job_posting_limit', models.IntegerField(default=3, help_text='-1 = unlimited')),
                ('featured_job_slots', models.IntegerField(default=0)),
                ('resume_database_access', models.BooleanField(default=False)),
                ('analytics_level', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('enterprise', 'Enterprise')], default='basic', max_length=10)),
                ('max_team_members', models.IntegerField(default=1)),
                ('priority_support', models.BooleanField(default=False)),
                ('custom_branding', models.BooleanField(default=False)),
                ('api_access', models.BooleanField(default=False)),
                ('features_json', models.JSONField(default=list, help_text='Marketing feature bullets')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'jf_billing_plans',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AdBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deposited_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_spent_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auto_topup_enabled', models.BooleanField(default=False)),
                ('auto_topup_threshold_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auto_topup_amount_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_budget', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_ad_budgets',
            },
        ),
        migrations.CreateModel(
            name='AdBudgetTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('spend', 'Ad Spend'), ('refund', 'Refund'), ('credit', 'Promo Credit')], max_length=10)),
                ('amount_lkr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_lkr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace_billing.adbudget')),
            ],
            options={
                'db_table': 'jf_ad_budget_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed_lkr', 'Fixed Amount Off (LKR)'), ('ad_credit', 'Ad Credit')], max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('uses_count', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, help_text='If set, only valid for this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace_billing.billingplan')),
            ],
            options={
                'db_table': 'jf_coupon_codes',
            },
        ),
        migrations.CreateModel(
            name='EmployerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Trial'), ('past_due', 'Past Due')], default='active', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mb_subscriptions', to='employers.employeraccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mb_subscriptions', to='marketplace_billing.billingplan')),
            ],
            options={
                'db_table': 'jf_employer_subscriptions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount_lkr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_lkr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('void', 'Void'), ('refunded', 'Refunded')], default='unpaid', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('line_items', models.JSONField(default=list)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mb_invoices', to='employers.employeraccount')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mb_invoices', to='marketplace_billing.employersubscription')),
            ],
            options={
                'db_table': 'jf_mb_invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
