# Generated by Django 5.2.11 on 2026-03-06 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('domain', 'Domain Verification'), ('document', 'Document Upload'), ('manual', 'Manual Review')], max_length=20)),
                ('domain', models.CharField(blank=True, max_length=300)),
                ('document_url', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='employers.employeraccount')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cx_employer_verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('fake_job', 'Fake/Suspicious Job'), ('fake_employer', 'Fake Employer'), ('suspicious_message', 'Suspicious Message'), ('fake_recruiter', 'Fake Recruiter'), ('payment_scam', 'Payment Scam')], max_length=30)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('description', models.TextField()),
                ('evidence_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed Fraud'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cx_fraud_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('id_document_url', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('trust_score', models.FloatField(default=0.0, help_text='0.0-1.0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.employeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cx_recruiter_verification',
            },
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('employer', 'Employer'), ('recruiter', 'Recruiter')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('overall_score', models.FloatField(default=0.5)),
                ('verification_score', models.FloatField(default=0.0)),
                ('activity_score', models.FloatField(default=0.0)),
                ('report_score', models.FloatField(default=1.0, help_text='Lower = more reports')),
                ('last_computed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cx_trust_score',
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
    ]
