# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('team_size', models.IntegerField(default=1)),
                ('estimated_hours', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('participants_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_gig_projects', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_projects', to='tenants.tenant')),
            ],
            options={
                'db_table': 'gig_projects',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InternalJobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('posting_type', models.CharField(choices=[('full_time', 'Full-Time Transfer'), ('part_time', 'Part-Time Role'), ('stretch', 'Stretch Assignment'), ('secondment', 'Secondment'), ('rotation', 'Rotation'), ('project', 'Project Role')], default='full_time', max_length=20)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list, help_text='[{"skill_id":"uuid","min_proficiency":2}]')),
                ('preferred_skills', models.JSONField(default=list)),
                ('min_experience_years', models.IntegerField(default=0)),
                ('min_tenure_months', models.IntegerField(default=0, help_text='Minimum months in current role')),
                ('grade_range', models.JSONField(default=list, help_text='["G4","G5","G6"]')),
                ('open_date', models.DateField()),
                ('close_date', models.DateField(blank=True, null=True)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.IntegerField(blank=True, help_text='For fixed-term postings', null=True)),
                ('is_visible_org_wide', models.BooleanField(default=True)),
                ('visible_to_departments', models.JSONField(default=list, help_text='Restrict visibility; empty=all')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='draft', max_length=20)),
                ('applications_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_postings', to='core_hr.department')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_internal_postings', to='core_hr.employee')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_postings', to='core_hr.position')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_postings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'internal_job_postings',
                'ordering': ['-open_date'],
            },
        ),
        migrations.CreateModel(
            name='MobilityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('readiness', models.CharField(choices=[('not_looking', 'Not Looking'), ('open', 'Open to Opportunities'), ('actively_looking', 'Actively Looking'), ('ready_now', 'Ready to Move Now')], default='not_looking', max_length=20)),
                ('preferred_roles', models.JSONField(default=list)),
                ('preferred_departments', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('open_to_relocation', models.BooleanField(default=False)),
                ('open_to_international', models.BooleanField(default=False)),
                ('career_aspirations', models.TextField(blank=True)),
                ('target_timeline_months', models.IntegerField(blank=True, null=True)),
                ('is_visible_to_hr', models.BooleanField(default=True)),
                ('is_visible_to_managers', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobility_profile', to='core_hr.employee')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core_hr.position')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobility_profiles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'mobility_profiles',
            },
        ),
        migrations.CreateModel(
            name='SkillMatchSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(choices=[('posting', 'Internal Posting'), ('gig', 'Gig Project'), ('learning', 'Learning Path')], max_length=20)),
                ('object_id', models.UUIDField(help_text='FK to the suggested posting/gig/course UUID')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matching_skills', models.JSONField(default=list)),
                ('gap_skills', models.JSONField(default=list)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_acted_upon', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_suggestions', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_match_suggestions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'skill_match_suggestions',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='GigParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('withdrew', 'Withdrew')], default='interested', max_length=20)),
                ('hours_contributed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('completion_rating', models.IntegerField(blank=True, help_text='1-5 rating from project owner', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_participations', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_participations', to='tenants.tenant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='internal_marketplace.gigproject')),
            ],
            options={
                'db_table': 'gig_participations',
                'unique_together': {('project', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='InternalApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_note', models.TextField(blank=True)),
                ('skill_match_score', models.DecimalField(blank=True, decimal_places=2, help_text='System-computed skill match %', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('manager_endorsed', models.BooleanField(blank=True, null=True)),
                ('manager_endorsement_note', models.TextField(blank=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_applications', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_applications', to='tenants.tenant')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internal_marketplace.internaljobposting')),
            ],
            options={
                'db_table': 'internal_applications',
                'ordering': ['-applied_at'],
                'unique_together': {('posting', 'applicant')},
            },
        ),
    ]
