# Generated by Django 5.2.11 on 2026-03-06 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('relationship', models.CharField(choices=[('current_employee', 'Current Employee'), ('former_employee', 'Former Employee'), ('applicant', 'Applicant'), ('intern', 'Intern')], max_length=20)),
                ('overall_rating', models.IntegerField()),
                ('work_life_balance', models.IntegerField(blank=True, null=True)),
                ('career_growth', models.IntegerField(blank=True, null=True)),
                ('compensation', models.IntegerField(blank=True, null=True)),
                ('management', models.IntegerField(blank=True, null=True)),
                ('culture', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('advice_to_management', models.TextField(blank=True, default='')),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('employment_duration_months', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=10)),
                ('helpful_count', models.IntegerField(default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employers.employeraccount')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_company_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('employer', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='EmployerReviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_response', to='reviews.companyreview')),
            ],
            options={
                'db_table': 'jf_review_responses',
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.companyreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_review_helpful',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
