# Generated by Django 5.2.11 on 2026-03-08 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('overall_benefits_rating', models.IntegerField(default=3, help_text='1-5 star rating')),
                ('health_insurance', models.BooleanField(blank=True, null=True)),
                ('annual_leave_days', models.IntegerField(blank=True, null=True)),
                ('remote_work_option', models.BooleanField(blank=True, null=True)),
                ('performance_bonus', models.BooleanField(blank=True, null=True)),
                ('training_allowance', models.BooleanField(blank=True, null=True)),
                ('transport_allowance', models.BooleanField(blank=True, null=True)),
                ('meal_allowance', models.BooleanField(blank=True, null=True)),
                ('pros', models.TextField(blank=True, default='')),
                ('cons', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits_reviews', to='employers.employeraccount')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_benefits_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('experience', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('difficulty', models.IntegerField(default=3, help_text='1=Very Easy to 5=Very Hard')),
                ('interview_type', models.CharField(blank=True, choices=[('phone', 'Phone Screen'), ('video', 'Video Interview'), ('in_person', 'In Person'), ('technical', 'Technical Test'), ('panel', 'Panel Interview'), ('group', 'Group Assessment')], default='', max_length=15)),
                ('num_rounds', models.IntegerField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, help_text='Process length in days', null=True)),
                ('got_offer', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('questions_asked', models.JSONField(default=list, help_text='List of interview questions remembered')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_reviews', to='employers.employeraccount')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_interview_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('job_title', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('base_salary_lkr', models.IntegerField(help_text='Monthly base salary in LKR')),
                ('total_comp_lkr', models.IntegerField(blank=True, help_text='Total compensation incl. bonus/allowances', null=True)),
                ('satisfaction_rating', models.IntegerField(default=3, help_text='1=Very Dissatisfied to 5=Very Satisfied')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_reviews', to='employers.employeraccount')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_salary_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
