# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        ('jobs', '0002_joblisting_application_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('ats_api', 'ATS API Integration'), ('xml_feed', 'XML Job Feed'), ('json_feed', 'JSON Job Feed'), ('csv_upload', 'CSV Upload'), ('partner_api', 'Partner API')], max_length=15)),
                ('feed_url', models.URLField(blank=True, default='', max_length=500)),
                ('auth_method', models.CharField(blank=True, default='', max_length=20)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error State'), ('deprecated', 'Deprecated')], default='active', max_length=15)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('total_jobs_imported', models.IntegerField(default=0)),
                ('duplicate_rate', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('sync_frequency_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_sources', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_feed_sources',
                'ordering': ['-last_sync_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedDeduplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duplicate_external_id', models.CharField(max_length=200)),
                ('duplicate_title', models.CharField(blank=True, default='', max_length=300)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('detection_method', models.CharField(default='title_hash', max_length=50)),
                ('was_suppressed', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('original_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedup_originals', to='jobs.joblisting')),
                ('feed_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedup_records', to='feed_normalization.feedsource')),
            ],
            options={
                'db_table': 'jf_feed_dedup',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DispositionSyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_application_id', models.CharField(max_length=200)),
                ('ats_stage', models.CharField(blank=True, default='', max_length=100)),
                ('ats_disposition', models.CharField(blank=True, default='', max_length=100)),
                ('platform_application_id', models.UUIDField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposition_syncs', to='feed_normalization.feedsource')),
            ],
            options={
                'db_table': 'jf_disposition_sync_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_job_id', models.CharField(blank=True, default='', max_length=200)),
                ('raw_payload', models.JSONField(default=dict)),
                ('error_type', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=10)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='feed_normalization.feedsource')),
            ],
            options={
                'db_table': 'jf_feed_error_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feed_source', 'is_resolved'], name='idx_feed_err_source')],
            },
        ),
    ]
