# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('diversity', 'Diversity'), ('wellness', 'Wellness'), ('professional', 'Professional'), ('social', 'Social'), ('volunteering', 'Volunteering'), ('other', 'Other')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('member_count', models.IntegerField(default=0)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_ergs', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ergs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ergs',
            },
        ),
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('webinar', 'Webinar'), ('workshop', 'Workshop'), ('social', 'Social'), ('volunteering', 'Volunteering'), ('celebration', 'Celebration'), ('training', 'Training'), ('other', 'Other')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('is_virtual', models.BooleanField(default=False)),
                ('meeting_url', models.CharField(blank=True, max_length=500)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('rsvp_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('attendees_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organised_events', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_events', to='tenants.tenant')),
                ('erg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='experience_hub.erg')),
            ],
            options={
                'db_table': 'community_events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('program_type', models.CharField(choices=[('spot_award', 'Spot Award'), ('peer_kudos', 'Peer Kudos'), ('milestone', 'Milestone'), ('manager_recognition', 'Manager Recognition'), ('anniversary', 'Anniversary')], default='peer_kudos', max_length=30)),
                ('point_value', models.IntegerField(default=0)),
                ('badge_icon', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('max_per_month_per_giver', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_programs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'recognition_programs',
            },
        ),
        migrations.CreateModel(
            name='RecognitionNomination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nominations', to=settings.AUTH_USER_MODEL)),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_nominations', to='core_hr.employee')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nominations', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_nominations', to='tenants.tenant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='experience_hub.recognitionprogram')),
            ],
            options={
                'db_table': 'recognition_nominations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ERGMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('lead', 'Lead'), ('co_lead', 'Co-Lead'), ('coordinator', 'Coordinator')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erg_memberships', to='core_hr.employee')),
                ('erg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='experience_hub.erg')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erg_memberships', to='tenants.tenant')),
            ],
            options={
                'db_table': 'erg_memberships',
                'unique_together': {('erg', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('not_attending', 'Not Attending'), ('maybe', 'Maybe')], default='attending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to='core_hr.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='experience_hub.communityevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to='tenants.tenant')),
            ],
            options={
                'db_table': 'event_rsvps',
                'unique_together': {('event', 'employee')},
            },
        ),
    ]
