# Generated by Django 5.2.11 on 2026-03-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('index_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('doc_count', models.IntegerField(default=0)),
                ('last_rebuilt_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_rebuilding', models.BooleanField(default=False)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('mapping_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'jf_search_indexes',
            },
        ),
    ]
