# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        ('jobs', '0002_joblisting_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseSurface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surface_type', models.CharField(choices=[('category', 'Browse by Category'), ('city', 'Browse by City'), ('salary', 'Browse by Salary'), ('level', 'Browse by Level'), ('industry', 'Browse by Industry'), ('shift', 'Browse by Shift'), ('contract', 'Browse by Contract Type')], max_length=15)),
                ('label', models.CharField(max_length=100)),
                ('label_si', models.CharField(blank=True, default='', max_length=100)),
                ('label_ta', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('job_count', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jf_browse_surfaces',
                'ordering': ['-is_featured', 'sort_order'],
                'unique_together': {('surface_type', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PersonalizedFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_ids', models.JSONField(default=list, help_text='Ordered list of job UUIDs in ranked order')),
                ('algorithm_version', models.CharField(default='v1', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_personalized_feeds',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rec_type', models.CharField(choices=[('similar', 'Similar Jobs'), ('also_viewed', 'People Also Viewed'), ('role_adjacent', 'Related Roles'), ('trending', 'Trending'), ('personalized', 'For You')], max_length=20)),
                ('score', models.FloatField(default=0.0, help_text='Recommendation relevance score')),
                ('reasons', models.JSONField(default=list, help_text="Human-readable reasons e.g. ['same category', 'similar salary']")),
                ('algorithm_version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_target', to='jobs.joblisting')),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_source', to='jobs.joblisting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_job_recommendations',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['source_job', 'rec_type'], name='idx_rec_source'), models.Index(fields=['user', 'rec_type'], name='idx_rec_user')],
            },
        ),
        migrations.CreateModel(
            name='SearchExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('match_score', models.FloatField(default=0.0)),
                ('salary_match', models.BooleanField(default=False)),
                ('location_match', models.BooleanField(default=False)),
                ('experience_match', models.BooleanField(default=False)),
                ('explanation_text', models.CharField(blank=True, default='', max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='jobs.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_explanations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_search_explanations',
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='TrendingEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('job_post_velocity', models.IntegerField(default=0, help_text='New jobs this week')),
                ('view_growth_pct', models.FloatField(default=0.0)),
                ('application_growth_pct', models.FloatField(default=0.0)),
                ('trending_score', models.FloatField(default=0.0)),
                ('reasons', models.JSONField(default=list)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_snapshots', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_trending_employers',
                'ordering': ['-trending_score'],
                'unique_together': {('employer', 'week_start')},
            },
        ),
    ]
