# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('contractor_ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('plan_type', models.CharField(choices=[('perm_only', 'Permanent Placements Only'), ('contract_only', 'Contract Spread Only'), ('hybrid', 'Hybrid (Perm + Contract)')], default='hybrid', max_length=20)),
                ('commission_model', models.CharField(choices=[('percentage_fee', '% of Placement Fee'), ('flat_amount', 'Flat Amount per Placement'), ('tiered', 'Tiered (volume-based)'), ('pct_revenue', '% of Revenue')], default='percentage_fee', max_length=30)),
                ('perm_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('contract_spread_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tiers', models.JSONField(default=list)),
                ('monthly_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('draw_is_recoverable', models.BooleanField(default=True)),
                ('clawback_days', models.IntegerField(default=90)),
                ('clawback_policy', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_plans', to='agencies.agency')),
            ],
            options={
                'db_table': 'comm_plan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_type', models.CharField(choices=[('perm_placement', 'Permanent Placement'), ('contract_spread', 'Contract Spread'), ('retainer', 'Retainer'), ('bonus', 'Bonus')], max_length=30)),
                ('status', models.CharField(choices=[('projected', 'Projected'), ('earned', 'Earned'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('clawed_back', 'Clawed Back'), ('on_hold', 'On Hold'), ('voided', 'Voided')], default='projected', max_length=30)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gross_commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('recruiter_split_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('recruiter_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('am_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('earned_period_start', models.DateField(blank=True, null=True)),
                ('earned_period_end', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('clawback_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('clawback_reason', models.TextField(blank=True)),
                ('clawed_back_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='agencies.agency')),
                ('am_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_as_am', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='contractor_ops.assignment')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='agencies.agencyplacement')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='commissions.commissionplan')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_as_recruiter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comm_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterCommissionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recruiter_split_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('am_split_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_comm_assignments', to='agencies.agency')),
                ('am_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='am_comm_assignments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_assignments', to='commissions.commissionplan')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comm_recruiter_assignment',
            },
        ),
    ]
