# Generated by Django 5.2.11 on 2026-03-06 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('muted_categories', models.JSONField(blank=True, default=list, help_text='List of category slugs the user has muted')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comm_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cx_comm_preference',
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('in_app', 'In-App')], max_length=20)),
                ('category', models.CharField(choices=[('recruiter_outreach', 'Recruiter Outreach'), ('candidate_reminder', 'Candidate Reminder'), ('interview', 'Interview'), ('offer', 'Offer'), ('onboarding', 'Onboarding'), ('learning', 'Learning'), ('mentor', 'Mentorship'), ('system', 'System'), ('marketing', 'Marketing')], max_length=30)),
                ('subject', models.CharField(blank=True, help_text='For email', max_length=500)),
                ('body', models.TextField(help_text='Template body with {{variable}} placeholders')),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='NULL = platform default template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm_templates', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'cx_comm_template',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('in_app', 'In-App')], max_length=20)),
                ('category', models.CharField(choices=[('recruiter_outreach', 'Recruiter Outreach'), ('candidate_reminder', 'Candidate Reminder'), ('interview', 'Interview'), ('offer', 'Offer'), ('onboarding', 'Onboarding'), ('learning', 'Learning'), ('mentor', 'Mentorship'), ('system', 'System'), ('marketing', 'Marketing')], max_length=30)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='queued', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='communications.communicationtemplate')),
            ],
            options={
                'db_table': 'cx_comm_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='cx_comm_mes_recipie_cafdc3_idx'), models.Index(fields=['channel', 'status'], name='cx_comm_mes_channel_84ac0e_idx')],
            },
        ),
    ]
