# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadcountPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('plan_year', models.IntegerField()),
                ('planned_headcount', models.IntegerField()),
                ('current_headcount', models.IntegerField(default=0)),
                ('approved_headcount', models.IntegerField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_headcount_plans', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headcount_plans', to='core_hr.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headcount_plans', to='core_hr.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headcount_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'headcount_plans',
            },
        ),
        migrations.CreateModel(
            name='HiringRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=20)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('new_headcount', 'New Headcount'), ('backfill', 'Backfill'), ('internal_transfer', 'Internal Transfer'), ('temp_to_perm', 'Temp to Perm')], max_length=30)),
                ('budget_grade', models.CharField(blank=True, max_length=50)),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requisitions', to='core_hr.department')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_requisitions', to='core_hr.employee')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='workforce_planning.headcountplan')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_requisitions', to='core_hr.position')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requisitions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hiring_requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgDesignScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_snapshot', models.JSONField(default=dict, help_text='Current org structure snapshot')),
                ('proposed_changes', models.JSONField(default=list, help_text='List of proposed org changes')),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('headcount_impact', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('discarded', 'Discarded')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_design_scenarios', to='tenants.tenant')),
            ],
            options={
                'db_table': 'org_design_scenarios',
            },
        ),
        migrations.CreateModel(
            name='PositionBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_year', models.IntegerField()),
                ('allocated_headcount', models.IntegerField(default=1)),
                ('filled_headcount', models.IntegerField(default=0)),
                ('budgeted_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('is_critical_role', models.BooleanField(default=False)),
                ('succession_readiness', models.CharField(choices=[('ready_now', 'Ready Now'), ('ready_12m', 'Ready in 12 months'), ('ready_24m', 'Ready in 24 months'), ('gap', 'Gap')], default='gap', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_budgets', to='workforce_planning.headcountplan')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_budgets', to='core_hr.position')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_budgets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'position_budgets',
                'unique_together': {('position', 'budget_year')},
            },
        ),
    ]
