# Generated by Django 5.2.11 on 2026-03-08 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        ('jobs', '0002_joblisting_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedJobCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('bid_model', models.CharField(choices=[('cpc', 'Cost Per Click'), ('cpa', 'Cost Per Application'), ('fixed', 'Fixed Boost'), ('daily_budget', 'Daily Budget')], default='cpc', max_length=15)),
                ('bid_amount_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_budget_lkr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_budget_lkr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('spent_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('applications', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_promoted_job_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boost_factor', models.FloatField(default=2.0, help_text='Ranking multiplier')),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('applications', models.IntegerField(default=0)),
                ('spent_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='jobs.joblisting')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_jobs', to='promotions_ads.promotedjobcampaign')),
            ],
            options={
                'db_table': 'jf_promoted_jobs',
                'unique_together': {('campaign', 'job')},
            },
        ),
        migrations.CreateModel(
            name='SponsoredCompanyPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement', models.CharField(choices=[('search_top', 'Top of Search Results'), ('homepage_featured', 'Homepage Featured'), ('category_spotlight', 'Category Spotlight'), ('sidebar', 'Sidebar Banner')], max_length=25)),
                ('headline', models.CharField(blank=True, default='', max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('cta_text', models.CharField(blank=True, default='See Open Roles', max_length=100)),
                ('cta_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('budget_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spent_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_placements', to='employers.employeraccount')),
            ],
            options={
                'db_table': 'jf_sponsored_company_pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_unique', models.BooleanField(default=True)),
                ('cost_lkr', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('source_page', models.CharField(blank=True, default='', max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('promoted_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='promotions_ads.promotedjob')),
            ],
            options={
                'db_table': 'jf_ad_clicks',
                'indexes': [models.Index(fields=['promoted_job', 'clicked_at'], name='idx_adclick_job_date')],
            },
        ),
    ]
