# Generated by Django 5.2.11 on 2026-03-09 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        ('jobs', '0002_joblisting_application_deadline_and_more'),
        ('promotions_ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialShareKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_page_id', models.UUIDField(blank=True, help_text='ID of the employers.CareerSitePage', null=True)),
                ('linkedin_text', models.TextField(blank=True, default='')),
                ('twitter_text', models.TextField(blank=True, default='')),
                ('whatsapp_text', models.TextField(blank=True, default='')),
                ('facebook_text', models.TextField(blank=True, default='')),
                ('share_image', models.ImageField(blank=True, null=True, upload_to='social_kits/')),
                ('share_url', models.URLField(blank=True, default='', max_length=500)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_kits', to='employers.employeraccount')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_kits', to='jobs.joblisting')),
            ],
            options={
                'db_table': 'jf_rm_social_kits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSourceAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('apply', 'Application'), ('talent_signup', 'Talent Community Sign-up'), ('social_click', 'Social Share Click'), ('email_open', 'Email Open')], max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('medium', models.CharField(blank=True, default='', max_length=100)),
                ('campaign', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.CharField(blank=True, default='', max_length=100)),
                ('career_page_id', models.UUIDField(blank=True, help_text='ID of the employers.CareerSitePage', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_attributions', to='employers.employeraccount')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.joblisting')),
            ],
            options={
                'db_table': 'jf_rm_campaign_attributions',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['employer', 'event_type', '-recorded_at'], name='idx_rm_csa_employer_event')],
            },
        ),
        migrations.CreateModel(
            name='TalentCommunityMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_page_id', models.UUIDField(blank=True, help_text='ID of the employers.CareerSitePage', null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('interested_roles', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(blank=True, default='', help_text='utm_source / referral code', max_length=50)),
                ('is_existing_user', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_community', to='employers.employeraccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_rm_talent_community',
                'ordering': ['-joined_at'],
                'unique_together': {('employer', 'email')},
            },
        ),
    ]
