# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('scam_job', 'Fraudulent Job Posting'), ('impersonation', 'Agency Impersonation'), ('fake_client', 'Fake Client'), ('harassment', 'Recruiter Harassment'), ('data_misuse', 'Candidate Data Misuse'), ('payment_fraud', 'Payment Fraud'), ('suspicious_outreach', 'Suspicious Outreach'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('reported_job_order_id', models.UUIDField(blank=True, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField()),
                ('evidence_urls', models.JSONField(default=list)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='agencies.agency')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_abuse_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_abuse_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_abuse_report',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyTrustProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted')], default='unverified', max_length=20)),
                ('domain_verified', models.BooleanField(default=False)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('business_reg_verified', models.BooleanField(default=False)),
                ('business_reg_number', models.CharField(blank=True, max_length=100)),
                ('tax_id_verified', models.BooleanField(default=False)),
                ('kyc_completed', models.BooleanField(default=False)),
                ('kyc_completed_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_provider', models.CharField(blank=True, max_length=100)),
                ('professional_insurance_verified', models.BooleanField(default=False)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('trust_score', models.IntegerField(default=50)),
                ('trust_score_updated_at', models.DateTimeField(blank=True, null=True)),
                ('payout_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('impersonation_flag', models.BooleanField(default=False)),
                ('fraud_flag', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to='agencies.agency')),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_agency_profile',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='agencies.agency')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_audit_log',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('scam_link', 'Scam / Phishing Link'), ('mass_outreach', 'Unusual Mass Outreach'), ('impersonation', 'Impersonation Signal'), ('suspicious_job', 'Suspicious Job Content'), ('payment_request', 'Upfront Payment Request'), ('rapid_login', 'Rapid/Unusual Login'), ('api_abuse', 'API Rate Abuse'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_outcome', models.CharField(blank=True, max_length=200)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_logs', to='agencies.agency')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspicious_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_suspicious_activity',
                'ordering': ['-detected_at'],
            },
        ),
    ]
