# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0005_offer_esign_document_url_offer_esign_envelope_id_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferApprovalMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('above_band_threshold_pct', models.FloatField(default=0.0, help_text='If offer is N% above band max, trigger this matrix')),
                ('department_filter', models.CharField(blank=True, default='', max_length=150)),
                ('level_filter', models.CharField(blank=True, default='', max_length=100)),
                ('requires_cfo_approval', models.BooleanField(default=False)),
                ('requires_chro_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offer_approval_matrices',
            },
        ),
        migrations.CreateModel(
            name='OfferApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offer_approval_steps',
                'ordering': ['offer', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='OfferVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict, help_text='Full offer data at this point in time')),
                ('change_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offer_versions',
                'ordering': ['offer', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='RelocationPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('international', 'International')], default='standard', max_length=20)),
                ('max_reimbursement', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('includes_house_hunting', models.BooleanField(default=False)),
                ('includes_temporary_housing', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'relocation_packages',
            },
        ),
        migrations.CreateModel(
            name='CompensationBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job_family_ref', models.CharField(blank=True, default='', help_text='Human-readable reference', max_length=255)),
                ('level_ref', models.CharField(blank=True, default='', max_length=100)),
                ('geo_zone', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('band_min', models.DecimalField(decimal_places=2, max_digits=14)),
                ('band_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('band_max', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_bands', to='tenants.tenant')),
            ],
            options={
                'db_table': 'compensation_bands',
                'ordering': ['name', 'geo_zone'],
            },
        ),
        migrations.CreateModel(
            name='CompetitivenessAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(default='pay_competitiveness', max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('job_family_ref', models.CharField(blank=True, default='', max_length=255)),
                ('level_ref', models.CharField(blank=True, default='', max_length=100)),
                ('geo_zone', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitiveness_alerts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'competitiveness_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounterOfferPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counter_base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counter_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counter_equity_units', models.IntegerField(blank=True, null=True)),
                ('counter_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('presented', 'Presented'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offers', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers', to='applications.offer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offer_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'counter_offer_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquityGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grant_type', models.CharField(choices=[('rsu', 'RSU'), ('iso', 'ISO'), ('nso', 'NSO'), ('esop', 'ESOP'), ('phantom', 'Phantom Stock')], default='rsu', max_length=20)),
                ('units', models.IntegerField(default=0)),
                ('cliff_months', models.IntegerField(default=12)),
                ('vest_months', models.IntegerField(default=48)),
                ('strike_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_grants', to='tenants.tenant')),
            ],
            options={
                'db_table': 'equity_grants',
            },
        ),
    ]
