# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0005_offer_esign_document_url_offer_esign_envelope_id_and_more'),
        ('compensation_ops', '0001_initial'),
        ('job_architecture', '0001_initial'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offerapprovalmatrix',
            name='approval_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_matrices', to='job_architecture.approvalchain'),
        ),
        migrations.AddField(
            model_name='offerapprovalmatrix',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_approval_matrices', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offerapprovalstep',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerapprovalstep',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='applications.offer'),
        ),
        migrations.AddField(
            model_name='offerapprovalstep',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_approval_steps', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='offerversion',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_version_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerversion',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='applications.offer'),
        ),
        migrations.AddField(
            model_name='offerversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_versions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='relocationpackage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocation_packages', to='tenants.tenant'),
        ),
    ]
