# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiversityMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_date', models.DateField()),
                ('metric_type', models.CharField(choices=[('gender', 'Gender'), ('age', 'Age'), ('tenure', 'Tenure'), ('nationality', 'Nationality'), ('employment_type', 'Employment Type'), ('department_distribution', 'Department Distribution')], max_length=30)),
                ('data', models.JSONField(default=dict, help_text='Full breakdown dict')),
                ('total_count', models.IntegerField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('scope_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diversity_metrics', to='core_hr.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diversity_metrics', to='tenants.tenant')),
            ],
            options={
                'db_table': 'diversity_metrics',
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='HeadcountSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('headcount', models.IntegerField()),
                ('new_hires', models.IntegerField(default=0)),
                ('terminations', models.IntegerField(default=0)),
                ('transfers_in', models.IntegerField(default=0)),
                ('transfers_out', models.IntegerField(default=0)),
                ('avg_tenure_months', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gender_breakdown', models.JSONField(default=dict)),
                ('employment_type_breakdown', models.JSONField(default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headcount_snapshots', to='core_hr.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headcount_snapshots', to='core_hr.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headcount_snapshots', to='tenants.tenant')),
            ],
            options={
                'db_table': 'headcount_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='PeopleAnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('report_type', models.CharField(choices=[('headcount', 'Headcount'), ('turnover', 'Turnover'), ('diversity', 'Diversity'), ('pay_equity', 'Pay Equity'), ('engagement', 'Engagement'), ('performance', 'Performance'), ('custom', 'Custom')], max_length=30)),
                ('schedule', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', max_length=10)),
                ('config', models.JSONField(default=dict, help_text='Filters, groupings, metrics configuration')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.JSONField(blank=True, null=True)),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], default='json', max_length=10)),
                ('recipients', models.JSONField(default=list, help_text='List of user UUIDs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analytics_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_analytics_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'people_analytics_reports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TurnoverReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField(blank=True, null=True)),
                ('headcount_start', models.IntegerField()),
                ('headcount_end', models.IntegerField()),
                ('voluntary_exits', models.IntegerField(default=0)),
                ('involuntary_exits', models.IntegerField(default=0)),
                ('total_exits', models.IntegerField(default=0)),
                ('turnover_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('regrettable_exits', models.IntegerField(default=0)),
                ('avg_tenure_at_exit_months', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('top_exit_reasons', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnover_reports', to='core_hr.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnover_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'turnover_reports',
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='AttritionRiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computed_date', models.DateField()),
                ('risk_score', models.IntegerField(help_text='0–100')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('contributing_factors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('model_version', models.CharField(max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_risk_scores', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_risk_scores', to='tenants.tenant')),
            ],
            options={
                'db_table': 'attrition_risk_scores',
                'ordering': ['-computed_date'],
                'unique_together': {('employee', 'computed_date')},
            },
        ),
    ]
