# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wcag_level', models.CharField(choices=[('A', 'Level A'), ('AA', 'Level AA'), ('AAA', 'Level AAA')], default='AA', max_length=3)),
                ('high_contrast_enabled', models.BooleanField(default=False)),
                ('font_size_default', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='medium', max_length=10)),
                ('keyboard_nav_enabled', models.BooleanField(default=True)),
                ('screen_reader_hints', models.BooleanField(default=True)),
                ('language_default', models.CharField(default='en', max_length=10)),
                ('rtl_support', models.BooleanField(default=False)),
                ('color_blind_mode', models.CharField(choices=[('none', 'None'), ('protanopia', 'Protanopia'), ('deuteranopia', 'Deuteranopia'), ('tritanopia', 'Tritanopia')], default='none', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accessibility_configs',
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('attrition_prediction', 'Attrition Prediction'), ('skill_matching', 'Skill Matching'), ('sentiment', 'Sentiment Analysis'), ('anomaly_detection', 'Anomaly Detection'), ('compensation_benchmarking', 'Compensation Benchmarking'), ('custom', 'Custom')], max_length=40)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('training_data_description', models.TextField(blank=True)),
                ('last_trained_at', models.DateField(blank=True, null=True)),
                ('accuracy_metrics', models.JSONField(default=dict)),
                ('bias_assessment', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('explainability_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ai_models', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_models',
            },
        ),
        migrations.CreateModel(
            name='AIDecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(help_text="e.g. 'Employee'", max_length=50)),
                ('entity_id', models.UUIDField()),
                ('decision_type', models.CharField(max_length=100)),
                ('input_features', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('was_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_decision_overrides', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_decision_logs', to='tenants.tenant')),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='compliance_ai.aimodel')),
            ],
            options={
                'db_table': 'ai_decision_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(help_text="e.g. 'payroll_entries'", max_length=100)),
                ('retention_years', models.IntegerField()),
                ('legal_basis', models.CharField(blank=True, max_length=200)),
                ('auto_delete', models.BooleanField(default=False)),
                ('last_purge_at', models.DateTimeField(blank=True, null=True)),
                ('next_purge_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_retention_policies', to='tenants.tenant')),
            ],
            options={
                'db_table': 'data_retention_policies',
            },
        ),
        migrations.CreateModel(
            name='PrivacyConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('analytics_data', 'Analytics Data'), ('ai_profiling', 'AI Profiling'), ('third_party_sharing', 'Third-Party Sharing'), ('marketing', 'Marketing'), ('all', 'All')], max_length=30)),
                ('is_granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_version', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to='tenants.tenant')),
            ],
            options={
                'db_table': 'privacy_consents',
                'unique_together': {('employee', 'consent_type')},
            },
        ),
    ]
