# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0005_offer_esign_document_url_offer_esign_envelope_id_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(choices=[('coding', 'Coding Challenge'), ('cognitive', 'Cognitive Ability'), ('personality', 'Personality / Values'), ('work_sample', 'Work Sample'), ('video', 'Video Response'), ('language', 'Language Proficiency'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('external_id', models.CharField(blank=True, default='', help_text='Vendor-side assessment ID', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('passing_score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_per_use', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eu_ai_act_risk_level', models.CharField(default='limited', help_text='EU AI Act risk classification: minimal, limited, high', max_length=20)),
                ('requires_human_review', models.BooleanField(default=False, help_text='EU AI Act Annex III — human review mandatory for high-risk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_catalog', to='tenants.tenant')),
            ],
            options={
                'db_table': 'assessment_catalog_items',
                'ordering': ['vendor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlternateAssessmentPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accommodation_type', models.CharField(blank=True, default='', help_text='e.g. Extended time, Screen reader compatible', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_assessment_paths', to='tenants.tenant')),
                ('alternate_catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_as_alternate_for', to='assessments.assessmentcatalogitem')),
                ('original_catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_paths', to='assessments.assessmentcatalogitem')),
            ],
            options={
                'db_table': 'alternate_assessment_paths',
            },
        ),
        migrations.CreateModel(
            name='AssessmentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('started', 'Started'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=20)),
                ('external_order_id', models.CharField(blank=True, default='', max_length=255)),
                ('invite_url', models.URLField(blank=True, default='')),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_orders', to='applications.application')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='assessments.assessmentcatalogitem')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_orders_placed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_orders', to='tenants.tenant')),
            ],
            options={
                'db_table': 'assessment_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_score', models.FloatField(blank=True, null=True)),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('band_label', models.CharField(blank=True, default='', help_text='e.g. Expert, Proficient', max_length=100)),
                ('sub_scores', models.JSONField(blank=True, default=dict, help_text='{"problem_solving": 85, "code_quality": 72}')),
                ('report_url', models.URLField(blank=True, default='')),
                ('ai_summary', models.TextField(blank=True, default='', help_text='AI-generated plain-language summary')),
                ('human_reviewed', models.BooleanField(default=False, help_text='EU AI Act — human has reviewed AI output')),
                ('human_review_note', models.TextField(blank=True, default='')),
                ('human_override', models.BooleanField(blank=True, help_text='Reviewer overrode AI pass/fail', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('human_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessment_results', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessmentorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='tenants.tenant')),
            ],
            options={
                'db_table': 'assessment_results',
            },
        ),
        migrations.CreateModel(
            name='AssessmentVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('api_base_url', models.URLField(blank=True, default='')),
                ('api_key_encrypted', models.TextField(blank=True, default='', help_text='Encrypted vendor API key')),
                ('webhook_secret_encrypted', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('supported_types', models.JSONField(blank=True, default=list, help_text='["coding", "cognitive", "personality", "work_sample"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_vendors', to='tenants.tenant')),
            ],
            options={
                'db_table': 'assessment_vendors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assessmentcatalogitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='assessments.assessmentvendor'),
        ),
        migrations.CreateModel(
            name='AssessmentWaiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('accommodation', 'Disability Accommodation'), ('strong_referral', 'Strong Referral'), ('repeat_candidate', 'Repeat / Known Candidate'), ('exec_override', 'Executive Override'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_waivers', to='applications.application')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waivers', to='assessments.assessmentcatalogitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_waivers', to='tenants.tenant')),
                ('waived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_waivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_waivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentorder',
            index=models.Index(fields=['tenant', 'status'], name='assessment__tenant__2df8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentorder',
            index=models.Index(fields=['application'], name='assessment__applica_d73e3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentvendor',
            unique_together={('tenant', 'slug')},
        ),
    ]
