# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scope', models.JSONField(default=list, help_text='["leave_approval","expense_approval","timesheet_approval"]')),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to='core_hr.employee')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_rules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'delegation_rules',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagerDashboardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pinned_widgets', models.JSONField(default=list, help_text='["team_attendance","pending_approvals","team_goals"]')),
                ('layout', models.JSONField(default=dict, help_text='Widget grid layout positions')),
                ('default_team_view', models.CharField(choices=[('list', 'List'), ('grid', 'Grid'), ('org_chart', 'Org Chart')], default='list', max_length=20)),
                ('show_indirect_reports', models.BooleanField(default=False)),
                ('notification_prefs', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_dashboard_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'manager_dashboard_configs',
            },
        ),
        migrations.CreateModel(
            name='OneOnOne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('location', models.CharField(blank=True, help_text='Room, Zoom link, etc.', max_length=200)),
                ('agenda', models.JSONField(default=list, help_text='[{"topic":"Career goals","notes":"...","added_by":"manager"}]')),
                ('notes', models.TextField(blank=True, help_text='Shared meeting notes')),
                ('manager_notes', models.TextField(blank=True, help_text='Private manager notes')),
                ('action_items', models.JSONField(default=list, help_text='[{"item":"Share development plan","owner":"employee","due":"2024-03-15","done":false}]')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('recurrence', models.CharField(blank=True, choices=[('none', 'None'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=20)),
                ('talk_about', models.JSONField(default=list, help_text='Shared talking points added by employee')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_on_ones_as_employee', to='core_hr.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_on_ones_as_manager', to='core_hr.employee')),
                ('recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='manager_hub.oneonone')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_on_ones', to='tenants.tenant')),
            ],
            options={
                'db_table': 'one_on_ones',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('observation', 'Observation'), ('coaching', 'Coaching Session'), ('commendation', 'Commendation'), ('concern', 'Concern'), ('development', 'Development Note'), ('pip_note', 'PIP Note')], default='observation', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('is_shared_with_hr', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_notes_received', to='core_hr.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_notes_given', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_notes', to='tenants.tenant')),
                ('related_one_on_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_notes', to='manager_hub.oneonone')),
            ],
            options={
                'db_table': 'coaching_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('probation_due', 'Probation Review Due'), ('contract_expiry', 'Contract Expiry Approaching'), ('leave_overdue', 'Leave Request Pending'), ('attendance_anomaly', 'Attendance Anomaly'), ('goal_at_risk', 'Goal At Risk'), ('certification_expiry', 'Certification Expiry'), ('performance_review_due', 'Performance Review Due'), ('high_attrition_risk', 'High Attrition Risk'), ('birthday', 'Team Birthday'), ('work_anniversary', 'Work Anniversary')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_about_me', to='core_hr.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_alerts', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_alerts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'team_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamPerformanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField(blank=True, help_text='Null = annual summary', null=True)),
                ('headcount', models.IntegerField(default=0)),
                ('avg_performance_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avg_attendance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_goal_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pending_approvals', models.IntegerField(default=0)),
                ('open_leave_requests', models.IntegerField(default=0)),
                ('attrition_risk_high', models.IntegerField(default=0)),
                ('attrition_risk_medium', models.IntegerField(default=0)),
                ('engagement_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('top_performers', models.JSONField(default=list)),
                ('at_risk_employees', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_performance_summaries', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_performance_summaries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'team_performance_summaries',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('manager', 'period_year', 'period_month')},
            },
        ),
    ]
