# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContingentWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('worker_type', models.CharField(choices=[('contractor', 'Contractor'), ('temp', 'Temp'), ('consultant', 'Consultant'), ('freelancer', 'Freelancer'), ('intern', 'Intern')], default='contractor', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_currency', models.CharField(default='LKR', max_length=3)),
                ('rate_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('fixed', 'Fixed')], default='hourly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('nda_signed', models.BooleanField(default=False)),
                ('bg_check_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_required', 'Not Required')], default='not_required', max_length=20)),
                ('access_granted', models.JSONField(default=list, help_text='Systems/tools this worker has been granted access to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contingent_workers', to='core_hr.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contingent_team', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contingent_workers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'contingent_workers',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContingentCompliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_type', models.CharField(choices=[('nda', 'NDA'), ('background_check', 'Background Check'), ('insurance', 'Insurance'), ('certification', 'Certification'), ('contract', 'Contract'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('last_reviewed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contingent_compliance_records', to='tenants.tenant')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='contingent_ops.contingentworker')),
            ],
            options={
                'db_table': 'contingent_compliance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('preferred', models.BooleanField(default=False)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('under_review', 'Under Review'), ('expired', 'Expired')], default='under_review', max_length=20)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='tenants.tenant')),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contingentworker',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='contingent_ops.vendor'),
        ),
        migrations.CreateModel(
            name='ContingentTimesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('daily_hours', models.JSONField(default=dict, help_text='{"Mon": 8.0, "Tue": 8.0, "Wed": 8.0, "Thu": 8.0, "Fri": 8.0}')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contingent_timesheets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contingent_timesheets', to='tenants.tenant')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='contingent_ops.contingentworker')),
            ],
            options={
                'db_table': 'contingent_timesheets',
                'ordering': ['-week_start'],
                'unique_together': {('worker', 'week_start')},
            },
        ),
    ]
