# Generated by Django 5.2.11 on 2026-03-06 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('grade', models.CharField(default='D', max_length=2)),
                ('sections', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_brand_scores',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('target_role', models.CharField(max_length=200)),
                ('target_salary', models.CharField(blank=True, default='', max_length=50)),
                ('timeframe', models.CharField(blank=True, default='', max_length=50)),
                ('milestones', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_career_roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('job_description', models.TextField(blank=True, default='')),
                ('your_name', models.CharField(max_length=200)),
                ('your_skills', models.JSONField(default=list)),
                ('experience', models.CharField(blank=True, default='', max_length=500)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('enthusiastic', 'Enthusiastic'), ('confident', 'Confident')], default='professional', max_length=15)),
                ('content', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_cover_letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPrepSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=25)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=20)),
                ('answer', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('feedback', models.JSONField(default=list)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ai_tools.interviewprepsession')),
            ],
            options={
                'db_table': 'jf_interview_answers',
            },
        ),
        migrations.CreateModel(
            name='LinkedInAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, default='', max_length=300)),
                ('total_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_linkedin_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('bio', models.TextField(blank=True, default='')),
                ('years_experience', models.IntegerField(default=0)),
                ('hourly_rate_lkr', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('sessions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.district')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_mentor_profiles',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ai_tools.mentorprofile')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_mentorship_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkingDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_networking_drafts',
                'ordering': ['-created_at'],
            },
        ),
    ]
