# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('contractor_ops', '0001_initial'),
        ('job_orders', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndingAssignmentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('extended', 'Assignment Extended'), ('redeployed', 'Redeployed'), ('ended', 'Assignment Ended (No Redeploy)'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('assignment_end_date', models.DateField()),
                ('days_until_end', models.IntegerField()),
                ('action_taken', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_alerts', to='agencies.agency')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeployment_alerts', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_alerts', to='contractor_ops.assignment')),
            ],
            options={
                'db_table': 'redep_ending_alert',
                'ordering': ['assignment_end_date'],
            },
        ),
        migrations.CreateModel(
            name='RedeploymentOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('match_reasons', models.JSONField(default=list)),
                ('match_status', models.CharField(choices=[('suggested', 'AI Suggested'), ('reviewed', 'Recruiter Reviewed'), ('pursuing', 'Pursuing'), ('submitted', 'Submitted'), ('placed', 'Placed'), ('rejected', 'Not a Fit')], default='suggested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeployment_opportunities', to='agencies.agency')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeployment_opportunities', to='submissions.candidateprofile')),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeployment_opportunities', to='job_orders.joborder')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_redeploy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'redep_opportunity',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='RedeploymentPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pool_type', models.CharField(choices=[('general', 'General Available Pool'), ('skill_based', 'Skill-Based'), ('sector', 'Sector-Specific'), ('geography', 'Geography-Based'), ('client_specific', 'Client-Specific Bench'), ('silver_medalist', 'Silver Medalist Pool'), ('boomerang', 'Boomerang Alumni')], default='general', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('target_skills', models.JSONField(default=list)),
                ('target_geographies', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeployment_pools', to='agencies.agency')),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_pools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'redep_pool',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RedeploymentPoolMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Available'), ('placed', 'Placed / No Longer Available'), ('opted_out', 'Opted Out'), ('removed', 'Removed')], default='active', max_length=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('redeployment_score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_additions', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='submissions.candidateprofile')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='redeployment.redeploymentpool')),
            ],
            options={
                'db_table': 'redep_pool_member',
                'unique_together': {('pool', 'candidate')},
            },
        ),
    ]
