# Generated by Django 5.2.11 on 2026-02-27 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(default=list, help_text='["employee.created", "leave.approved", ...]')),
                ('secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'webhook_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('attempt', models.IntegerField(default=1)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='platform_core.webhooksubscription')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(help_text='e.g. LeaveRequest, JobChange, PayrollRun', max_length=50)),
                ('entity_id', models.UUIDField()),
                ('action_type', models.CharField(help_text='e.g. approve_leave, approve_promotion', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.IntegerField(default=1, help_text='Step in multi-level approval chain')),
                ('total_steps', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approver', 'status'], name='idx_approval_approver')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='e.g. employee.created, leave.approved', max_length=100)),
                ('entity_type', models.CharField(help_text='Model name (Employee, LeaveRequest, etc.)', max_length=50)),
                ('entity_id', models.UUIDField()),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": {"old": ..., "new": ...}}')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrm_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='idx_audit_tenant'), models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='idx_audit_entity')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('action', 'Action Required')], default='info', max_length=30)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=20)),
                ('action_url', models.URLField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.tenant')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='idx_notif_recipient')],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='e.g. employee.created, leave.approved, payroll.payslip_generated', max_length=100)),
                ('category', models.CharField(choices=[('hr', 'HR Action'), ('leave', 'Leave'), ('attendance', 'Attendance'), ('payroll', 'Payroll'), ('performance', 'Performance'), ('onboarding', 'Onboarding'), ('document', 'Document'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('automation', 'Workflow Automation')], default='user', max_length=20)),
                ('source_object_type', models.CharField(blank=True, max_length=50)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'timeline_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', '-created_at'], name='idx_timeline_emp'), models.Index(fields=['tenant', 'category'], name='idx_timeline_cat')],
            },
        ),
    ]
