# Generated by Django 5.2.11 on 2026-02-28 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0001_initial'),
        ('platform_core', '0001_initial'),
        ('tenants', '0002_scimconfiguration_scimsynclog_ssoconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('plan_type', models.CharField(choices=[('health', 'Health Insurance'), ('dental', 'Dental'), ('vision', 'Vision'), ('life', 'Life Insurance'), ('retirement', 'Retirement'), ('wellness', 'Wellness'), ('education', 'Education Allowance'), ('transport', 'Transport'), ('meal', 'Meal'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('coverage_details', models.JSONField(default=dict, help_text='Plan-specific coverage info')),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_window_start', models.DateField(blank=True, null=True)),
                ('enrollment_window_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'benefit_plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('harassment', 'Harassment'), ('discrimination', 'Discrimination'), ('workplace_safety', 'Workplace Safety'), ('policy_violation', 'Policy Violation'), ('compensation', 'Compensation'), ('management', 'Management'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('investigation', 'Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_grievances', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='tenants.tenant')),
            ],
            options={
                'db_table': 'grievance_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KBCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('icon', models.CharField(default='📖', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('article_count', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='platform_core.kbcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_categories', to='tenants.tenant')),
            ],
            options={
                'db_table': 'kb_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('content', models.TextField(help_text='Markdown/HTML content')),
                ('excerpt', models.CharField(blank=True, max_length=500)),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_articles', to='tenants.tenant')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='platform_core.kbcategory')),
            ],
            options={
                'db_table': 'kb_articles',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('leadership', 'Leadership'), ('domain', 'Domain Knowledge'), ('language', 'Language'), ('certification', 'Certification')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('proficiency_levels', models.JSONField(default=list, help_text='\n        [{"level":1,"name":"Beginner"},{"level":2,"name":"Intermediate"},\n         {"level":3,"name":"Advanced"},{"level":4,"name":"Expert"}]\n    ')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='tenants.tenant')),
            ],
            options={
                'db_table': 'skill_definitions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BenefitEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('coverage_tier', models.CharField(blank=True, help_text='e.g. Employee Only, Employee+Spouse, Family', max_length=50)),
                ('dependents', models.JSONField(default=list, help_text='List of dependent details')),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('payroll_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_enrollments', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_enrollments', to='tenants.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='platform_core.benefitplan')),
            ],
            options={
                'db_table': 'benefit_enrollments',
                'unique_together': {('employee', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency_level', models.IntegerField(default=1)),
                ('target_level', models.IntegerField(blank=True, help_text='Desired proficiency', null=True)),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('last_assessed', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core_hr.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='platform_core.skilldefinition')),
            ],
            options={
                'db_table': 'employee_skills',
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
