# Generated by Django 5.2.11 on 2026-03-09 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('agency_crm', '0001_initial'),
        ('job_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active Partner'), ('probation', 'On Probation'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('specializations', models.JSONField(default=list)),
                ('geographies', models.JSONField(default=list)),
                ('markup_fee_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('agreement_url', models.URLField(blank=True)),
                ('insurance_verified', models.BooleanField(default=False)),
                ('compliance_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_partners', to='agencies.agency')),
            ],
            options={
                'db_table': 'vms_subcontractor',
                'ordering': ['partner_name'],
            },
        ),
        migrations.CreateModel(
            name='VMSIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('beeline', 'Beeline'), ('fieldglass', 'SAP Fieldglass'), ('iqn', 'IQN / Coupa'), ('peoplefluent', 'PeopleFluent'), ('shiftwise', 'ShiftWise'), ('vndly', 'VNDLY'), ('simplyvms', 'SimplyVMS'), ('custom', 'Custom / Other')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('active', 'Active'), ('paused', 'Paused'), ('error', 'Integration Error'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('api_endpoint', models.URLField(blank=True)),
                ('api_key_hint', models.CharField(blank=True, max_length=50)),
                ('vendor_id', models.CharField(blank=True, max_length=100)),
                ('sync_job_feeds', models.BooleanField(default=True)),
                ('sync_submittals', models.BooleanField(default=True)),
                ('sync_interviews', models.BooleanField(default=True)),
                ('sync_timesheets', models.BooleanField(default=False)),
                ('sync_invoices', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('last_sync_error', models.TextField(blank=True)),
                ('is_msp_managed', models.BooleanField(default=False)),
                ('msp_name', models.CharField(blank=True, max_length=200)),
                ('program_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms_integrations', to='agencies.agency')),
                ('client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms_integrations', to='agency_crm.clientaccount')),
            ],
            options={
                'db_table': 'vms_integration',
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='VendorScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_label', models.CharField(max_length=50)),
                ('fill_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('time_to_submit_days', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('submittal_to_interview_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('offer_to_start_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('compliance_score', models.IntegerField(blank=True, null=True)),
                ('overall_rank', models.IntegerField(blank=True, null=True)),
                ('total_vendors', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_scorecards', to='agencies.agency')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='vendor_vms.vmsintegration')),
            ],
            options={
                'db_table': 'vms_vendor_scorecard',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VMSJobFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vms_job_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New (Unprocessed)'), ('matched', 'Matched to Job Order'), ('active', 'Active'), ('filled', 'Filled'), ('cancelled', 'Cancelled / Closed')], default='new', max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_feeds', to='vendor_vms.vmsintegration')),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms_feeds', to='job_orders.joborder')),
            ],
            options={
                'db_table': 'vms_job_feed',
                'unique_together': {('integration', 'vms_job_id')},
            },
        ),
    ]
