# Generated by Django 5.2.11 on 2026-03-07 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0005_criticalrole_internalmobilityprofile'),
        ('learning', '0001_initial'),
        ('tenants', '0003_billing_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('program_type', models.CharField(choices=[('one_on_one', 'One-on-One'), ('group', 'Group'), ('peer', 'Peer'), ('reverse', 'Reverse Mentorship')], default='one_on_one', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_matches', models.IntegerField(blank=True, null=True)),
                ('matching_criteria', models.JSONField(blank=True, default=dict, help_text='{"skills":[],"departments":[],"seniority_gap":0}')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_programs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'mentorship_programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('goals', models.TextField(blank=True)),
                ('meeting_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('adhoc', 'Ad-Hoc')], default='monthly', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_matches', to='core_hr.employee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_matches', to='core_hr.employee')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='learning.mentorshipprogram')),
            ],
            options={
                'db_table': 'mentorship_matches',
                'ordering': ['-matched_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillPathway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_skills', models.JSONField(blank=True, default=list, help_text='List of skill definition IDs this pathway develops')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='List of position IDs this pathway prepares for')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pathways', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_pathways', to='tenants.tenant')),
            ],
            options={
                'db_table': 'skill_pathways',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LXPRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('skill_gap', 'Skill Gap'), ('career_goal', 'Career Goal'), ('role_transition', 'Role Transition'), ('mandatory', 'Mandatory'), ('peer_completion', 'Peer Completion'), ('manager_assigned', 'Manager Assigned')], default='skill_gap', max_length=50)),
                ('reason_detail', models.TextField(blank=True)),
                ('score', models.FloatField(default=0.0, help_text='Relevance score 0.0–1.0')),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lxp_recommendations', to='learning.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lxp_recommendations', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lxp_recommendations', to='tenants.tenant')),
                ('pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lxp_recommendations', to='learning.skillpathway')),
            ],
            options={
                'db_table': 'lxp_recommendations',
                'ordering': ['-score', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PathwayStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_steps', to='learning.course')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learning.skillpathway')),
            ],
            options={
                'db_table': 'pathway_steps',
                'ordering': ['pathway', 'order'],
                'unique_together': {('pathway', 'order')},
            },
        ),
    ]
