# Generated by Django 5.2.11 on 2026-02-25 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=5)),
                ('alias_normalized', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'db_table': 'location_aliases',
            },
        ),
        migrations.CreateModel(
            name='SkillTaxonomy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('programming_language', 'Programming Language'), ('framework', 'Framework'), ('tool', 'Tool'), ('platform', 'Platform'), ('methodology', 'Methodology'), ('soft_skill', 'Soft Skill'), ('domain', 'Domain'), ('certification', 'Certification'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Skill taxonomy',
                'db_table': 'skill_taxonomy',
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='TitleAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_title', models.CharField(max_length=200)),
                ('alias_normalized', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'db_table': 'title_aliases',
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_normalized', models.CharField(db_index=True, max_length=200)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='taxonomy.skilltaxonomy')),
            ],
            options={
                'db_table': 'skill_aliases',
                'unique_together': {('alias_normalized',)},
            },
        ),
    ]
