# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpatAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_country', models.CharField(max_length=2)),
                ('host_country', models.CharField(max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term'), ('permanent_transfer', 'Permanent Transfer'), ('commuter', 'Commuter')], default='long_term', max_length=30)),
                ('home_base_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('host_allowances', models.JSONField(default=dict, help_text='{"housing": 0, "cola": 0, "school": 0, "car": 0}')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('extended', 'Extended'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('supporting_family', models.BooleanField(default=False)),
                ('family_members', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expat_assignments', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expat_assignments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'expat_assignments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MultiCurrencyRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=16)),
                ('effective_date', models.DateField()),
                ('source', models.CharField(blank=True, help_text="e.g. 'CBSL', 'manual', 'open_exchange_rates'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_currency_rates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'multi_currency_rates',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='VisaPermit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permit_type', models.CharField(choices=[('work_visa', 'Work Visa'), ('residence_permit', 'Residence Permit'), ('work_permit', 'Work Permit'), ('dependent_visa', 'Dependent Visa'), ('business_visa', 'Business Visa'), ('other', 'Other')], max_length=30)),
                ('country', models.CharField(max_length=2)),
                ('permit_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('applied', 'Applied'), ('renewal_pending', 'Renewal Pending')], max_length=20)),
                ('supporting_documents', models.JSONField(default=list)),
                ('reminder_days_before', models.IntegerField(default=60)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_permits', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_permits', to='tenants.tenant')),
            ],
            options={
                'db_table': 'visa_permits',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='CountryPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(help_text="ISO 3166-1 alpha-2, e.g. 'LK'", max_length=2)),
                ('country_name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('timezone', models.CharField(max_length=50)),
                ('statutory_rules', models.JSONField(default=dict, help_text='Country-specific statutory/compliance rules')),
                ('holiday_convention', models.CharField(blank=True, max_length=50)),
                ('work_week', models.JSONField(default=list, help_text='[1,2,3,4,5] — Mon=1, Tue=2, ..., Sun=7')),
                ('standard_work_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('is_enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_packs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'country_packs',
                'unique_together': {('tenant', 'country_code')},
            },
        ),
    ]
