# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0005_offer_esign_document_url_offer_esign_envelope_id_and_more'),
        ('jobs', '0005_job_degree_optional_note_job_degree_required_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseRateForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_acceptance_probability', models.FloatField(help_text='0–1 probability')),
                ('key_factors', models.JSONField(blank=True, default=list, help_text='EU AI Act Annex III — top factors influencing prediction')),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('forecast_date', models.DateField(auto_now_add=True)),
                ('actual_outcome', models.CharField(blank=True, default='', help_text='accepted/declined — populated after outcome known', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_rate_forecasts', to='applications.application')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_rate_forecasts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'close_rate_forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='FairnessReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('gender', 'Gender Parity'), ('ethnicity', 'Ethnic Diversity'), ('age', 'Age Equity'), ('disability', 'Disability Inclusion'), ('combined', 'Combined Equity')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('funnel_data', models.JSONField(blank=True, default=dict, help_text='{"applied": {"female": 120, "male": 180}, "hired": {...}}')),
                ('adverse_impact_flags', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, help_text='Null = tenant-wide report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fairness_reports', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fairness_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairness_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'fairness_reports',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PipelineBottleneck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=100)),
                ('avg_days_in_stage', models.FloatField()),
                ('benchmark_days', models.FloatField(help_text='Expected / target days in stage')),
                ('candidates_stuck', models.IntegerField(default=0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('suggested_action', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottlenecks', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_bottlenecks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'pipeline_bottlenecks',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='FillTimeForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_days_to_fill', models.FloatField()),
                ('confidence_interval_low', models.FloatField(blank=True, null=True)),
                ('confidence_interval_high', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('feature_importances', models.JSONField(blank=True, default=dict, help_text='EU AI Act Annex III — explainability: feature weights used in prediction')),
                ('forecast_date', models.DateField(auto_now_add=True)),
                ('actual_days_to_fill', models.FloatField(blank=True, help_text='Populated when job closes', null=True)),
                ('human_reviewed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_time_forecasts', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_time_forecasts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'fill_time_forecasts',
                'ordering': ['-forecast_date'],
                'indexes': [models.Index(fields=['tenant', 'job'], name='fill_time_f_tenant__c6b915_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterviewerLoadForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('predicted_interview_count', models.IntegerField(default=0)),
                ('predicted_hours', models.FloatField(default=0.0)),
                ('capacity_hours', models.FloatField(default=10.0, help_text='Hours available for interviews per week')),
                ('overloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_forecasts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_load_forecasts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'interviewer_load_forecasts',
                'ordering': ['week_start'],
                'unique_together': {('tenant', 'interviewer', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='ProcessAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('sla_breach', 'SLA Breach'), ('idle_candidates', 'Idle Candidates'), ('low_pipeline', 'Low Pipeline Volume'), ('high_drop_off', 'High Drop-off Rate'), ('bias_signal', 'Bias Signal Detected'), ('vendor_sla_breach', 'Vendor SLA Breach'), ('interviewer_overload', 'Interviewer Overload'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_process_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_alerts', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_alerts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'process_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='process_ale_tenant__1b816d_idx'), models.Index(fields=['tenant', 'alert_type'], name='process_ale_tenant__f5ece1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecruiterCapacityPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('planned_open_roles', models.IntegerField(default=0)),
                ('actual_open_roles', models.IntegerField(default=0)),
                ('planned_hires', models.IntegerField(default=0)),
                ('actual_hires', models.IntegerField(default=0)),
                ('capacity_utilisation_pct', models.FloatField(blank=True, help_text='Actual / planned * 100', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_plans', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_capacity_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'recruiter_capacity_plans',
                'ordering': ['-period_start'],
                'unique_together': {('tenant', 'recruiter', 'period_start')},
            },
        ),
    ]
