"""Celery tasks for Vendor Management app."""

from celery import shared_task


@shared_task(name="apps.vendor_management.tasks.check_vendor_sla_compliance")
def check_vendor_sla_compliance():
    """
    Check VendorSLA rules against recent VendorSubmissions.
    Creates ProcessAlerts for any SLA breaches detected.
    """
    from django.utils import timezone
    from datetime import timedelta
    from apps.vendor_management.models import VendorSLA, VendorSubmission
    from apps.analytics_forecasting.models import ProcessAlert

    now = timezone.now()
    breaches_created = 0

    for sla in VendorSLA.objects.filter(is_active=True).select_related("agency", "tenant"):
        # Check max_time_to_submit_days: submissions that took too long
        threshold_date = now - timedelta(days=sla.max_time_to_submit_days)
        slow_submissions = VendorSubmission.objects.filter(
            tenant=sla.tenant,
            agency=sla.agency,
            submitted_at__lt=threshold_date,
            status="submitted",
        ).count()

        if slow_submissions > 0:
            alert_title = (
                f"Vendor SLA breach: {sla.agency.name} — "
                f"{slow_submissions} submission(s) past {sla.max_time_to_submit_days}d limit"
            )
            # Avoid duplicate open alerts for same agency
            already_open = ProcessAlert.objects.filter(
                tenant=sla.tenant,
                alert_type="vendor_sla_breach",
                status="open",
                title=alert_title,
            ).exists()
            if not already_open:
                ProcessAlert.objects.create(
                    tenant=sla.tenant,
                    alert_type="vendor_sla_breach",
                    title=alert_title,
                    detail=(
                        f"Agency '{sla.agency.name}' has {slow_submissions} open submission(s) "
                        f"older than {sla.max_time_to_submit_days} days. SLA requires submissions "
                        f"within {sla.max_time_to_submit_days} days."
                    ),
                    severity="high",
                    assigned_to=sla.breach_escalation_contact,
                )
                breaches_created += 1

    return {"sla_breach_alerts_created": breaches_created}


@shared_task(name="apps.vendor_management.tasks.generate_vendor_scorecards")
def generate_vendor_scorecards():
    """
    Monthly task: compute scorecard metrics per agency for the previous calendar month
    and upsert a VendorScorecard record.
    """
    from django.utils import timezone
    from datetime import date
    from apps.vendor_management.models import VendorAgency, VendorSubmission, VendorScorecard

    today = date.today()
    # Previous month boundaries
    first_of_this_month = today.replace(day=1)
    last_of_prev_month = first_of_this_month - timezone.timedelta(days=1)
    first_of_prev_month = last_of_prev_month.replace(day=1)

    scorecards_created = 0
    for agency in VendorAgency.objects.filter(is_active=True).select_related("tenant"):
        submissions = VendorSubmission.objects.filter(
            tenant=agency.tenant,
            agency=agency,
            submitted_at__date__gte=first_of_prev_month,
            submitted_at__date__lte=last_of_prev_month,
        )
        total = submissions.count()
        accepted = submissions.filter(status="accepted").count()
        rejected = submissions.filter(status="rejected").count()

        # Simple quality score: acceptance rate * 100
        quality_score = (accepted / total * 100) if total > 0 else None

        VendorScorecard.objects.create(
            tenant=agency.tenant,
            agency=agency,
            period_start=first_of_prev_month,
            period_end=last_of_prev_month,
            submissions_count=total,
            hires_count=accepted,
            quality_score=quality_score,
            notes=f"Auto-generated by monthly scorecard task. Accepted={accepted}, Rejected={rejected}.",
        )
        scorecards_created += 1

    return {"scorecards_created": scorecards_created}
