# Generated by Django 5.2.11 on 2026-02-25 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=300)),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, default='', max_length=30)),
                ('headline', models.CharField(blank=True, default='', max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('location_normalized', models.JSONField(blank=True, help_text='{"city": "...", "country_code": "..."}', null=True)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('total_experience_years', models.FloatField(blank=True, null=True)),
                ('most_recent_title', models.CharField(blank=True, default='', max_length=200)),
                ('most_recent_company', models.CharField(blank=True, default='', max_length=200)),
                ('recency_score', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='direct', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('merged', 'Merged'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redirect_to', models.ForeignKey(blank=True, help_text='If merged, points to the target candidate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=300)),
                ('degree', models.CharField(blank=True, default='', max_length=200)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'candidate_education',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('normalized_title', models.CharField(blank=True, default='', max_length=300)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('raw_block', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'candidate_experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('linkedin', 'LinkedIn'), ('github', 'GitHub')], max_length=20)),
                ('identity_value', models.CharField(max_length=500)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'candidate_identities',
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=200)),
                ('confidence', models.FloatField(default=1.0)),
                ('years_used', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list, help_text='Matched text excerpts')),
                ('source_section', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidates.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='taxonomy.skilltaxonomy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'candidate_skills',
            },
        ),
        migrations.CreateModel(
            name='MergeAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_sources', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('to_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_targets', to='candidates.candidate')),
            ],
            options={
                'db_table': 'merge_audits',
            },
        ),
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('file_url', models.CharField(max_length=500)),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('file_type', models.CharField(default='application/pdf', max_length=50)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('clean_text', models.TextField(blank=True, default='')),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('pending_parse', 'Pending Parse'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending_parse', max_length=20)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('parse_confidence', models.FloatField(blank=True, null=True)),
                ('parse_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'resume_documents',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['tenant', 'primary_email'], name='candidates_tenant__7fd874_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['tenant', 'created_at'], name='candidates_tenant__db6fca_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['tenant', 'status'], name='candidates_tenant__5b5e41_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateidentity',
            index=models.Index(fields=['tenant', 'identity_value'], name='candidate_i_tenant__81fae9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateidentity',
            unique_together={('tenant', 'identity_type', 'identity_value')},
        ),
        migrations.AlterUniqueTogether(
            name='candidateskill',
            unique_together={('candidate', 'skill')},
        ),
        migrations.AddIndex(
            model_name='resumedocument',
            index=models.Index(fields=['tenant', 'candidate', 'version'], name='resume_docu_tenant__2dde91_idx'),
        ),
    ]
