# Generated by Django 5.2.11 on 2026-02-27 04:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('tenants', '0002_tenantsettings_api_rate_limit_per_minute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('issuer', models.CharField(blank=True, default='', max_length=300)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'candidate_certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal = not visible to candidate')),
                ('mentions', models.JSONField(blank=True, default=list, help_text='User IDs mentioned via @')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidate_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='availability',
            field=models.CharField(choices=[('immediate', 'Immediately Available'), ('2_weeks', '2 Weeks Notice'), ('1_month', '1 Month Notice'), ('3_months', '3 Months Notice'), ('not_looking', 'Not Looking')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='consent_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='data_retention_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(blank=True, default='', help_text='PhD, Masters, Bachelors, Associate, High School', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pool_status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('pipeline', 'In Pipeline'), ('hired', 'Hired'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rating',
            field=models.IntegerField(blank=True, help_text='1-5 star rating', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_completeness',
            field=models.FloatField(blank=True, help_text='0-100 how complete the parsed profile is', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='talent_tier',
            field=models.CharField(choices=[('none', 'None'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='none', max_length=20),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['tenant', 'pool_status'], name='candidates_tenant__aa73fc_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['tenant', 'talent_tier'], name='candidates_tenant__8954d0_idx'),
        ),
        migrations.AddField(
            model_name='candidatecertification',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='candidatecertification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='candidatenote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatenote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='candidatenote',
            name='parent_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='candidates.candidatenote'),
        ),
        migrations.AddField(
            model_name='candidatenote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='candidatenote',
            index=models.Index(fields=['tenant', 'candidate', 'created_at'], name='candidate_n_tenant__204568_idx'),
        ),
    ]
