# Generated by Django 5.2.11 on 2026-03-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidatecertification_candidatenote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gdpr_deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pool_status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('pipeline', 'In Pipeline'), ('hired', 'Hired'), ('archived', 'Archived'), ('gdpr_deleted', 'GDPR Deleted')], default='new', max_length=20),
        ),
    ]
