# Generated by Django 5.2.11 on 2026-03-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_gin_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at']},
        ),
    ]
