# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_datasubjectrequest'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFollowUpTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('snoozed', 'Snoozed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidate_followup_tasks',
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateOutreachLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('linkedin', 'LinkedIn'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('in_person', 'In Person'), ('other', 'Other')], default='email', max_length=20)),
                ('outcome', models.CharField(choices=[('no_response', 'No Response'), ('positive', 'Positive Response'), ('negative', 'Not Interested'), ('callback_requested', 'Callback Requested'), ('meeting_booked', 'Meeting Booked')], default='no_response', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('contacted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'candidate_outreach_logs',
                'ordering': ['-contacted_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='datasubjectrequest',
            new_name='data_subjec_tenant__8bd078_idx',
            old_name='dsr_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='datasubjectrequest',
            new_name='data_subjec_request_1bd4ad_idx',
            old_name='dsr_email_idx',
        ),
        migrations.AddField(
            model_name='candidate',
            name='crm_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='crm_stage',
            field=models.CharField(blank=True, choices=[('prospect', 'Prospect'), ('engaged', 'Engaged'), ('nurturing', 'Nurturing'), ('warm', 'Warm'), ('converted', 'Converted'), ('inactive', 'Inactive')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='do_not_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='next_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatefollowuptask',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='candidatefollowuptask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatefollowuptask',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_followup_tasks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='candidateoutreachlog',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_logs', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='candidateoutreachlog',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateoutreachlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_logs', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='candidatefollowuptask',
            index=models.Index(fields=['tenant', 'candidate', 'status'], name='candidate_f_tenant__21a754_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatefollowuptask',
            index=models.Index(fields=['tenant', 'owner', 'status'], name='candidate_f_tenant__b0c8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateoutreachlog',
            index=models.Index(fields=['tenant', 'candidate', 'contacted_at'], name='candidate_o_tenant__19a642_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateoutreachlog',
            index=models.Index(fields=['tenant', 'sender'], name='candidate_o_tenant__86f1fe_idx'),
        ),
    ]
