# Generated by Django 5.2.11 on 2026-03-08 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_talentpool_nurturecampaign_talentpoolmember'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='alert_quality_score',
            field=models.FloatField(default=0.0, help_text='0-100 score based on engagement (open/click/apply rate)'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company-specific alert (new jobs from this company)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followers_alerts', to='employers.employeraccount'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='salary_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alert when jobs with salary >= this amount are posted', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='work_arrangement',
            field=models.CharField(blank=True, default='', help_text='Filter by work arrangement (remote/onsite/hybrid)', max_length=10),
        ),
        migrations.CreateModel(
            name='AlertEngagementLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_job_id', models.UUIDField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_job_id', models.UUIDField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to='notifications.jobalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jf_alert_engagement_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
