# Generated by Django 5.2.11 on 2026-03-07 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0004_alter_employee_options_historicalemployee'),
        ('tenants', '0003_billing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('warning_letter', 'Warning Letter'), ('employment_certificate', 'Employment Certificate'), ('nda', 'NDA'), ('policy_acknowledgement', 'Policy Acknowledgement'), ('contract', 'Contract'), ('custom', 'Custom')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='HTML/Markdown template with {{variable}} placeholders')),
                ('variables', models.JSONField(default=list, help_text='[{"key": "employee_name", "label": "Employee Name", "required": true}]')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'document_templates',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('variables_used', models.JSONField(default=dict)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('e_sign_provider', models.CharField(blank=True, max_length=50)),
                ('e_sign_request_id', models.CharField(blank=True, max_length=200)),
                ('e_sign_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='core_hr.employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='documents_policies.documenttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='tenants.tenant')),
            ],
            options={
                'db_table': 'generated_documents',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('hr_policy', 'HR Policy'), ('code_of_conduct', 'Code of Conduct'), ('safety', 'Safety'), ('data_privacy', 'Data Privacy'), ('leave', 'Leave'), ('benefits', 'Benefits'), ('it_security', 'IT Security'), ('custom', 'Custom')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('requires_acknowledgement', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('target_audience', models.JSONField(default=dict, help_text='{"departments": [], "grades": [], "all": true}')),
                ('attachments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_documents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_documents', to='tenants.tenant')),
            ],
            options={
                'db_table': 'policy_documents',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to='core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to='tenants.tenant')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='documents_policies.policydocument')),
            ],
            options={
                'db_table': 'policy_acknowledgements',
                'unique_together': {('policy', 'employee')},
            },
        ),
    ]
