# Generated by Django 5.1 on 2026-03-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0005_offer_esign_document_url_offer_esign_envelope_id_and_more'),
        ('candidates', '0008_candidatefollowuptask_candidateoutreachlog_and_more'),
        ('tenants', '0004_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WCAGCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion_number', models.CharField(help_text='e.g. 1.1.1, 2.4.7', max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('A', 'Level A'), ('AA', 'Level AA'), ('AAA', 'Level AAA')], default='AA', max_length=3)),
                ('guideline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('testing_procedure', models.TextField(blank=True, default='')),
                ('wcag_version', models.CharField(default='2.2', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wcag_criteria',
                'ordering': ['criterion_number'],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contrast_mode', models.CharField(choices=[('default', 'Default'), ('high_contrast', 'High Contrast'), ('dark_mode', 'Dark Mode')], default='default', max_length=20)),
                ('font_size', models.CharField(choices=[('default', 'Default'), ('large', 'Large'), ('x_large', 'Extra Large')], default='default', max_length=20)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('screen_reader_optimised', models.BooleanField(default=False)),
                ('captions_preferred', models.BooleanField(default=False)),
                ('keyboard_nav_only', models.BooleanField(default=False)),
                ('custom_preferences', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='a11y_ops_preference', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_preferences', to='tenants.tenant')),
            ],
            options={
                'db_table': 'a11y_ops_preferences',
            },
        ),
        migrations.CreateModel(
            name='AccessibilityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('career_site', 'Career Site'), ('candidate_portal', 'Candidate Portal'), ('recruiter_ui', 'Recruiter UI'), ('email_template', 'Email Template'), ('pdf_document', 'PDF Document'), ('api', 'API Response'), ('other', 'Other')], default='other', max_length=30)),
                ('scope_detail', models.CharField(blank=True, default='', help_text='e.g. URL, component name', max_length=255)),
                ('review_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('remediation_required', 'Remediation Required')], default='planned', max_length=30)),
                ('tool_used', models.CharField(blank=True, default='', help_text='e.g. axe-core, WAVE, manual screen reader', max_length=100)),
                ('conformance_level_target', models.CharField(default='AA', max_length=3)),
                ('overall_result', models.CharField(blank=True, default='', help_text='pass / fail / partial', max_length=20)),
                ('issues_found', models.IntegerField(default=0)),
                ('issues_resolved', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessibility_reviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_reviews', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accessibility_reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accommodation_type', models.CharField(help_text='e.g. Extended assessment time, Screen reader, Sign language interpreter', max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('partially_approved', 'Partially Approved'), ('denied', 'Denied'), ('completed', 'Completed')], default='submitted', max_length=30)),
                ('approved_accommodation', models.TextField(blank=True, default='', help_text='What was actually provided')),
                ('denial_reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_requests', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_requests', to='candidates.candidate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accommodation_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DemographicDataPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_gender', models.BooleanField(default=False)),
                ('allow_ethnicity', models.BooleanField(default=False)),
                ('allow_disability', models.BooleanField(default=False)),
                ('allow_age_band', models.BooleanField(default=False)),
                ('allow_veteran_status', models.BooleanField(default=False)),
                ('allow_pronouns', models.BooleanField(default=False)),
                ('consent_version', models.CharField(blank=True, default='', max_length=20)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_permissions', to='candidates.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_permissions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'demographic_data_permissions',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_applicable', 'Not Applicable'), ('not_tested', 'Not Tested')], default='not_tested', max_length=20)),
                ('finding', models.TextField(blank=True, default='')),
                ('screenshot_url', models.URLField(blank=True, default='')),
                ('remediation_ticket_url', models.URLField(blank=True, default='')),
                ('remediated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_evidence', to='tenants.tenant')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='accessibility_ops.accessibilityreview')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='accessibility_ops.wcagcriterion')),
            ],
            options={
                'db_table': 'accessibility_evidence',
                'ordering': ['review', 'criterion__criterion_number'],
                'unique_together': {('review', 'criterion')},
            },
        ),
    ]
